[pytest]
testpaths = tests
pythonpath = .
python_files = test*.py *Test.py Test*.py
python_classes = Test*
python_functions = test*
addopts =
    -v
    --tb=short
    --strict-markers
    --durations=10
    --maxfail=25
    --cov src
markers =
    all: runs all tests including slow ones
    unit: marks tests as unit tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
