#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#  python pwb.py wd/wikinews
#
#
import re
import time
import codecs
from API.maindir import main_dir
import pywikibot
#import sys
import unicodedata
#import urllib
#import urllib.request
#import urllib.parse
import unicodedata
#---
import sys
#---
svwiki = {
	"الإكوادور"	:	"Kategori:Robotskapade Ecuadorartiklar",
	"الإمارات العربية المتحدة"	:	"Kategori:Robotskapade Förenade Arabemiratenartiklar",
	"الأرجنتين"	:	"Kategori:Robotskapade Argentinaartiklar",
	"الأردن"	:	"Kategori:Robotskapade Jordanienartiklar",
	"البحرين"	:	"Kategori:Robotskapade Bahrainartiklar",
	"البرازيل"	:	"Kategori:Robotskapade Brasilienartiklar",
	"البوسنة والهرسك"	:	"Kategori:Robotskapade Bosnien och Hercegovinaartiklar",
	"التشيك"	:	"Kategori:Robotskapade Tjeckienartiklar",
	"الجبل الأسود"	:	"Kategori:Robotskapade Montenegroartiklar",
	"الجزائر"	:	"Kategori:Robotskapade Algerietartiklar",
	"الجزر الكاريبية الهولندية"	:	"Kategori:Robotskapade Karibiska Nederländernaartiklar",
	"الدنمارك"	:	"Kategori:Robotskapade Danmarkartiklar",
	"الرأس الأخضر"	:	"Kategori:Robotskapade Kap Verdeartiklar",
	"الصحراء الغربية"	:	"Kategori:Robotskapade Västsaharaartiklar",
	"الصين"	:	"Kategori:Robotskapade Kinaartiklar",
	"العراق"	:	"Kategori:Robotskapade Irakartiklar",
	"الغابون"	:	"Kategori:Robotskapade Gabonartiklar",
	"الفلبين"	:	"Kategori:Robotskapade Filippinernaartiklar",
	"القارة القطبية الجنوبية"	:	"Kategori:Robotskapade Antarktisartiklar",
	"الكاميرون"	:	"Kategori:Robotskapade Kamerunartiklar",
	"الكويت"	:	"Kategori:Robotskapade Kuwaitartiklar",
	"المجر"	:	"Kategori:Robotskapade Ungernartiklar",
	"المغرب"	:	"Kategori:Robotskapade Marockoartiklar",
	"المكسيك"	:	"Kategori:Robotskapade Mexikoartiklar",
	"المملكة المتحدة"	:	"Kategori:Robotskapade Storbritannienartiklar",
	"النمسا"	:	"Kategori:Robotskapade Österrikeartiklar",
	"الهند"	:	"Kategori:Robotskapade Indienartiklar",
	"اليونان"	:	"Kategori:Robotskapade Greklandartiklar",
	"إثيوبيا"	:	"Kategori:Robotskapade Etiopienartiklar",
	"إريتريا"	:	"Kategori:Robotskapade Eritreaartiklar",
	"إسبانيا"	:	"Kategori:Robotskapade Spanienartiklar",
	"إستونيا"	:	"Kategori:Robotskapade Estlandartiklar",
	"إسرائيل"	:	"Kategori:Robotskapade Israelartiklar",
	"إندونيسيا"	:	"Kategori:Robotskapade Indonesienartiklar",
	"إيران"	:	"Kategori:Robotskapade Iranartiklar",
	"أذربيجان"	:	"Kategori:Robotskapade Azerbajdzjanartiklar",
	"أرمينيا"	:	"Kategori:Robotskapade Armenienartiklar",
	"أستراليا"	:	"Kategori:Robotskapade Australienartiklar",
	"أفغانستان"	:	"Kategori:Robotskapade Afghanistanartiklar",
	"ألبانيا"	:	"Kategori:Robotskapade Albanienartiklar",
	"أنتيغوا وباربودا"	:	"Kategori:Robotskapade Antigua och Barbudaartiklar",
	"أندورا"	:	"Kategori:Robotskapade Andorraartiklar",
	"أنغولا"	:	"Kategori:Robotskapade Angolaartiklar",
	"آيسلندا"	:	"Kategori:Robotskapade Islandartiklar",
	"باربادوس"	:	"Kategori:Robotskapade Barbadosartiklar",
	"باهاماس"	:	"Kategori:Robotskapade Bahamasartiklar",
	"برمودا"	:	"Kategori:Robotskapade Bermudaartiklar",
	"بروناي"	:	"Kategori:Robotskapade Bruneiartiklar",
	"بلجيكا"	:	"Kategori:Robotskapade Belgienartiklar",
	"بلغاريا"	:	"Kategori:Robotskapade Bulgarienartiklar",
	"بليز"	:	"Kategori:Robotskapade Belizeartiklar",
	"بنغلاديش"	:	"Kategori:Robotskapade Bangladeshartiklar",
	"بنين"	:	"Kategori:Robotskapade Beninartiklar",
	"بوتان"	:	"Kategori:Robotskapade Bhutanartiklar",
	"بوتسوانا"	:	"Kategori:Robotskapade Botswanaartiklar",
	"بوركينا فاسو"	:	"Kategori:Robotskapade Burkina Fasoartiklar",
	"بوروندي"	:	"Kategori:Robotskapade Burundiartiklar",
	"بوليفيا"	:	"Kategori:Robotskapade Boliviaartiklar",
	"تشيلي"	:	"Kategori:Robotskapade Chileartiklar",
	"جامايكا"	:	"Kategori:Robotskapade Jamaicaartiklar",
	"جرينلاند"	:	"Kategori:Robotskapade Grönlandartiklar",
	"جزر القمر"	:	"Kategori:Robotskapade Komorernaartiklar",
	"جزر المالديف"	:	"Kategori:Robotskapade Maldivernaartiklar",
	"جزر أولاند"	:	"Kategori:Robotskapade Ålandartiklar",
	"جزر فارو"	:	"Kategori:Robotskapade Färöarnaartiklar",
	"جزر فوكلاند"	:	"Kategori:Robotskapade Falklandsöarnaartiklar",
	"جزر كايمان"	:	"Kategori:Robotskapade Caymanöarnaartiklar",
	"جزر كوك"	:	"Kategori:Robotskapade Cooköarnaartiklar",
	"جزر كوكوس"	:	"Kategori:Robotskapade Kokosöarnaartiklar",
	"جزر مارشال"	:	"Kategori:Robotskapade Marshallöarnaartiklar",
	"جزر ماريانا الشمالية"	:	"Kategori:Robotskapade Nordmarianernaartiklar",
	"جمهورية الدومينيكان"	:	"Kategori:Robotskapade Dominikanska republikenartiklar",
	"جمهورية الكونغو"	:	"Kategori:Robotskapade Kongo-Brazzavilleartiklar",
	"جمهورية الكونغو الديمقراطية"	:	"Kategori:Robotskapade Kongo-Kinshasaartiklar",
	"جمهورية أفريقيا الوسطى"	:	"Kategori:Robotskapade Centralafrikanska republikenartiklar",
	"جمهورية أيرلندا"	:	"Kategori:Robotskapade Irlandartiklar",
	"جمهورية مقدونيا"	:	"Kategori:Robotskapade Makedonienartiklar",
	"جنوب السودان"	:	"Kategori:Robotskapade Sydsudanartiklar",
	"جورجيا"	:	"Kategori:Robotskapade Georgienartiklar",
	"جورجيا الجنوبية وجزر ساندويتش الجنوبية"	:	"Kategori:Robotskapade Sydgeorgien och Sydsandwichöarnaartiklar",
	"جيبوتي"	:	"Kategori:Robotskapade Djiboutiartiklar",
	"جيرزي"	:	"Kategori:Robotskapade Jerseyartiklar",
	"دومينيكا"	:	"Kategori:Robotskapade Dominicaartiklar",
	"روسيا البيضاء"	:	"Kategori:Robotskapade Vitrysslandartiklar",
	"ساحل العاج"	:	"Kategori:Robotskapade Elfenbenskustenartiklar",
	"ساموا الأمريكية"	:	"Kategori:Robotskapade Amerikanska Samoaartiklar",
	"سانت لوسيا"	:	"Kategori:Robotskapade Saint Luciaartiklar",
	"سريلانكا"	:	"Kategori:Robotskapade Sri Lankaartiklar",
	"سوريا"	:	"Kategori:Robotskapade Syrienartiklar",
	"سويسرا"	:	"Kategori:Robotskapade Schweizartiklar",
	"غامبيا"	:	"Kategori:Robotskapade Gambiaartiklar",
	"غانا"	:	"Kategori:Robotskapade Ghanaartiklar",
	"غرينادا"	:	"Kategori:Robotskapade Grenadaartiklar",
	"غواتيمالا"	:	"Kategori:Robotskapade Guatemalaartiklar",
	"غوادلوب"	:	"Kategori:Robotskapade Guadeloupeartiklar",
	"غوام"	:	"Kategori:Robotskapade Guamartiklar",
	"غويانا الفرنسية"	:	"Kategori:Robotskapade Franska Guyanaartiklar",
	"غيانا"	:	"Kategori:Robotskapade Guyanaartiklar",
	"غيرنزي"	:	"Kategori:Robotskapade Guernseyartiklar",
	"غينيا"	:	"Kategori:Robotskapade Guineaartiklar",
	"غينيا الاستوائية"	:	"Kategori:Robotskapade Ekvatorialguineaartiklar",
	"غينيا بيساو"	:	"Kategori:Robotskapade Guinea-Bissauartiklar",
	"فنلندا"	:	"Kategori:Robotskapade Finlandartiklar",
	"فيجي"	:	"Kategori:Robotskapade Fijiartiklar",
	"قبرص"	:	"Kategori:Robotskapade Cypernartiklar",
	"قيرغيزستان"	:	"Kategori:Robotskapade Kirgizistanartiklar",
	"كازاخستان"	:	"Kategori:Robotskapade Kazakstanartiklar",
	"كرواتيا"	:	"Kategori:Robotskapade Kroatienartiklar",
	"كمبوديا"	:	"Kategori:Robotskapade Kambodjaartiklar",
	"كندا"	:	"Kategori:Robotskapade Kanadaartiklar",
	"كوبا"	:	"Kategori:Robotskapade Kubaartiklar",
	"كوريا الجنوبية"	:	"Kategori:Robotskapade Sydkoreaartiklar",
	"كوريا الشمالية"	:	"Kategori:Robotskapade Nordkoreaartiklar",
	"كوستاريكا"	:	"Kategori:Robotskapade Costa Ricaartiklar",
	"كوسوفو"	:	"Kategori:Robotskapade Kosovoartiklar",
	"كولومبيا"	:	"Kategori:Robotskapade Colombiaartiklar",
	"كيريباتي"	:	"Kategori:Robotskapade Kiribatiartiklar",
	"كينيا"	:	"Kategori:Robotskapade Kenyaartiklar",
	"لاتفيا"	:	"Kategori:Robotskapade Lettlandartiklar",
	"لاوس"	:	"Kategori:Robotskapade Laosartiklar",
	"لبنان"	:	"Kategori:Robotskapade Libanonartiklar",
	"لوكسمبورغ"	:	"Kategori:Robotskapade Luxemburgartiklar",
	"ليبيا"	:	"Kategori:Robotskapade Libyenartiklar",
	"ليبيريا"	:	"Kategori:Robotskapade Liberiaartiklar",
	"ليتوانيا"	:	"Kategori:Robotskapade Litauenartiklar",
	"ليسوتو"	:	"Kategori:Robotskapade Lesothoartiklar",
	"مالطا"	:	"Kategori:Robotskapade Maltaartiklar",
	"مالي"	:	"Kategori:Robotskapade Maliartiklar",
	"مدغشقر"	:	"Kategori:Robotskapade Madagaskarartiklar",
	"مصر"	:	"Kategori:Robotskapade Egyptenartiklar",
	"ملاوي"	:	"Kategori:Robotskapade Malawiartiklar",
	"منغوليا"	:	"Kategori:Robotskapade Mongolietartiklar",
	"موريتانيا"	:	"Kategori:Robotskapade Mauretanienartiklar",
	"موريشيوس"	:	"Kategori:Robotskapade Mauritiusartiklar",
	"مولدافيا"	:	"Kategori:Robotskapade Moldavienartiklar",
	"مونتسرات"	:	"Kategori:Robotskapade Montserratartiklar",
	"ميانمار"	:	"Kategori:Robotskapade Burmaartiklar",
	"نيكاراغوا"	:	"Kategori:Robotskapade Nicaraguaartiklar",
	"هايتي"	:	"Kategori:Robotskapade Haitiartiklar",
	"هندوراس"	:	"Kategori:Robotskapade Hondurasartiklar",
	"هونغ كونغ"	:	"Kategori:Robotskapade Hongkongartiklar",
	"ولايات ميكرونيسيا المتحدة"	:	"Kategori:Robotskapade Mikronesiens federerade staterartiklar",

}
cebwiki = {
	"الإكوادور"	:	"Kategoriya:Ecuador_paghimo_ni_bot",
	"الإمارات العربية المتحدة"	:	"Kategoriya:Hiniusang_Emiratong_Arabo_paghimo_ni_bot",
	"الأرجنتين"	:	"Kategoriya:Arhentina_paghimo_ni_bot",
	"الأردن"	:	"Kategoriya:Hordanya_paghimo_ni_bot",
	"الأوروغواي"	:	"Kategoriya:Uruguay_paghimo_ni_bot",
	"البحرين"	:	"Kategoriya:Bareyn_paghimo_ni_bot",
	"البرازيل"	:	"Kategoriya:Brasil_paghimo_ni_bot",
	"البرتغال"	:	"Kategoriya:Portugal_paghimo_ni_bot",
	"البوسنة والهرسك"	:	"Kategoriya:Bosnia_ug_Herzegovina_paghimo_ni_bot",
	"التشيك"	:	"Kategoriya:Tsekya_paghimo_ni_bot",
	"الجبل الأسود"	:	"Kategoriya:Montenegro_paghimo_ni_bot",
	"الجزائر"	:	"Kategoriya:Arhelya_paghimo_ni_bot",
	"الجزر الكاريبية الهولندية"	:	"Kategoriya:Bonaire,_Saint_Eustatius_and_Saba_paghimo_ni_bot",
	"الدنمارك"	:	"Kategoriya:Dinamarka_paghimo_ni_bot",
	"الرأس الأخضر"	:	"Kategoriya:Cabo_Verde_paghimo_ni_bot",
	"السعودية"	:	"Kategoriya:Arabyang_Saudita_paghimo_ni_bot",
	"السلفادور"	:	"Kategoriya:El_Salvador_paghimo_ni_bot",
	"السنغال"	:	"Kategoriya:Senegal_paghimo_ni_bot",
	"السودان"	:	"Kategoriya:Sudan_paghimo_ni_bot",
	"السويد"	:	"Kategoriya:Suwesya_paghimo_ni_bot",
	"الصحراء الغربية"	:	"Kategoriya:Western_Sahara_paghimo_ni_bot",
	"الصومال"	:	"Kategoriya:Somalia_paghimo_ni_bot",
	"الصين"	:	"Kategoriya:Republikang_Popular_sa_Tsina_paghimo_ni_bot",
	"العراق"	:	"Kategoriya:Iraq_paghimo_ni_bot",
	"الغابون"	:	"Kategoriya:Gabon_paghimo_ni_bot",
	"الفلبين"	:	"Kategoriya:Pilipinas_paghimo_ni_bot",
	"القارة القطبية الجنوبية"	:	"Kategoriya:in'Antarctica_paghimo_ni_bot",
	"الكاميرون"	:	"Kategoriya:Kamerun_paghimo_ni_bot",
	"الكويت"	:	"Kategoriya:Kuwait_paghimo_ni_bot",
	"المجر"	:	"Kategoriya:Unggriya_paghimo_ni_bot",
	"المغرب"	:	"Kategoriya:Maruwekos_paghimo_ni_bot",
	"المكسيك"	:	"Kategoriya:Mehiko_paghimo_ni_bot",
	"المملكة المتحدة"	:	"Kategoriya:Hiniusang_Gingharian_paghimo_ni_bot",
	"النرويج"	:	"Kategoriya:Noruwega_paghimo_ni_bot",
	"النمسا"	:	"Kategoriya:Awstriya_paghimo_ni_bot",
	"النيجر"	:	"Kategoriya:Niger_paghimo_ni_bot",
	"الهند"	:	"Kategoriya:Indya_paghimo_ni_bot",
	"الولايات المتحدة"	:	"Kategoriya:Estados_Unidos_paghimo_ni_bot",
	"اليابان"	:	"Kategoriya:Hapon_paghimo_ni_bot",
	"اليمن"	:	"Kategoriya:Yemen_paghimo_ni_bot",
	"اليونان"	:	"Kategoriya:Gresya_paghimo_ni_bot",
	"إثيوبيا"	:	"Kategoriya:Etiopia_paghimo_ni_bot",
	"إريتريا"	:	"Kategoriya:Eritrea_paghimo_ni_bot",
	"إسبانيا"	:	"Kategoriya:Espanya_paghimo_ni_bot",
	"إستونيا"	:	"Kategoriya:Estonia_paghimo_ni_bot",
	"إسرائيل"	:	"Kategoriya:Israel_paghimo_ni_bot",
	"إقليم المحيط الهندي البريطاني"	:	"Kategoriya:British_Indian_Ocean_Territory_paghimo_ni_bot",
	"إندونيسيا"	:	"Kategoriya:Indonesia_paghimo_ni_bot",
	"إيران"	:	"Kategoriya:Iran_paghimo_ni_bot",
	"إيطاليا"	:	"Kategoriya:Italya_paghimo_ni_bot",
	"أذربيجان"	:	"Kategoriya:Aserbaiyan_paghimo_ni_bot",
	"أراض فرنسية جنوبية وأنتارتيكية"	:	"Kategoriya:French_Southern_Territories_paghimo_ni_bot",
	"أرمينيا"	:	"Kategoriya:Armenya_paghimo_ni_bot",
	"أروبا"	:	"Kategoriya:Aruba_paghimo_ni_bot",
	"أستراليا"	:	"Kategoriya:Awstralya_paghimo_ni_bot",
	"أفغانستان"	:	"Kategoriya:Apganistan_paghimo_ni_bot",
	"ألبانيا"	:	"Kategoriya:Albanya_paghimo_ni_bot",
	"ألمانيا"	:	"Kategoriya:Alemanya_paghimo_ni_bot",
	"أنتيغوا وباربودا"	:	"Kategoriya:Antigua_ug_Barbuda_paghimo_ni_bot",
	"أندورا"	:	"Kategoriya:Andorra_paghimo_ni_bot",
	"أنغولا"	:	"Kategoriya:Angola_paghimo_ni_bot",
	"أنغويلا"	:	"Kategoriya:Anguilla_paghimo_ni_bot",
	"أوزبكستان"	:	"Kategoriya:Uzbekistan_paghimo_ni_bot",
	"أوغندا"	:	"Kategoriya:Uganda_paghimo_ni_bot",
	"أوكرانيا"	:	"Kategoriya:Ukranya_paghimo_ni_bot",
	"أيرلندا"	:	"Kategoriya:Ireland_paghimo_ni_bot",
	"آيسلندا"	:	"Kategoriya:Islandya_paghimo_ni_bot",
	"باراغواي"	:	"Kategoriya:Paraguay_paghimo_ni_bot",
	"باربادوس"	:	"Kategoriya:Barbados_paghimo_ni_bot",
	"باكستان"	:	"Kategoriya:Pakistan_paghimo_ni_bot",
	"بالاو"	:	"Kategoriya:Palau_paghimo_ni_bot",
	"باهاماس"	:	"Kategoriya:Bahamas_paghimo_ni_bot",
	"برمودا"	:	"Kategoriya:Bermuda_paghimo_ni_bot",
	"بروناي"	:	"Kategoriya:Brunei_paghimo_ni_bot",
	"بلجيكا"	:	"Kategoriya:Belhika_paghimo_ni_bot",
	"بلغاريا"	:	"Kategoriya:Bulgaria_paghimo_ni_bot",
	"بليز"	:	"Kategoriya:Belize_paghimo_ni_bot",
	"بنغلاديش"	:	"Kategoriya:Bangladesh_paghimo_ni_bot",
	"بنما"	:	"Kategoriya:Panama_paghimo_ni_bot",
	"بنين"	:	"Kategoriya:Benin_paghimo_ni_bot",
	"بوتان"	:	"Kategoriya:Bhutan_paghimo_ni_bot",
	"بوتسوانا"	:	"Kategoriya:Botswana_paghimo_ni_bot",
	"بوركينا فاسو"	:	"Kategoriya:Burkina_Faso_paghimo_ni_bot",
	"بوروندي"	:	"Kategoriya:Burundi_paghimo_ni_bot",
	"بولندا"	:	"Kategoriya:Polonya_paghimo_ni_bot",
	"بوليفيا"	:	"Kategoriya:Bolivia_paghimo_ni_bot",
	"بولينزيا الفرنسية"	:	"Kategoriya:French_Polynesia_paghimo_ni_bot",
	"بيرو"	:	"Kategoriya:Peru_paghimo_ni_bot",
	"تايلاند"	:	"Kategoriya:Tailandya_paghimo_ni_bot",
	"تايوان"	:	"Kategoriya:Republika_sa_Tsina_paghimo_ni_bot",
	"تركمانستان"	:	"Kategoriya:Turkmenistan_paghimo_ni_bot",
	"تركيا"	:	"Kategoriya:Turkiya_paghimo_ni_bot",
	"ترينيداد وتوباغو"	:	"Kategoriya:Trinidad_ug_Tobago_paghimo_ni_bot",
	"تشاد"	:	"Kategoriya:Chad_paghimo_ni_bot",
	"تشيلي"	:	"Kategoriya:Chile_paghimo_ni_bot",
	"تنزانيا"	:	"Kategoriya:Tanzania_paghimo_ni_bot",
	"توغو"	:	"Kategoriya:Togo_paghimo_ni_bot",
	"تونس"	:	"Kategoriya:Tunisia_paghimo_ni_bot",
	"تونغا"	:	"Kategoriya:Tonga_paghimo_ni_bot",
	"تيمور الشرقية"	:	"Kategoriya:Sidlakang_Timor_paghimo_ni_bot",
	"جامايكا"	:	"Kategoriya:Jamaica_paghimo_ni_bot",
	"جبل طارق"	:	"Kategoriya:Gibraltar_paghimo_ni_bot",
	"جرينلاند"	:	"Kategoriya:Greenland_paghimo_ni_bot",
	"جزر العذراء الأمريكية"	:	"Kategoriya:U.S._Virgin_Islands_paghimo_ni_bot",
	"جزر العذراء البريطانية"	:	"Kategoriya:British_Virgin_Islands_paghimo_ni_bot",
	"جزر القمر"	:	"Kategoriya:Comoros_paghimo_ni_bot",
	"جزر الولايات المتحدة الصغيرة النائية"	:	"Kategoriya:United_States_Minor_Outlying_Islands_paghimo_ni_bot",
	"جزر أولاند"	:	"Kategoriya:Aland_Islands_paghimo_ni_bot",
	"جزر توركس وكايكوس"	:	"Kategoriya:Turks_and_Caicos_Islands_paghimo_ni_bot",
	"جزر سليمان"	:	"Kategoriya:Kapupud-ang_Solomon_paghimo_ni_bot",
	"جزر كايمان"	:	"Kategoriya:Cayman_Islands_paghimo_ni_bot",
	"جزر كوك"	:	"Kategoriya:Cook_Islands_paghimo_ni_bot",
	"جزيرة بوفيه"	:	"Kategoriya:Bouvet_Island_paghimo_ni_bot",
	"جزيرة عيد الميلاد"	:	"Kategoriya:Christmas_Island_paghimo_ni_bot",
	"جمهورية الدومينيكان"	:	"Kategoriya:Republikang_Dominikano_paghimo_ni_bot",
	"جمهورية الكونغو"	:	"Kategoriya:Republika_sa_Congo_paghimo_ni_bot",
	"جمهورية الكونغو الديمقراطية"	:	"Kategoriya:Republikang_Demokratiko_sa_Congo_paghimo_ni_bot",
	"جمهورية أفريقيا الوسطى"	:	"Kategoriya:Republikang_Sentral_Aprikano_paghimo_ni_bot",
	"جمهورية مقدونيا"	:	"Kategoriya:Macedonia_paghimo_ni_bot",
	"جنوب السودان"	:	"Kategoriya:Habagatang_Sudan_paghimo_ni_bot",
	"جنوب أفريقيا"	:	"Kategoriya:Habagatang_Aprika_paghimo_ni_bot",
	"جورجيا"	:	"Kategoriya:Georgia_(nasod)_paghimo_ni_bot",
	"جيبوتي"	:	"Kategoriya:Yibuti_paghimo_ni_bot",
	"جيرزي"	:	"Kategoriya:Jersey_paghimo_ni_bot",
	"دومينيكا"	:	"Kategoriya:Dominica_paghimo_ni_bot",
	"روسيا"	:	"Kategoriya:Rusya_paghimo_ni_bot",
	"روسيا البيضاء"	:	"Kategoriya:Biyelorusya_paghimo_ni_bot",
	"رومانيا"	:	"Kategoriya:Rumanya_paghimo_ni_bot",
	"زامبيا"	:	"Kategoriya:Zambia_paghimo_ni_bot",
	"زيمبابوي"	:	"Kategoriya:Zimbabwe_paghimo_ni_bot",
	"ساحل العاج"	:	"Kategoriya:Baybayon_sa_Marpil_paghimo_ni_bot",
	"ساموا"	:	"Kategoriya:Samoa_paghimo_ni_bot",
	"ساموا الأمريكية"	:	"Kategoriya:American_Samoa_paghimo_ni_bot",
	"سريلانكا"	:	"Kategoriya:Sri_Lanka_paghimo_ni_bot",
	"سفالبارد ويان ماين"	:	"Kategoriya:Svalbard_and_Jan_Mayen_paghimo_ni_bot",
	"سلطنة عمان"	:	"Kategoriya:Oman_paghimo_ni_bot",
	"سلوفاكيا"	:	"Kategoriya:Eslobakya_paghimo_ni_bot",
	"سلوفينيا"	:	"Kategoriya:Eslobenya_paghimo_ni_bot",
	"سنغافورة"	:	"Kategoriya:Singgapura_paghimo_ni_bot",
	"سوازيلاند"	:	"Kategoriya:Suwasilandiya_paghimo_ni_bot",
	"سوريا"	:	"Kategoriya:Siria_paghimo_ni_bot",
	"سورينام"	:	"Kategoriya:Surinam_paghimo_ni_bot",
	"سويسرا"	:	"Kategoriya:Swisa_paghimo_ni_bot",
	"سيراليون"	:	"Kategoriya:Sierra_Leone_paghimo_ni_bot",
	"سيشل"	:	"Kategoriya:Seychelles_paghimo_ni_bot",
	"سينت مارتن"	:	"Kategoriya:Sint_Maarten_paghimo_ni_bot",
	"صربيا"	:	"Kategoriya:Serbya_paghimo_ni_bot",
	"طاجيكستان"	:	"Kategoriya:Tayikistan_paghimo_ni_bot",
	"غامبيا"	:	"Kategoriya:Gambia_paghimo_ni_bot",
	"غانا"	:	"Kategoriya:Ghana_paghimo_ni_bot",
	"غرينادا"	:	"Kategoriya:Grenada_paghimo_ni_bot",
	"غواتيمالا"	:	"Kategoriya:Guatemala_paghimo_ni_bot",
	"غوادلوب"	:	"Kategoriya:Guadeloupe_paghimo_ni_bot",
	"غوام"	:	"Kategoriya:Guam_paghimo_ni_bot",
	"غيانا"	:	"Kategoriya:Guyana_paghimo_ni_bot",
	"غيرنزي"	:	"Kategoriya:Guernsey_paghimo_ni_bot",
	"غينيا"	:	"Kategoriya:Guinea_paghimo_ni_bot",
	"غينيا الاستوائية"	:	"Kategoriya:Gineang_Ekwatoryal_paghimo_ni_bot",
	"غينيا بيساو"	:	"Kategoriya:Guinea-Bissau_paghimo_ni_bot",
	"فانواتو"	:	"Kategoriya:Vanuatu_paghimo_ni_bot",
	"فرنسا"	:	"Kategoriya:Pransiya_paghimo_ni_bot",
	"فنزويلا"	:	"Kategoriya:Venezuela_paghimo_ni_bot",
	"فنلندا"	:	"Kategoriya:Finlandia_paghimo_ni_bot",
	"فيتنام"	:	"Kategoriya:Biyetnam_paghimo_ni_bot",
	"فيجي"	:	"Kategoriya:Fiji_paghimo_ni_bot",
	"قبرص"	:	"Kategoriya:Tsipre_paghimo_ni_bot",
	"قطر"	:	"Kategoriya:Katar_paghimo_ni_bot",
	"قيرغيزستان"	:	"Kategoriya:Kirgistan_paghimo_ni_bot",
	"كازاخستان"	:	"Kategoriya:Kasahistan_paghimo_ni_bot",
	"كرواتيا"	:	"Kategoriya:Krowasya_paghimo_ni_bot",
	"كمبوديا"	:	"Kategoriya:Kamboya_paghimo_ni_bot",
	"كندا"	:	"Kategoriya:Canada_paghimo_ni_bot",
	"كوبا"	:	"Kategoriya:Cuba_paghimo_ni_bot",
	"كوراساو"	:	"Kategoriya:Curaçao_paghimo_ni_bot",
	"كوريا الجنوبية"	:	"Kategoriya:Habagatang_Korea_paghimo_ni_bot",
	"كوريا الشمالية"	:	"Kategoriya:Amihanang_Korea_paghimo_ni_bot",
	"كوستاريكا"	:	"Kategoriya:Costa_Rica_paghimo_ni_bot",
	"كوسوفو"	:	"Kategoriya:Kosobo_paghimo_ni_bot",
	"كولومبيا"	:	"Kategoriya:Colombia_paghimo_ni_bot",
	"كيريباتي"	:	"Kategoriya:Kiribati_paghimo_ni_bot",
	"كينيا"	:	"Kategoriya:Kenya_paghimo_ni_bot",
	"لاتفيا"	:	"Kategoriya:Latvia_paghimo_ni_bot",
	"لاوس"	:	"Kategoriya:Laos_paghimo_ni_bot",
	"لبنان"	:	"Kategoriya:Libano_paghimo_ni_bot",
	"لوكسمبورغ"	:	"Kategoriya:Luksemburgo_paghimo_ni_bot",
	"ليبيا"	:	"Kategoriya:Libya_paghimo_ni_bot",
	"ليبيريا"	:	"Kategoriya:Liberya_paghimo_ni_bot",
	"ليتوانيا"	:	"Kategoriya:Litwanya_paghimo_ni_bot",
	"ليختنشتاين"	:	"Kategoriya:Liechtenstein_paghimo_ni_bot",
	"ليسوتو"	:	"Kategoriya:Lesotho_paghimo_ni_bot",
	"ماكاو"	:	"Kategoriya:Macao_paghimo_ni_bot",
	"مالطا"	:	"Kategoriya:Malta_paghimo_ni_bot",
	"مالي"	:	"Kategoriya:Mali_paghimo_ni_bot",
	"ماليزيا"	:	"Kategoriya:Malasya_paghimo_ni_bot",
	"مايوت"	:	"Kategoriya:Mayotte_paghimo_ni_bot",
	"مدغشقر"	:	"Kategoriya:Madagascar_paghimo_ni_bot",
	"مصر"	:	"Kategoriya:Ehipto_paghimo_ni_bot",
	"ملاوي"	:	"Kategoriya:Malawi_paghimo_ni_bot",
	"منغوليا"	:	"Kategoriya:Mongolia_paghimo_ni_bot",
	"موريتانيا"	:	"Kategoriya:Mauritania_paghimo_ni_bot",
	"موريشيوس"	:	"Kategoriya:Maurisyo_paghimo_ni_bot",
	"موزمبيق"	:	"Kategoriya:Mozambique_paghimo_ni_bot",
	"مولدافيا"	:	"Kategoriya:Moldabya_paghimo_ni_bot",
	"موناكو"	:	"Kategoriya:Monako_paghimo_ni_bot",
	"مونتسرات"	:	"Kategoriya:Montserrat_paghimo_ni_bot",
	"ميانمار"	:	"Kategoriya:Burma_paghimo_ni_bot",
	"ناميبيا"	:	"Kategoriya:Namibya_paghimo_ni_bot",
	"ناورو"	:	"Kategoriya:Nauru_paghimo_ni_bot",
	"نيبال"	:	"Kategoriya:Nepal_paghimo_ni_bot",
	"نيجيريا"	:	"Kategoriya:Nigeria_paghimo_ni_bot",
	"نيكاراغوا"	:	"Kategoriya:Nicaragua_paghimo_ni_bot",
	"نيوزيلندا"	:	"Kategoriya:New_Zealand_paghimo_ni_bot",
	"هايتي"	:	"Kategoriya:Haiti_paghimo_ni_bot",
	"هندوراس"	:	"Kategoriya:Honduras_paghimo_ni_bot",
	"هولندا"	:	"Kategoriya:Olanda_paghimo_ni_bot",
	"واليس وفوتونا"	:	"Kategoriya:Wallis_and_Futuna_paghimo_ni_bot",
}

#---
replacement3 = {}
def main():
	for item in svwiki.keys():
		if item in cebwiki:
			form = '%s\tScebwiki\t"%s"\n' % ( svwiki[item] , cebwiki[item] )
			pywikibot.output(form)
			with codecs.open( "mer/ceb-sv.csv", "a", encoding="utf-8") as logFil:
				logFil.write(form)
#---
if __name__ == "__main__":
    main()
#---