#!/usr/bin/env python3
# -*- coding:utf-8 -*-
#  python pwb.py wd/wikinews
#
#
ContriesTable={
    "Q851":{        
        "ar": "السعودية"
        ,"de": "Saudi-Arabien"
        ,"el": "Σαουδική Αραβία"
        ,"en": "Saudi Arabia"
        ,"eo": "Sauda Arabio"
        ,"es": "Arabia Saudita"
        ,"et": "Saudi Araabias"
        ,"fa": "عربستان سعودی"
        ,"fr": "Arabie saoudite"
        ,"it": "Arabia Saudita"
        ,"nb": "Saudi-Arabia"
        ,"nl": "Saoedi-Arabië"
        ,"ru": "Саудовской Аравии"#
        ,"sco": "Saudi Arabie"
        },
    "Q801":{        
        "ar": "إسرائيل"
        ,"de": "Israel"
        ,"el": "Ισραήλ"
        ,"en": "Israel"
        ,"eo": "Israelo"
        ,"es": "Israel"
        ,"et": "Iisrael"
        ,"fa": "اسرائیل"
        ,"fr": "Israël"
        ,"it": "Israele"
        ,"nb": "Israel"
        ,"nl": "Israël"
        ,"ru": "Израиль"
        ,"sco": "Israel"
        },
    "Q1410":{        
        "ar": "جبل طارق"
        ,"de": "Gibraltar"
        ,"el": "Γιβραλτάρ"
        ,"en": "Gibraltar"
        ,"eo": "Ĝibraltaro"
        ,"es": "Gibraltar"
        ,"et": "Gibraltar"
        ,"fa": "جبل طارق"
        ,"fr": "Gibraltar"
        ,"it": "Gibilterra"
        ,"nb": "Gibraltar"
        ,"nl": "Gibraltar"
        ,"ru": "Гибралтар"
        ,"sco": "Gibraltar"
        },
    "Q804":{        
        "ar": "بنما"
        ,"de": "Panama"
        ,"el": "Παναμάς"
        ,"en": "Panama"
        ,"eo": "Panamo"
        ,"es": "Panamá"
        ,"et": "Panama"
        ,"fa": "پاناما"
        ,"fr": "Panama"
        ,"it": "Panama"
        ,"nb": "Panama"
        ,"nl": "Panama"
        ,"ru": "Панаме"##
        ,"sco": "Panama"
        },
    "Q800":{        
        "ar": "كوستاريكا"
        ,"de": "Costa Rica"
        ,"el": "Κόστα Ρίκα"
        ,"en": "Costa Rica"
        ,"eo": "Kostariko"
        ,"es": "Costa Rica"
        ,"et": "Costa Rica"
        ,"fa": "کاستاریکا"
        ,"fr": "Costa Rica"
        ,"it": "Costa Rica"
        ,"nb": "Costa Rica"
        ,"nl": "Costa Rica"
        ,"ru": "Коста-Рике"###
        ,"sco": "Costa Rica"
        },
    "Q419":{        
        "ar": "بيرو"
        ,"de": "Peru"
        ,"el": "Περού"
        ,"en": "Peru"
        ,"eo": "Peruo"
        ,"es": "Perú"
        ,"et": "Peruu"
        ,"fa": "پرو"
        ,"fr": "Pérou"
        ,"it": "Perù"
        ,"nb": "Peru"
        ,"nl": "Peru"
        ,"ru": "Перу"#
        ,"sco": "Peru"
        },
    "Q668":{        
        "ar": "الهند"
        ,"de": "Indien"
        ,"el": "Ινδία"
        ,"en": "India"
        ,"eo": "Barato"
        ,"es": "India"
        ,"et": "India"
        ,"fa": "هند"
        ,"fr": "Inde"
        ,"it": "India"
        ,"nb": "India"
        ,"nl": "India"
        ,"ru": "Индия"
        ,"sco": "Indie"
        },
    "Q1019":{        
        "ar": "مدغشقر"
        ,"de": "Madagaskar"
        ,"el": "Μαδαγασκάρη"
        ,"en": "Madagascar"
        ,"eo": "Madagaskaro"
        ,"es": "Madagascar"
        ,"et": "Madagaskar"
        ,"fa": "ماداگاسکار"
        ,"fr": "Madagascar"
        ,"it": "Madagascar"
        ,"nb": "Madagaskar"
        ,"nl": "Madagaskar"
        ,"ru": "Мадагаскар"
        ,"sco": "Madagascar"
        },
    "Q664":{        
        "ar": "نيوزيلندا"
        ,"de": "Neuseeland"
        ,"el": "Νέα Ζηλανδία"
        ,"en": "New Zealand"
        ,"eo": "Nov-Zelando"
        ,"es": "Nueva Zelanda"
        ,"et": "Uus-Meremaa"
        ,"fa": "نیوزیلند"
        ,"fr": "Nouvelle-Zélande"
        ,"it": "Nuova Zelanda"
        ,"nb": "New Zealand"
        ,"nl": "Nieuw-Zeeland"
        ,"ru": "Новая Зеландия"
        ,"sco": "New Zealand"
        },
    "Q414":{        
        "ar": "الأرجنتين"
        ,"de": "Argentinien"
        ,"el": "Αργεντινή"
        ,"en": "Argentina"
        ,"eo": "Argentino"
        ,"es": "Argentina"
        ,"et": "Argentina"
        ,"fa": "آرژانتین"
        ,"fr": "Argentine"
        ,"it": "Argentina"
        ,"nb": "Argentina"
        ,"nl": "Argentinië"
        ,"ru": "Аргентине"##
        ,"sco": "Argentinae"
        },
    "Q142":{        
        "ar": "فرنسا"
        ,"de": "Frankreich"
        ,"el": "Γαλλία"
        ,"en": "France"
        ,"eo": "Francio"
        ,"es": "Francia"
        ,"et": "Prantsusmaa"
        ,"fa": "فرانسه"
        ,"fr": "France"
        ,"it": "Francia"
        ,"nb": "Frankrike"
        ,"nl": "Frankrijk"
        ,"ru": "Франция"
        ,"sco": "Fraunce"
        },
    "Q55":{        
        "ar": "هولندا"
        ,"de": "Niederlande"
        ,"el": "Ολλανδία"
        ,"en": "the Netherlands"
        ,"eo": "Nederlando"
        ,"es": "Países Bajos"
        ,"et": "Holland"
        ,"fa": "هلند"
        ,"fr": "Pays-Bas"
        ,"it": "Paesi Bassi"
        ,"nb": "Nederland"
        ,"nl": "Nederland"
        ,"ru": "Нидерландах"
        ,"sco": "Netherlands"
        },
    "Q13353":{        
        "ar": "مونتسرات"
        ,"de": "Montserrat"
        ,"el": "Μοντσερράτ"
        ,"en": "Montserrat"
        ,"eo": "Moncerato"
        ,"es": "Montserrat"
        ,"et": "Montserrat"
        ,"fa": "مونتسرات"
        ,"fr": "Montserrat"
        ,"it": "Montserrat"
        ,"nb": "Montserrat"
        ,"nl": "Montserrat"
        ,"ru": "Монтсеррат"
        ,"sco": "Montserrat"
        },
    "Q32":{        
        "ar": "لوكسمبورغ"
        ,"de": "Luxemburg"
        ,"el": "Λουξεμβούργο"
        ,"en": "Luxembourg"
        ,"eo": "Luksemburgo"
        ,"es": "Luxemburgo"
        ,"et": "Luksemburg"
        ,"fa": "لوکزامبورگ"
        ,"fr": "Luxembourg"
        ,"it": "Lussemburgo"
        ,"nb": "Luxembourg"
        ,"nl": "Luxemburg"
        ,"ru": "Люксембург"
        ,"sco": "Luxembourg"
        },
    "Q781":{        
        "ar": "أنتيغوا وباربودا"
        ,"de": "Antigua und Barbuda"
        ,"el": "Αντίγκουα και Μπαρμπούντα"
        ,"en": "Antigua and Barbuda"
        ,"eo": "Antigvo-Barbudo"
        ,"es": "Antigua y Barbuda"
        ,"et": "Antigua ja Barbuda"
        ,"fa": "آنتیگوا و باربودا"
        ,"fr": "Antigua-et-Barbuda"
        ,"it": "Antigua e Barbuda"
        ,"nb": "Antigua og Barbuda"
        ,"nl": "Antigua en Barbuda"
        ,"ru": "Антигуа и Барбуда"
        ,"sco": "Antigua an Barbuda"
        },
    "Q25279":{        
        "ar": "كوراساو"
        ,"de": "Curaçao"
        ,"el": "Κουρασάο"
        ,"en": "Curaçao"
        ,"eo": "Kuracao"
        ,"es": "Curazao"
        ,"et": "Curaçao"
        ,"fa": "کوراسائو"
        ,"fr": "Curaçao"
        ,"it": "Curaçao"
        ,"nb": "Curaçao"
        ,"nl": "Curaçao"
        ,"ru": "Кюрасао"
        ,"sco": "Curaçao"
        },
    "Q783":{        
        "ar": "هندوراس"
        ,"de": "Honduras"
        ,"el": "Ονδούρα"
        ,"en": "Honduras"
        ,"eo": "Honduro"
        ,"es": "Honduras"
        ,"et": "Honduras"
        ,"fa": "هندوراس"
        ,"fr": "Honduras"
        ,"it": "Honduras"
        ,"nb": "Honduras"
        ,"nl": "Honduras"
        ,"ru": "Гондурас"
        ,"sco": "Honduras"
        },
    "Q784":{        
        "ar": "دومينيكا"
        ,"de": "Dominica"
        ,"el": "Δομινίκα"
        ,"en": "Dominica"
        ,"eo": "Dominiko"
        ,"es": "Dominica"
        ,"et": "Dominica"
        ,"fa": "دومینیکا"
        ,"fr": "Dominique"
        ,"it": "Dominica"
        ,"nb": "Dominica"
        ,"nl": "Dominica"
        ,"ru": "Доминика"
        ,"sco": "Dominica"
        },
    "Q785":{        
        "ar": "جيرزي"
        ,"de": "Jersey"
        ,"el": "Τζέρσεϊ"
        ,"en": "Jersey"
        ,"eo": "Ĵersejo"
        ,"es": "Jersey"
        ,"et": "Jersey"
        ,"fa": "جرزی"
        ,"fr": "Jersey"
        ,"it": "Baliato di Jersey"
        ,"nb": "Jersey"
        ,"nl": "Jersey"
        ,"ru": "Джерси"
        ,"sco": "Jersey"
        },
    "Q786":{        
        "ar": "جمهورية الدومينيكان"
        ,"de": "Dominikanische Republik"
        ,"el": "Δομινικανή Δημοκρατία"
        ,"en": "the Dominican Republic"
        ,"eo": "Domingo"
        ,"es": "República Dominicana"
        ,"et": "Dominikaani Vabariik"
        ,"fa": "جمهوری دومینیکن"
        ,"fr": "République dominicaine"
        ,"it": "Repubblica Dominicana"
        ,"nb": "Den dominikanske republikk"
        ,"nl": "de Dominicaanse Republiek"
        ,"ru": "Доминиканская Республика"
        ,"sco": "Dominican Republic"
        },
    "Q37":{        
        "ar": "ليتوانيا"
        ,"de": "Litauen"
        ,"el": "Λιθουανία"
        ,"en": "Lithuania"
        ,"eo": "Litovio"
        ,"es": "Lituania"
        ,"et": "Leedu"
        ,"fa": "لیتوانی"
        ,"fr": "Lituanie"
        ,"it": "Lituania"
        ,"nb": "Litauen"
        ,"nl": "Litouwen"
        ,"ru": "Литва"
        ,"sco": "Lithuanie"
        },
    "Q1011":{        
        "ar": "الرأس الأخضر"
        ,"de": "Kap Verde"
        ,"el": "Πράσινο Ακρωτήριο"
        ,"en": "Cape Verde"
        ,"eo": "Kaboverdo"
        ,"es": "Cabo Verde"
        ,"et": "Roheneemesaared"
        ,"fa": "کیپ ورد"
        ,"fr": "Cap-Vert"
        ,"it": "Capo Verde"
        ,"nb": "Kapp Verde"
        ,"nl": "Kaapverdië"
        ,"ru": "Кабо-Верде"
        ,"sco": "Cape Verde"
        },
    "Q833":{        
        "ar": "ماليزيا"
        ,"de": "Malaysia"
        ,"el": "Μαλαισία"
        ,"en": "Malaysia"
        ,"eo": "Malajzio"
        ,"es": "Malasia"
        ,"et": "Malaisia"
        ,"fa": "مالزی"
        ,"fr": "Malaisie"
        ,"it": "Malesia"
        ,"nb": "Malaysia"
        ,"nl": "Maleisië"
        ,"ru": "Малайзия"
        ,"sco": "Malaysie"
        },
    "Q711":{        
        "ar": "منغوليا"
        ,"de": "Mongolei"
        ,"el": "Μογγολία"
        ,"en": "Mongolia"
        ,"eo": "Mongolio"
        ,"es": "Mongolia"
        ,"et": "Mongoolia"
        ,"fa": "مغولستان"
        ,"fr": "Mongolie"
        ,"it": "Mongolia"
        ,"nb": "Mongolia"
        ,"nl": "Mongolië"
        ,"ru": "Монголия"
        ,"sco": "Mongolie"
        },
    "Q710":{        
        "ar": "كيريباتي"
        ,"de": "Kiribati"
        ,"el": "Κιριμπάτι"
        ,"en": "Kiribati"
        ,"eo": "Kiribato"
        ,"es": "Kiribati"
        ,"et": "Kiribati"
        ,"fa": "کیریباتی"
        ,"fr": "Kiribati"
        ,"it": "Kiribati"
        ,"nb": "Kiribati"
        ,"nl": "Kiribati"
        ,"ru": "Кирибати"
        ,"sco": "Kiribati"
        },
    "Q717":{        
        "ar": "فنزويلا"
        ,"de": "Venezuela"
        ,"el": "Βενεζουέλα"
        ,"en": "Venezuela"
        ,"eo": "Venezuelo"
        ,"es": "Venezuela"
        ,"et": "Venezuela"
        ,"fa": "ونزوئلا"
        ,"fr": "Venezuela"
        ,"it": "Venezuela"
        ,"nb": "Venezuela"
        ,"nl": "Venezuela"
        ,"ru": "Венесуэла"
        ,"sco": "Venezuela"
        },
    "Q837":{        
        "ar": "نيبال"
        ,"de": "Nepal"
        ,"el": "Νεπάλ"
        ,"en": "Nepal"
        ,"eo": "Nepalo"
        ,"es": "Nepal"
        ,"et": "Nepal"
        ,"fa": "نپال"
        ,"fr": "Népal"
        ,"it": "Nepal"
        ,"nb": "Nepal"
        ,"nl": "Nepal"
        ,"ru": "Непал"
        ,"sco": "Nepal"
        },
    "Q34":{        
        "ar": "السويد"
        ,"de": "Schweden"
        ,"el": "Σουηδία"
        ,"en": "Sweden"
        ,"eo": "Svedio"
        ,"es": "Suecia"
        ,"et": "Rootsi"
        ,"fa": "سوئد"
        ,"fr": "Suède"
        ,"it": "Svezia"
        ,"nb": "Sverige"
        ,"nl": "Zweden"
        ,"ru": "Швеция"
        ,"sco": "Swaden"
        },
    "Q183":{        
        "ar": "ألمانيا"
        ,"de": "Deutschland"
        ,"el": "Γερμανία"
        ,"en": "Germany"
        ,"eo": "Germanio"
        ,"es": "Alemania"
        ,"et": "Saksamaa"
        ,"fa": "آلمان"
        ,"fr": "Allemagne"
        ,"it": "Germania"
        ,"nb": "Tyskland"
        ,"nl": "Duitsland"
        ,"ru": "Германия"
        ,"sco": "Germany"
        },
    "Q35555":{        
        "ar": "واليس وفوتونا"
        ,"de": "Wallis und Futuna"
        ,"el": "Ουαλίς και Φουτουνά"
        ,"en": "Wallis and Futuna"
        ,"eo": "Valiso kaj Futuno"
        ,"es": "Wallis y Futuna"
        ,"et": "Wallis ja Futuna"
        ,"fa": "والیس و فوتونا"
        ,"fr": "Wallis-et-Futuna"
        ,"it": "Wallis e Futuna"
        ,"nb": "Wallis- og Futunaøyene"
        ,"nl": "Wallis en Futuna"
        ,"ru": "Уоллис и Футуна"
        ,"sco": "Wallis an Futuna"
        },
    "Q408":{        
        "ar": "أستراليا"
        ,"de": "Australien"
        ,"el": "Αυστραλία"
        ,"en": "Australia"
        ,"eo": "Aŭstralio"
        ,"es": "Australia"
        ,"et": "Austraalia"
        ,"fa": "استرالیا"
        ,"fr": "Australie"
        ,"it": "Australia"
        ,"nb": "Australia"
        ,"nl": "Australië"
        ,"ru": "Австралия"
        ,"sco": "Australie"
        },
    "Q252":{        
        "ar": "إندونيسيا"
        ,"de": "Indonesien"
        ,"el": "Ινδονησία"
        ,"en": "Indonesia"
        ,"eo": "Indonezio"
        ,"es": "Indonesia"
        ,"et": "Indoneesia"
        ,"fa": "اندونزی"
        ,"fr": "Indonésie"
        ,"it": "Indonesia"
        ,"nb": "Indonesia"
        ,"nl": "Indonesië"
        ,"ru": "Индонезия"
        ,"sco": "Indonesie"
        },
    "Q399":{        
        "ar": "أرمينيا"
        ,"de": "Armenien"
        ,"el": "Αρμενία"
        ,"en": "Armenia"
        ,"eo": "Armenio"
        ,"es": "Armenia"
        ,"et": "Armeenia"
        ,"fa": "ارمنستان"
        ,"fr": "Arménie"
        ,"it": "Armenia"
        ,"nb": "Armenia"
        ,"nl": "Armenië"
        ,"ru": "Армения"
        ,"sco": "Armenie"
        },
    "Q398":{        
        "ar": "البحرين"
        ,"de": "Bahrain"
        ,"el": "Μπαχρέιν"
        ,"en": "Bahrain"
        ,"eo": "Barejno"
        ,"es": "Baréin"
        ,"et": "Bahrein"
        ,"fa": "بحرین"
        ,"fr": "Bahreïn"
        ,"it": "Bahrein"
        ,"nb": "Bahrain"
        ,"nl": "Bahrein"
        ,"ru": "Бахрейне"#
        ,"sco": "Bahrain"
        },
    "Q403":{        
        "ar": "صربيا"
        ,"de": "Serbien"
        ,"el": "Σερβία"
        ,"en": "Serbia"
        ,"eo": "Serbio"
        ,"es": "Serbia"
        ,"et": "Serbia"
        ,"fa": "صربستان"
        ,"fr": "Serbie"
        ,"it": "Serbia"
        ,"nb": "Serbia"
        ,"nl": "Servië"
        ,"ru": "Сербия"
        ,"sco": "Serbie"
        },
    "Q657":{        
        "ar": "تشاد"
        ,"de": "Tschad"
        ,"el": "Τσαντ"
        ,"en": "Chad"
        ,"eo": "Ĉado"
        ,"es": "Chad"
        ,"et": "Tšaad"
        ,"fa": "چاد"
        ,"fr": "Tchad"
        ,"it": "Ciad"
        ,"nb": "Tsjad"
        ,"nl": "Tsjaad"
        ,"ru": "Чад"
        ,"sco": "Chad"
        },
    "Q258":{        
        "ar": "جنوب أفريقيا"
        ,"de": "Südafrika"
        ,"el": "Νότια Αφρική"
        ,"en": "South Africa"
        ,"eo": "Sud-Afriko"
        ,"es": "Sudáfrica"
        ,"et": "Lõuna-Aafrika Vabariik"
        ,"fa": "آفریقای جنوبی"
        ,"fr": "Afrique du Sud"
        ,"it": "Sudafrica"
        ,"nb": "Sør-Afrika"
        ,"nl": "Zuid-Afrika"
        ,"ru": "Южно-Африканская Республика"
        ,"sco": "Sooth Africae"
        },
    "Q21203":{        
        "ar": "أروبا"
        ,"de": "Aruba"
        ,"el": "Αρούμπα"
        ,"en": "Aruba"
        ,"eo": "Arubo"
        ,"es": "Aruba"
        ,"et": "Aruba"
        ,"fa": "آروبا"
        ,"fr": "Aruba"
        ,"it": "Aruba"
        ,"nb": "Aruba"
        ,"nl": "Aruba"
        ,"ru": "Аруба"
        ,"sco": "Aruba"
        },
    "Q805":{        
        "ar": "اليمن"
        ,"de": "Jemen"
        ,"el": "Υεμένη"
        ,"en": "Yemen"
        ,"eo": "Jemeno"
        ,"es": "Yemen"
        ,"et": "Jeemen"
        ,"fa": "یمن"
        ,"fr": "Yémen"
        ,"it": "Yemen"
        ,"nb": "Jemen"
        ,"nl": "Jemen"
        ,"ru": "Йемене"#
        ,"sco": "Yemen"
        },
    "Q45":{        
        "ar": "البرتغال"
        ,"de": "Portugal"
        ,"el": "Πορτογαλία"
        ,"en": "Portugal"
        ,"eo": "Portugalio"
        ,"es": "Portugal"
        ,"et": "Portugal"
        ,"fa": "پرتغال"
        ,"fr": "Portugal"
        ,"it": "Portogallo"
        ,"nb": "Portugal"
        ,"nl": "Portugal"
        ,"ru": "Португалия"
        ,"sco": "Portugal"
        },
    "Q159":{        
        "ar": "روسيا"
        ,"de": "Russland"
        ,"el": "Ρωσία"
        ,"en": "Russia"
        ,"eo": "Rusio"
        ,"es": "Rusia"
        ,"et": "Venemaa"
        ,"fa": "روسیه"
        ,"fr": "Russie"
        ,"it": "Russia"
        ,"nb": "Russland"
        ,"nl": "Rusland"
        ,"ru": "Россия"
        ,"sco": "Roushie"
        },
    "Q43":{        
        "ar": "تركيا"
        ,"de": "Türkei"
        ,"el": "Τουρκία"
        ,"en": "Turkey"
        ,"eo": "Turkio"
        ,"es": "Turquía"
        ,"et": "Türgi"
        ,"fa": "ترکیه"
        ,"fr": "Turquie"
        ,"it": "Turchia"
        ,"nb": "Tyrkia"
        ,"nl": "Turkije"
        ,"ru": "Турция"
        ,"sco": "Turkey"
        },
    "Q40":{        
        "ar": "النمسا"
        ,"de": "Österreich"
        ,"el": "Αυστρία"
        ,"en": "Austria"
        ,"eo": "Aŭstrio"
        ,"es": "Austria"
        ,"et": "Austria"
        ,"fa": "اتریش"
        ,"fr": "Autriche"
        ,"it": "Austria"
        ,"nb": "Østerrike"
        ,"nl": "Oostenrijk"
        ,"ru": "Австрия"
        ,"sco": "Austrick"
        },
    "Q41":{        
        "ar": "اليونان"
        ,"de": "Griechenland"
        ,"el": "Ελλάδα"
        ,"en": "Greece"
        ,"eo": "Grekio"
        ,"es": "Grecia"
        ,"et": "Kreeka"
        ,"fa": "یونان"
        ,"fr": "Grèce"
        ,"it": "Grecia"
        ,"nb": "Hellas"
        ,"nl": "Griekenland"
        ,"ru": "Греция"
        ,"sco": "Greece"
        },
    "Q155":{        
        "ar": "البرازيل"
        ,"de": "Brasilien"
        ,"el": "Βραζιλία"
        ,"en": "Brazil"
        ,"eo": "Brazilo"
        ,"es": "Brasil"
        ,"et": "Brasiilia"
        ,"fa": "برزیل"
        ,"fr": "Brésil"
        ,"it": "Brasile"
        ,"nb": "Brasil"
        ,"nl": "Brazilië"
        ,"ru": "Бразилия"
        ,"sco": "Brazil"
        },
    "Q792":{        
        "ar": "السلفادور"
        ,"de": "El Salvador"
        ,"el": "Ελ Σαλβαδόρ"
        ,"en": "El Salvador"
        ,"eo": "Salvadoro"
        ,"es": "El Salvador"
        ,"et": "El Salvador"
        ,"fa": "السالوادور"
        ,"fr": "Salvador"
        ,"it": "El Salvador"
        ,"nb": "El Salvador"
        ,"nl": "El Salvador"
        ,"ru": "Сальвадор"
        ,"sco": "El Salvador"
        },
    "Q790":{        
        "ar": "هايتي"
        ,"de": "Haiti"
        ,"el": "Αϊτή"
        ,"en": "Haiti"
        ,"eo": "Haitio"
        ,"es": "Haití"
        ,"et": "Haiti"
        ,"fa": "هائیتی"
        ,"fr": "Haïti"
        ,"it": "Haiti"
        ,"nb": "Haiti"
        ,"nl": "Haïti"
        ,"ru": "Республика Гаити"
        ,"sco": "Haiti"
        },
    "Q796":{        
        "ar": "العراق"
        ,"de": "Irak"
        ,"el": "Ιράκ"
        ,"en": "Iraq"
        ,"eo": "Irako"
        ,"es": "Irak"
        ,"et": "Iraak"
        ,"fa": "عراق"
        ,"fr": "Irak"
        ,"it": "Iraq"
        ,"nb": "Irak"
        ,"nl": "Irak"
        ,"ru": "Ирак"
        ,"sco": "Iraq"
        },
    "Q794":{        
        "ar": "إيران"
        ,"de": "Iran"
        ,"el": "Ιράν"
        ,"en": "Iran"
        ,"eo": "Irano"
        ,"es": "Irán"
        ,"et": "Iraan"
        ,"fa": "ایران"
        ,"fr": "Iran"
        ,"it": "Iran"
        ,"nb": "Iran"
        ,"nl": "Iran"
        ,"ru": "Иран"
        ,"sco": "Iran"
        },
    "Q23635":{        
        "ar": "جزر برمودا"
        ,"de": "Bermuda"
        ,"el": "Βερμούδες"
        ,"en": "Bermuda"
        ,"eo": "Bermudo"
        ,"es": "Bermudas"
        ,"et": "Bermuda"
        ,"fa": "برمودا"
        ,"fr": "Bermudes"
        ,"it": "Bermuda"
        ,"nb": "Bermuda"
        ,"nl": "Bermuda"
        ,"ru": "Бермудские Острова"
        ,"sco": "Bermuda"
        },
    "Q954":{        
        "ar": "زيمبابوي"
        ,"de": "Simbabwe"
        ,"el": "Ζιμπάμπουε"
        ,"en": "Zimbabwe"
        ,"eo": "Zimbabvo"
        ,"es": "Zimbabue"
        ,"et": "Zimbabwe"
        ,"fa": "زیمبابوه"
        ,"fr": "Zimbabwe"
        ,"it": "Zimbabwe"
        ,"nb": "Zimbabwe"
        ,"nl": "Zimbabwe"
        ,"ru": "Зимбабве"
        ,"sco": "Zimbabwe"
        },
    "Q889":{        
        "ar": "أفغانستان"
        ,"de": "Afghanistan"
        ,"el": "Αφγανιστάν"
        ,"en": "Afghanistan"
        ,"eo": "Afganio"
        ,"es": "Afganistán"
        ,"et": "Afganistan"
        ,"fa": "افغانستان"
        ,"fr": "Afghanistan"
        ,"it": "Afghanistan"
        ,"nb": "Afghanistan"
        ,"nl": "Afghanistan"
        ,"ru": "Афганистан"
        ,"sco": "Afghanistan"
        },
    "Q884":{        
        "ar": "كوريا الجنوبية"
        ,"de": "Südkorea"
        ,"el": "Νότια Κορέα"
        ,"en": "South Korea"
        ,"eo": "Sud-Koreio"
        ,"es": "Corea del Sur"
        ,"et": "Lõuna-Korea"
        ,"fa": "کره جنوبی"
        ,"fr": "Corée du Sud"
        ,"it": "Corea del Sud"
        ,"nb": "Sør-Korea"
        ,"nl": "Zuid-Korea"
        ,"ru": "Республика Корея"
        ,"sco": "Sooth Korea"
        },
    "Q958":{        
        "ar": "جنوب السودان"
        ,"de": "Südsudan"
        ,"el": "Νότιο Σουδάν"
        ,"en": "South Sudan"
        ,"eo": "Sud-Sudano"
        ,"es": "Sudán del Sur"
        ,"et": "Lõuna-Sudaan"
        ,"fa": "سودان جنوبی"
        ,"fr": "Soudan du Sud"
        ,"it": "Sudan del Sud"
        ,"nb": "Sør-Sudan"
        ,"nl": "Zuid-Soedan"
        ,"ru": "Южный Судан"
        ,"sco": "Sooth Sudan"
        },
    "Q881":{        
        "ar": "فيتنام"
        ,"de": "Vietnam"
        ,"el": "Βιετνάμ"
        ,"en": "Vietnam"
        ,"eo": "Vjetnamio"
        ,"es": "Vietnam"
        ,"et": "Vietnam"
        ,"fa": "ویتنام"
        ,"fr": "Viêt Nam"
        ,"it": "Vietnam"
        ,"nb": "Vietnam"
        ,"nl": "Vietnam"
        ,"ru": "Вьетнам"
        ,"sco": "Vietnam"
        },
    "Q986":{        
        "ar": "إريتريا"
        ,"de": "Eritrea"
        ,"el": "Ερυθραία"
        ,"en": "Eritrea"
        ,"eo": "Eritreo"
        ,"es": "Eritrea"
        ,"et": "Eritrea"
        ,"fa": "اریتره"
        ,"fr": "Érythrée"
        ,"it": "Eritrea"
        ,"nb": "Eritrea"
        ,"nl": "Eritrea"
        ,"ru": "Эритрея"
        ,"sco": "Eritrea"
        },
    "Q14773":{        
        "ar": "ماكاو"
        ,"de": "Macau"
        ,"el": "Μακάου"
        ,"en": "Macau"
        ,"eo": "Makao"
        ,"es": "Macao"
        ,"et": "Macau"
        ,"fa": "ماکائو"
        ,"fr": "Macao"
        ,"it": "Macao"
        ,"nb": "Macao"
        ,"nl": "Macau"
        ,"ru": "Макао"
        ,"sco": "Macau"
        },
    "Q822":{        
        "ar": "لبنان"
        ,"de": "Libanon"
        ,"el": "Λίβανος"
        ,"en": "Lebanon"
        ,"eo": "Libano"
        ,"es": "Líbano"
        ,"et": "Liibanon"
        ,"fa": "لبنان"
        ,"fr": "Liban"
        ,"it": "Libano"
        ,"nb": "Libanon"
        ,"nl": "Libanon"
        ,"ru": "Ливан"
        ,"sco": "Lebanon"
        },
    "Q241":{        
        "ar": "كوبا"
        ,"de": "Kuba"
        ,"el": "Κούβα"
        ,"en": "Cuba"
        ,"eo": "Kubo"
        ,"es": "Cuba"
        ,"et": "Kuuba"
        ,"fa": "کوبا"
        ,"fr": "Cuba"
        ,"it": "Cuba"
        ,"nb": "Cuba"
        ,"nl": "Cuba"
        ,"ru": "Куба"
        ,"sco": "Cuba"
        },
    "Q242":{        
        "ar": "بليز"
        ,"de": "Belize"
        ,"el": "Μπελίζε"
        ,"en": "Belize"
        ,"eo": "Belizo"
        ,"es": "Belice"
        ,"et": "Belize"
        ,"fa": "بلیز"
        ,"fr": "Belize"
        ,"it": "Belize"
        ,"nb": "Belize"
        ,"nl": "Belize"
        ,"ru": "Белиз"
        ,"sco": "Belize"
        },
    "Q244":{        
        "ar": "باربادوس"
        ,"de": "Barbados"
        ,"el": "Μπαρμπάντος"
        ,"en": "Barbados"
        ,"eo": "Barbado"
        ,"es": "Barbados"
        ,"et": "Barbados"
        ,"fa": "باربادوس"
        ,"fr": "Barbade"
        ,"it": "Barbados"
        ,"nb": "Barbados"
        ,"nl": "Barbados"
        ,"ru": "Барбадос"
        ,"sco": "Barbados"
        },
    "Q424":{        
        "ar": "كمبوديا"
        ,"de": "Kambodscha"
        ,"el": "Καμπότζη"
        ,"en": "Cambodia"
        ,"eo": "Kamboĝo"
        ,"es": "Camboya"
        ,"et": "Kambodža"
        ,"fa": "کامبوج"
        ,"fr": "Cambodge"
        ,"it": "Cambogia"
        ,"nb": "Kambodsja"
        ,"nl": "Cambodja"
        ,"ru": "Камбоджа"
        ,"sco": "Cambodie"
        },
    "Q33":{        
        "ar": "فنلندا"
        ,"de": "Finnland"
        ,"el": "Φινλανδία"
        ,"en": "Finland"
        ,"eo": "Finnlando"
        ,"es": "Finlandia"
        ,"et": "Soome"
        ,"fa": "فنلاند"
        ,"fr": "Finlande"
        ,"it": "Finlandia"
        ,"nb": "Finland"
        ,"nl": "Finland"
        ,"ru": "Финляндия"
        ,"sco": "Finland"
        },
    "Q921":{        
        "ar": "بروناي"
        ,"de": "Brunei"
        ,"el": "Μπρουνέι"
        ,"en": "Brunei"
        ,"eo": "Brunejo"
        ,"es": "Brunéi"
        ,"et": "Brunei"
        ,"fa": "برونئی"
        ,"fr": "Brunei"
        ,"it": "Brunei"
        ,"nb": "Brunei"
        ,"nl": "Brunei"
        ,"ru": "Бруней"
        ,"sco": "Brunei"
        },
    "Q31":{        
        "ar": "بلجيكا"
        ,"de": "Belgien"
        ,"el": "Βέλγιο"
        ,"en": "Belgium"
        ,"eo": "Belgio"
        ,"es": "Bélgica"
        ,"et": "Belgia"
        ,"fa": "بلژیک"
        ,"fr": "Belgique"
        ,"it": "Belgio"
        ,"nb": "Belgia"
        ,"nl": "België"
        ,"ru": "Бельгия"
        ,"sco": "Belgium"
        },
    "Q30":{        
        "ar": "الولايات المتحدة الأمريكية"
        ,"de": "Vereinigte Staaten"
        ,"el": "Ηνωμένες Πολιτείες Αμερικής"
        ,"en": "the United States of America"
        ,"eo": "Usono"
        ,"es": "Estados Unidos"
        ,"et": "Ameerika Ühendriigid"
        ,"fa": "ایالات متحده آمریکا"
        ,"fr": "États-Unis"
        ,"it": "Stati Uniti d'America"
        ,"nb": "USA"
        ,"nl": "de Verenigde Staten van Amerika"#
        ,"ru": "Соединённые Штаты Америки"
        ,"sco": "Unitit States"
        },
    "Q924":{        
        "ar": "تنزانيا"
        ,"de": "Tansania"
        ,"el": "Τανζανία"
        ,"en": "Tanzania"
        ,"eo": "Tanzanio"
        ,"es": "Tanzania"
        ,"et": "Tansaania"
        ,"fa": "تانزانیا"
        ,"fr": "Tanzanie"
        ,"it": "Tanzania"
        ,"nb": "Tanzania"
        ,"nl": "Tanzania"
        ,"ru": "Танзания"
        ,"sco": "Tanzanie"
        },
    "Q36":{        
        "ar": "بولندا"
        ,"de": "Polen"
        ,"el": "Πολωνία"
        ,"en": "Poland"
        ,"eo": "Pollando"
        ,"es": "Polonia"
        ,"et": "Poola"
        ,"fa": "لهستان"
        ,"fr": "Pologne"
        ,"it": "Polonia"
        ,"nb": "Polen"
        ,"nl": "Polen"
        ,"ru": "Польша"
        ,"sco": "Poland"
        },
    "Q35":{        
        "ar": "الدنمارك"
        ,"de": "Dänemark"
        ,"el": "Δανία"
        ,"en": "Denmark"
        ,"eo": "Danio"
        ,"es": "Dinamarca"
        ,"et": "Taani"
        ,"fa": "دانمارک"
        ,"fr": "Danemark"
        ,"it": "Danimarca"
        ,"nb": "Danmark"
        ,"nl": "Denemarken"
        ,"ru": "Дания"
        ,"sco": "Denmark"
        },
    "Q730":{        
        "ar": "سورينام"
        ,"de": "Suriname"
        ,"el": "Σουρινάμ"
        ,"en": "Suriname"
        ,"eo": "Surinamo"
        ,"es": "Surinam"
        ,"et": "Suriname"
        ,"fa": "سورینام"
        ,"fr": "Suriname"
        ,"it": "Suriname"
        ,"nb": "Surinam"
        ,"nl": "Suriname"
        ,"ru": "Суринам"
        ,"sco": "Suriname"
        },
    "Q928":{        
        "ar": "الفلبين"
        ,"de": "Philippinen"
        ,"el": "Φιλιππίνες"
        ,"en": "Philippines"
        ,"eo": "Filipinoj"
        ,"es": "Filipinas"
        ,"et": "Filipiinid"
        ,"fa": "فیلیپین"
        ,"fr": "Philippines"
        ,"it": "Filippine"
        ,"nb": "Filippinene"
        ,"nl": "de Filipijnen"#
        ,"ru": "Филиппины"
        ,"sco": "Philippines"
        },
    "Q929":{        
        "ar": "جمهورية أفريقيا الوسطى"
        ,"de": "Zentralafrikanische Republik"
        ,"el": "Κεντροαφρικανική Δημοκρατία"
        ,"en": "Central African Republic"
        ,"eo": "Centr-Afrika Respubliko"
        ,"es": "República Centroafricana"
        ,"et": "Kesk-Aafrika Vabariik"
        ,"fa": "جمهوری آفریقای مرکزی"
        ,"fr": "République centrafricaine"
        ,"it": "Repubblica Centrafricana"
        ,"nb": "Den sentralafrikanske republikk"
        ,"nl": "de Centraal-Afrikaanse Republiek"#
        ,"ru": "Центральноафриканская Республика"
        ,"sco": "Central African Republic"
        },
    "Q39":{        
        "ar": "سويسرا"
        ,"de": "Schweiz"
        ,"el": "Ελβετία"
        ,"en": "Switzerland"
        ,"eo": "Svislando"
        ,"es": "Suiza"
        ,"et": "Šveits"
        ,"fa": "سوئیس"
        ,"fr": "Suisse"
        ,"it": "Svizzera"
        ,"nb": "Sveits"
        ,"nl": "Zwitserland"
        ,"ru": "Швейцария"
        ,"sco": "Swisserland"
        },
    "Q38":{        
        "ar": "إيطاليا"
        ,"de": "Italien"
        ,"el": "Ιταλία"
        ,"en": "Italy"
        ,"eo": "Italio"
        ,"es": "Italia"
        ,"et": "Itaalia"
        ,"fa": "ایتالیا"
        ,"fr": "Italie"
        ,"it": "Italia"
        ,"nb": "Italia"
        ,"nl": "Italië"
        ,"ru": "Италия"
        ,"sco": "Italy"
        },
    "Q858":{        
        "ar": "سوريا"
        ,"de": "Syrien"
        ,"el": "Συρία"
        ,"en": "Syria"
        ,"eo": "Sirio"
        ,"es": "Siria"
        ,"et": "Süüria"
        ,"fa": "سوریه"
        ,"fr": "Syrie"
        ,"it": "Siria"
        ,"nb": "Syria"
        ,"nl": "Syrië"
        ,"ru": "Сирия"
        ,"sco": "Sirie"
        },
    "Q423":{        
        "ar": "كوريا الشمالية"
        ,"de": "Nordkorea"
        ,"el": "Βόρεια Κορέα"
        ,"en": "North Korea"
        ,"eo": "Nord-Koreio"
        ,"es": "Corea del Norte"
        ,"et": "Põhja-Korea"
        ,"fa": "کره شمالی"
        ,"fr": "Corée du Nord"
        ,"it": "Corea del Nord"
        ,"nb": "Nord-Korea"
        ,"nl": "Noord-Korea"
        ,"ru": "Корейская Народно-Демократическая Республика"
        ,"sco": "North Korea"
        },
    "Q983":{        
        "ar": "غينيا الاستوائية"
        ,"de": "Äquatorialguinea"
        ,"el": "Ισημερινή Γουινέα"
        ,"en": "Equatorial Guinea"
        ,"eo": "Ekvatora Gvineo"
        ,"es": "Guinea Ecuatorial"
        ,"et": "Ekvatoriaal-Guinea"
        ,"fa": "گینه استوایی"
        ,"fr": "Guinée équatoriale"
        ,"it": "Guinea Equatoriale"
        ,"nb": "Ekvatorial-Guinea"
        ,"nl": "Equatoriaal-Guinea"
        ,"ru": "Экваториальная Гвинея"
        ,"sco": "Equatorial Guinea"
        },
    "Q733":{        
        "ar": "باراغواي"
        ,"de": "Paraguay"
        ,"el": "Παραγουάη"
        ,"en": "Paraguay"
        ,"eo": "Paragvajo"
        ,"es": "Paraguay"
        ,"et": "Paraguay"
        ,"fa": "پاراگوئه"
        ,"fr": "Paraguay"
        ,"it": "Paraguay"
        ,"nb": "Paraguay"
        ,"nl": "Paraguay"
        ,"ru": "Парагвай"
        ,"sco": "Paraguay"
        },
    "Q854":{        
        "ar": "سريلانكا"
        ,"de": "Sri Lanka"
        ,"el": "Σρι Λάνκα"
        ,"en": "Sri Lanka"
        ,"eo": "Srilanko"
        ,"es": "Sri Lanka"
        ,"et": "Sri Lanka"
        ,"fa": "سری‌لانکا"
        ,"fr": "Sri Lanka"
        ,"it": "Sri Lanka"
        ,"nb": "Sri Lanka"
        ,"nl": "Sri Lanka"
        ,"ru": "Шри-Ланка"
        ,"sco": "Sri Lanka"
        },
    "Q734":{        
        "ar": "غيانا"
        ,"de": "Guyana"
        ,"el": "Γουιάνα"
        ,"en": "Guyana"
        ,"eo": "Gujano"
        ,"es": "Guyana"
        ,"et": "Guyana"
        ,"fa": "گایان"
        ,"fr": "Guyana"
        ,"it": "Guyana"
        ,"nb": "Guyana"
        ,"nl": "Guyana"
        ,"ru": "Гайана"
        ,"sco": "Guyana"
        },
    "Q736":{        
        "ar": "الإكوادور"
        ,"de": "Ecuador"
        ,"el": "Ισημερινός"
        ,"en": "Ecuador"
        ,"eo": "Ekvadoro"
        ,"es": "Ecuador"
        ,"et": "Ecuador"
        ,"fa": "اکوادور"
        ,"fr": "Équateur"
        ,"it": "Ecuador"
        ,"nb": "Ecuador"
        ,"nl": "Ecuador"
        ,"ru": "Эквадор"
        ,"sco": "Ecuador"
        },
    "Q1013":{        
        "ar": "ليسوتو"
        ,"de": "Lesotho"
        ,"el": "Λεσότο"
        ,"en": "Lesotho"
        ,"eo": "Lesoto"
        ,"es": "Lesoto"
        ,"et": "Lesotho"
        ,"fa": "لسوتو"
        ,"fr": "Lesotho"
        ,"it": "Lesotho"
        ,"nb": "Lesotho"
        ,"nl": "Lesotho"
        ,"ru": "Лесото"
        ,"sco": "Lesotho"
        },
    "Q235":{        
        "ar": "موناكو"
        ,"de": "Monaco"
        ,"el": "Μονακό"
        ,"en": "Monaco"
        ,"eo": "Monako"
        ,"es": "Mónaco"
        ,"et": "Monaco"
        ,"fa": "موناکو"
        ,"fr": "Monaco"
        ,"it": "Principato di Monaco"
        ,"nb": "Monaco"
        ,"nl": "Monaco"
        ,"ru": "Монако"
        ,"sco": "Monaco"
        },
    "Q236":{        
        "ar": "الجبل الأسود"
        ,"de": "Montenegro"
        ,"el": "Μαυροβούνιο"
        ,"en": "Montenegro"
        ,"eo": "Montenegro"
        ,"es": "Montenegro"
        ,"et": "Montenegro"
        ,"fa": "مونته‌نگرو"
        ,"fr": "Monténégro"
        ,"it": "Montenegro"
        ,"nb": "Montenegro"
        ,"nl": "Montenegro"
        ,"ru": "Черногория"
        ,"sco": "Montenegro"
        },
    "Q230":{        
        "ar": "جورجيا"
        ,"de": "Georgien"
        ,"el": "Γεωργία"
        ,"en": "Georgia"
        ,"eo": "Kartvelio"
        ,"es": "Georgia"
        ,"et": "Gruusia"
        ,"fa": "گرجستان"
        ,"fr": "Géorgie"
        ,"it": "Georgia"
        ,"nb": "Georgia"
        ,"nl": "Georgië"
        ,"ru": "Грузия"
        ,"sco": "Georgie"
        },
    "Q232":{        
        "ar": "كازاخستان"
        ,"de": "Kasachstan"
        ,"el": "Καζακστάν"
        ,"en": "Kazakhstan"
        ,"eo": "Kazaĥio"
        ,"es": "Kazajistán"
        ,"et": "Kasahstan"
        ,"fa": "قزاقستان"
        ,"fr": "Kazakhstan"
        ,"it": "Kazakistan"
        ,"nb": "Kasakhstan"
        ,"nl": "Kazachstan"
        ,"ru": "Казахстан"
        ,"sco": "Kazakhstan"
        },
    "Q233":{        
        "ar": "مالطا"
        ,"de": "Malta"
        ,"el": "Μάλτα"
        ,"en": "Malta"
        ,"eo": "Malto"
        ,"es": "Malta"
        ,"et": "Malta"
        ,"fa": "مالت"
        ,"fr": "Malte"
        ,"it": "Malta"
        ,"nb": "Malta"
        ,"nl": "Malta"
        ,"ru": "Мальта"
        ,"sco": "Maltae"
        },
    "Q334":{        
        "ar": "سنغافورة"
        ,"de": "Singapur"
        ,"el": "Σιγκαπούρη"
        ,"en": "Singapore"
        ,"eo": "Singapuro"
        ,"es": "Singapur"
        ,"et": "Singapur"
        ,"fa": "سنگاپور"
        ,"fr": "Singapour"
        ,"it": "Singapore"
        ,"nb": "Singapore"
        ,"nl": "Singapore"
        ,"ru": "Сингапур"
        ,"sco": "Singapore"
        },
    "Q145":{        
        "ar": "المملكة المتحدة"
        ,"de": "Vereinigtes Königreich"
        ,"el": "Ηνωμένο Βασίλειο"
        ,"en": "the United Kingdom"
        ,"eo": "Unuiĝinta Reĝlando"
        ,"es": "Reino Unido"
        ,"et": "Suurbritannia"
        ,"fa": "بریتانیا"
        ,"fr": "Royaume-Uni"
        ,"it": "Regno Unito"
        ,"nb": "Storbritannia"
        ,"nl": "het Verenigd Koninkrijk"
        ,"ru": "Великобритания"
        ,"sco": "Unitit Kinrick"
        },
    "Q20":{        
        "ar": "النرويج"
        ,"de": "Norwegen"
        ,"el": "Νορβηγία"
        ,"en": "Norway"
        ,"eo": "Norvegio"
        ,"es": "Noruega"
        ,"et": "Norra"
        ,"fa": "نروژ"
        ,"fr": "Norvège"
        ,"it": "Norvegia"
        ,"nb": "Norge"
        ,"nl": "Noorwegen"
        ,"ru": "Норвегия"
        ,"sco": "Norawa"
        },
    "Q1045":{        
        "ar": "الصومال"
        ,"de": "Somalia"
        ,"el": "Σομαλία"
        ,"en": "Somalia"
        ,"eo": "Somalio"
        ,"es": "Somalia"
        ,"et": "Somaalia"
        ,"fa": "سومالی"
        ,"fr": "Somalie"
        ,"it": "Somalia"
        ,"nb": "Somalia"
        ,"nl": "Somalië"
        ,"ru": "Сомали"
        ,"sco": "Somalie"
        },
    "Q1044":{        
        "ar": "سيراليون"
        ,"de": "Sierra Leone"
        ,"el": "Σιέρα Λεόνε"
        ,"en": "Sierra Leone"
        ,"eo": "Siera-Leono"
        ,"es": "Sierra Leona"
        ,"et": "Sierra Leone"
        ,"fa": "سیرالئون"
        ,"fr": "Sierra Leone"
        ,"it": "Sierra Leone"
        ,"nb": "Sierra Leone"
        ,"nl": "Sierra Leone"
        ,"ru": "Сьерра-Леоне"
        ,"sco": "Sierra Leone"
        },
    "Q1042":{        
        "ar": "سيشل"
        ,"de": "Seychellen"
        ,"el": "Σεϋχέλλες"
        ,"en": "Seychelles"
        ,"eo": "Sejŝeloj"
        ,"es": "Seychelles"
        ,"et": "Seišellid"
        ,"fa": "سیشل"
        ,"fr": "Seychelles"
        ,"it": "Seychelles"
        ,"nb": "Seychellene"
        ,"nl": "Seychellen"
        ,"ru": "Сейшелы"
        ,"sco": "Seychelles"
        },
    "Q1041":{        
        "ar": "السنغال"
        ,"de": "Senegal"
        ,"el": "Σενεγάλη"
        ,"en": "Senegal"
        ,"eo": "Senegalo"
        ,"es": "Senegal"
        ,"et": "Senegal"
        ,"fa": "سنگال"
        ,"fr": "Sénégal"
        ,"it": "Senegal"
        ,"nb": "Senegal"
        ,"nl": "Senegal"
        ,"ru": "Сенегал"
        ,"sco": "Senegal"
        },
    "Q262":{        
        "ar": "الجزائر"
        ,"de": "Algerien"
        ,"el": "Αλγερία"
        ,"en": "Algeria"
        ,"eo": "Alĝerio"
        ,"es": "Argelia"
        ,"et": "Alžeeria"
        ,"fa": "الجزایر"
        ,"fr": "Algérie"
        ,"it": "Algeria"
        ,"nb": "Algerie"
        ,"nl": "Algerije"
        ,"ru": "Алжир"
        ,"sco": "Algerie"
        },
    "Q28":{        
        "ar": "المجر"
        ,"de": "Ungarn"
        ,"el": "Ουγγαρία"
        ,"en": "Hungary"
        ,"eo": "Hungario"
        ,"es": "Hungría"
        ,"et": "Ungari"
        ,"fa": "مجارستان"
        ,"fr": "Hongrie"
        ,"it": "Ungheria"
        ,"nb": "Ungarn"
        ,"nl": "Hongarije"
        ,"ru": "Венгрия"
        ,"sco": "Hungary"
        },
    "Q29":{        
        "ar": "إسبانيا"
        ,"de": "Spanien"
        ,"el": "Ισπανία"
        ,"en": "Spain"
        ,"eo": "Hispanio"
        ,"es": "España"
        ,"et": "Hispaania"
        ,"fa": "اسپانیا"
        ,"fr": "Espagne"
        ,"it": "Spagna"
        ,"nb": "Spania"
        ,"nl": "Spanje"
        ,"ru": "Испания"
        ,"sco": "Spain"
        },
    "Q819":{        
        "ar": "لاوس"
        ,"de": "Laos"
        ,"el": "Λάος"
        ,"en": "Laos"
        ,"eo": "Laoso"
        ,"es": "Laos"
        ,"et": "Laos"
        ,"fa": "لائوس"
        ,"fr": "Laos"
        ,"it": "Laos"
        ,"nb": "Laos"
        ,"nl": "Laos"
        ,"ru": "Лаос"
        ,"sco": "Laos"
        },
    "Q148":{        
        "ar": "الصين"
        ,"de": "Volksrepublik China"
        ,"el": "Λαϊκή Δημοκρατία της Κίνας"
        ,"en": "People's Republic of China"
        ,"eo": "Ĉina Popola Respubliko"
        ,"es": "República Popular China"
        ,"et": "Hiina"
        ,"fa": "جمهوری خلق چین"
        ,"fr": "République populaire de Chine"
        ,"it": "Cina"
        ,"nb": "Folkerepublikken Kina"
        ,"nl": "de Volksrepubliek China"
        ,"ru": "Китайская Народная Республика"
        ,"sco": "Fowkrepublic o Cheenae"
        },
    "Q1049":{        
        "ar": "السودان"
        ,"de": "Sudan"
        ,"el": "Σουδάν"
        ,"en": "Sudan"
        ,"eo": "Sudano"
        ,"es": "Sudán"
        ,"et": "Sudaan"
        ,"fa": "سودان"
        ,"fr": "Soudan"
        ,"it": "Sudan"
        ,"nb": "Sudan"
        ,"nl": "Soedan"
        ,"ru": "Судан"
        ,"sco": "Sudan"
        },
    "Q1025":{        
        "ar": "موريتانيا"
        ,"de": "Mauretanien"
        ,"el": "Μαυριτανία"
        ,"en": "Mauritania"
        ,"eo": "Maŭritanio"
        ,"es": "Mauritania"
        ,"et": "Mauritaania"
        ,"fa": "موریتانی"
        ,"fr": "Mauritanie"
        ,"it": "Mauritania"
        ,"nb": "Mauritania"
        ,"nl": "Mauritanië"
        ,"ru": "Мавритания"
        ,"sco": "Mauritanie"
        },
    "Q1027":{        
        "ar": "موريشيوس"
        ,"de": "Mauritius"
        ,"el": "Μαυρίκιος"
        ,"en": "Mauritius"
        ,"eo": "Maŭricio"
        ,"es": "Mauricio"
        ,"et": "Mauritius"
        ,"fa": "موریس"
        ,"fr": "Maurice"
        ,"it": "Mauritius"
        ,"nb": "Mauritius"
        ,"nl": "Mauritius"
        ,"ru": "Маврикий"
        ,"sco": "Mauritius"
        },
    "Q1020":{        
        "ar": "مالاوي"
        ,"de": "Malawi"
        ,"el": "Μαλάουι"
        ,"en": "Malawi"
        ,"eo": "Malavio"
        ,"es": "Malaui"
        ,"et": "Malawi"
        ,"fa": "مالاوی"
        ,"fr": "Malawi"
        ,"it": "Malawi"
        ,"nb": "Malawi"
        ,"nl": "Malawi"
        ,"ru": "Малави"
        ,"sco": "Malawi"
        },
    "Q189":{        
        "ar": "آيسلندا"
        ,"de": "Island"
        ,"el": "Ισλανδία"
        ,"en": "Iceland"
        ,"eo": "Islando"
        ,"es": "Islandia"
        ,"et": "Island"
        ,"fa": "ایسلند"
        ,"fr": "Islande"
        ,"it": "Islanda"
        ,"nb": "Island"
        ,"nl": "IJsland"
        ,"ru": "Исландия"
        ,"sco": "Iceland"
        },
    "Q843":{        
        "ar": "باكستان"
        ,"de": "Pakistan"
        ,"el": "Πακιστάν"
        ,"en": "Pakistan"
        ,"eo": "Pakistano"
        ,"es": "Pakistán"
        ,"et": "Pakistan"
        ,"fa": "پاکستان"
        ,"fr": "Pakistan"
        ,"it": "Pakistan"
        ,"nb": "Pakistan"
        ,"nl": "Pakistan"
        ,"ru": "Пакистан"
        ,"sco": "Pakistan"
        },
    "Q842":{        
        "ar": "سلطنة عمان"
        ,"de": "Oman"
        ,"el": "Ομάν"
        ,"en": "Oman"
        ,"eo": "Omano"
        ,"es": "Omán"
        ,"et": "Omaan"
        ,"fa": "عمان"
        ,"fr": "Oman"
        ,"it": "Oman"
        ,"nb": "Oman"
        ,"nl": "Oman"
        ,"ru": "Оман"
        ,"sco": "Oman"
        },
    "Q184":{        
        "ar": "روسيا البيضاء"
        ,"de": "Weißrussland"
        ,"el": "Λευκορωσία"
        ,"en": "Belarus"
        ,"eo": "Belorusio"
        ,"es": "Bielorrusia"
        ,"et": "Valgevene"
        ,"fa": "بلاروس"
        ,"fr": "Biélorussie"
        ,"it": "Bielorussia"
        ,"nb": "Hviterussland"
        ,"nl": "Wit-Rusland"
        ,"ru": "Белоруссия"
        ,"sco": "Belaroushie"
        },
    "Q1029":{        
        "ar": "موزمبيق"
        ,"de": "Mosambik"
        ,"el": "Μοζαμβίκη"
        ,"en": "Mozambique"
        ,"eo": "Mozambiko"
        ,"es": "Mozambique"
        ,"et": "Mosambiik"
        ,"fa": "موزامبیک"
        ,"fr": "Mozambique"
        ,"it": "Mozambico"
        ,"nb": "Mosambik"
        ,"nl": "Mozambique"
        ,"ru": "Мозамбик"
        ,"sco": "Mozambique"
        },
    "Q846":{        
        "ar": "قطر"
        ,"de": "Katar"
        ,"el": "Κατάρ"
        ,"en": "Qatar"
        ,"eo": "Kataro"
        ,"es": "Catar"
        ,"et": "Katar"
        ,"fa": "قطر"
        ,"fr": "Qatar"
        ,"it": "Qatar"
        ,"nb": "Qatar"
        ,"nl": "Qatar"
        ,"ru": "Катар"
        ,"sco": "Qatar"
        },
    "Q265":{        
        "ar": "أوزبكستان"
        ,"de": "Usbekistan"
        ,"el": "Ουζμπεκιστάν"
        ,"en": "Uzbekistan"
        ,"eo": "Uzbekio"
        ,"es": "Uzbekistán"
        ,"et": "Usbekistan"
        ,"fa": "ازبکستان"
        ,"fr": "Ouzbékistan"
        ,"it": "Uzbekistan"
        ,"nb": "Usbekistan"
        ,"nl": "Oezbekistan"
        ,"ru": "Узбекистан"
        ,"sco": "Uzbekistan"
        },
    "Q228":{        
        "ar": "أندورا"
        ,"de": "Andorra"
        ,"el": "Ανδόρρα"
        ,"en": "Andorra"
        ,"eo": "Andoro"
        ,"es": "Andorra"
        ,"et": "Andorra"
        ,"fa": "آندورا"
        ,"fr": "Andorre"
        ,"it": "Andorra"
        ,"nb": "Andorra"
        ,"nl": "Andorra"
        ,"ru": "Андорра"
        ,"sco": "Andorrae"
        },
    "Q227":{        
        "ar": "أذربيجان"
        ,"de": "Aserbaidschan"
        ,"el": "Αζερμπαϊτζάν"
        ,"en": "Azerbaijan"
        ,"eo": "Azerbajĝano"
        ,"es": "Azerbaiyán"
        ,"et": "Aserbaidžaan"
        ,"fa": "جمهوری آذربایجان"
        ,"fr": "Azerbaïdjan"
        ,"it": "Azerbaigian"
        ,"nb": "Aserbajdsjan"
        ,"nl": "Azerbeidzjan"
        ,"ru": "Азербайджан"
        ,"sco": "Azerbaijan"
        },
    "Q225":{        
        "ar": "البوسنة والهرسك"
        ,"de": "Bosnien und Herzegowina"
        ,"el": "Βοσνία και Ερζεγοβίνη"
        ,"en": "Bosnia and Herzegovina"
        ,"eo": "Bosnio kaj Hercegovino"
        ,"es": "Bosnia y Herzegovina"
        ,"et": "Bosnia ja Hertsegoviina"
        ,"fa": "بوسنی و هرزگوین"
        ,"fr": "Bosnie-Herzégovine"
        ,"it": "Bosnia ed Erzegovina"
        ,"nb": "Bosnia-Hercegovina"
        ,"nl": "Bosnië en Herzegovina"
        ,"ru": "Босния и Герцеговина"
        ,"sco": "Bosnie an Herzegovinae"
        },
    "Q224":{        
        "ar": "كرواتيا"
        ,"de": "Kroatien"
        ,"el": "Κροατία"
        ,"en": "Croatia"
        ,"eo": "Kroatio"
        ,"es": "Croacia"
        ,"et": "Horvaatia"
        ,"fa": "کرواسی"
        ,"fr": "Croatie"
        ,"it": "Croazia"
        ,"nb": "Kroatia"
        ,"nl": "Kroatië"
        ,"ru": "Хорватия"
        ,"sco": "Croatie"
        },
    "Q223":{        
        "ar": "غرينلاند"
        ,"de": "Grönland"
        ,"el": "Γροιλανδία"
        ,"en": "Greenland"
        ,"eo": "Gronlando"
        ,"es": "Groenlandia"
        ,"et": "Gröönimaa"
        ,"fa": "گرینلند"
        ,"fr": "Groenland"
        ,"it": "Groenlandia"
        ,"nb": "Grønland"
        ,"nl": "Groenland"
        ,"ru": "Гренландия"
        ,"sco": "Greenland"
        },
    "Q222":{        
        "ar": "ألبانيا"
        ,"de": "Albanien"
        ,"el": "Αλβανία"
        ,"en": "Albania"
        ,"eo": "Albanio"
        ,"es": "Albania"
        ,"et": "Albaania"
        ,"fa": "آلبانی"
        ,"fr": "Albanie"
        ,"it": "Albania"
        ,"nb": "Albania"
        ,"nl": "Albanië"
        ,"ru": "Албания"
        ,"sco": "Albanie"
        },
    "Q221":{        
        "ar": "جمهورية مقدونيا"
        ,"de": "Mazedonien"
        ,"el": "πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας"
        ,"en": "Republic of Macedonia"
        ,"eo": "Respubliko Makedonio"
        ,"es": "República de Macedonia"
        ,"et": "Makedoonia"
        ,"fa": "جمهوری مقدونیه"
        ,"fr": "République de Macédoine"
        ,"it": "Repubblica di Macedonia"
        ,"nb": "Republikken Makedonia"
        ,"nl": "Macedonië"
        ,"ru": "Республика Македония"
        ,"sco": "Republic o Macedonie"
        },
    "Q96":{        
        "ar": "المكسيك"
        ,"de": "Mexiko"
        ,"el": "Μεξικό"
        ,"en": "Mexico"
        ,"eo": "Meksiko"
        ,"es": "México"
        ,"et": "Mehhiko"
        ,"fa": "مکزیک"
        ,"fr": "Mexique"
        ,"it": "Messico"
        ,"nb": "Mexico"
        ,"nl": "Mexico"
        ,"ru": "Мексика"
        ,"sco": "Mexico"
        },
    "Q229":{        
        "ar": "قبرص"
        ,"de": "Republik Zypern"
        ,"el": "Κύπρος"
        ,"en": "Cyprus"
        ,"eo": "Kipro"
        ,"es": "Chipre"
        ,"et": "Küpros"
        ,"fa": "قبرس"
        ,"fr": "Chypre"
        ,"it": "Cipro"
        ,"nb": "Kypros"
        ,"nl": "Cyprus"
        ,"ru": "Кипр"
        ,"sco": "Cyprus"
        },
    "Q347":{        
        "ar": "ليختنشتاين"
        ,"de": "Liechtenstein"
        ,"el": "Λίχτενσταϊν"
        ,"en": "Liechtenstein"
        ,"eo": "Liĥtenŝtejno"
        ,"es": "Liechtenstein"
        ,"et": "Liechtenstein"
        ,"fa": "لیختن‌اشتاین"
        ,"fr": "Liechtenstein"
        ,"it": "Liechtenstein"
        ,"nb": "Liechtenstein"
        ,"nl": "Liechtenstein"
        ,"ru": "Лихтенштейн"
        ,"sco": "Liechtenstein"
        },
    "Q1050":{        
        "ar": "سوازيلاند"
        ,"de": "Swasiland"
        ,"el": "Σουαζιλάνδη"
        ,"en": "Swaziland"
        ,"eo": "Svazilando"
        ,"es": "Suazilandia"
        ,"et": "Svaasimaa"
        ,"fa": "سوازیلند"
        ,"fr": "Swaziland"
        ,"it": "Swaziland"
        ,"nb": "Swaziland"
        ,"nl": "Swaziland"
        ,"ru": "Свазиленд"
        ,"sco": "Swaziland"
        },
    "Q17":{        
        "ar": "اليابان"
        ,"de": "Japan"
        ,"el": "Ιαπωνία"
        ,"en": "Japan"
        ,"eo": "Japanio"
        ,"es": "Japón"
        ,"et": "Jaapan"
        ,"fa": "ژاپن"
        ,"fr": "Japon"
        ,"it": "Giappone"
        ,"nb": "Japan"
        ,"nl": "Japan"
        ,"ru": "Япония"
        ,"sco": "Japan"
        },
    "Q16":{        
        "ar": "كندا"
        ,"de": "Kanada"
        ,"el": "Καναδάς"
        ,"en": "Canada"
        ,"eo": "Kanado"
        ,"es": "Canadá"
        ,"et": "Kanada"
        ,"fa": "کانادا"
        ,"fr": "Canada"
        ,"it": "Canada"
        ,"nb": "Canada"
        ,"nl": "Canada"
        ,"ru": "Канада"
        ,"sco": "Canadae"
        },
    "Q1028":{        
        "ar": "المغرب"
        ,"de": "Marokko"
        ,"el": "Μαρόκο"
        ,"en": "Morocco"
        ,"eo": "Maroko"
        ,"es": "Marruecos"
        ,"et": "Maroko"
        ,"fa": "مراکش"
        ,"fr": "Maroc"
        ,"it": "Marocco"
        ,"nb": "Marokko"
        ,"nl": "Marokko"
        ,"ru": "Марокко"
        ,"sco": "Morocco"
        },
    "Q902":{        
        "ar": "بنغلاديش"
        ,"de": "Bangladesch"
        ,"el": "Μπανγκλαντές"
        ,"en": "Bangladesh"
        ,"eo": "Bangladeŝo"
        ,"es": "Bangladés"
        ,"et": "Bangladesh"
        ,"fa": "بنگلادش"
        ,"fr": "Bangladesh"
        ,"it": "Bangladesh"
        ,"nb": "Bangladesh"
        ,"nl": "Bangladesh"
        ,"ru": "Бангладеш"
        ,"sco": "Bangladesh"
        },
    "Q25230":{        
        "ar": "غيرنزي"
        ,"de": "Guernsey"
        ,"el": "Γκέρνσεϊ"
        ,"en": "Guernsey"
        ,"eo": "Gernezejo"
        ,"es": "Guernsey"
        ,"et": "Guernsey"
        ,"fa": "گرنزی"
        ,"fr": "Guernesey"
        ,"it": "Guernsey"
        ,"nb": "Guernsey"
        ,"nl": "Guernsey"
        ,"ru": "Гернси"
        ,"sco": "Guernsey"
        },
    "Q1036":{        
        "ar": "أوغندا"
        ,"de": "Uganda"
        ,"el": "Ουγκάντα"
        ,"en": "Uganda"
        ,"eo": "Ugando"
        ,"es": "Uganda"
        ,"et": "Uganda"
        ,"fa": "اوگاندا"
        ,"fr": "Ouganda"
        ,"it": "Uganda"
        ,"nb": "Uganda"
        ,"nl": "Oeganda"
        ,"ru": "Уганда"
        ,"sco": "Uganda"
        },
    "Q1008":{        
        "ar": "ساحل العاج"
        ,"de": "Elfenbeinküste"
        ,"el": "Ακτή Ελεφαντοστού"
        ,"en": "Ivory Coast"
        ,"eo": "Ebur-Bordo"
        ,"es": "Costa de Marfil"
        ,"et": "Elevandiluurannik"
        ,"fa": "ساحل عاج"
        ,"fr": "Côte d'Ivoire"
        ,"it": "Costa d'Avorio"
        ,"nb": "Elfenbenskysten"
        ,"nl": "Ivoorkust"
        ,"ru": "Кот-д’Ивуар"
        ,"sco": "Côte d'Ivoire"
        },
    "Q1032":{        
        "ar": "النيجر"
        ,"de": "Niger"
        ,"el": "Νίγηρας"
        ,"en": "Niger"
        ,"eo": "Niĝero"
        ,"es": "Níger"
        ,"et": "Niger"
        ,"fa": "نیجر"
        ,"fr": "Niger"
        ,"it": "Niger"
        ,"nb": "Niger"
        ,"nl": "Niger"
        ,"ru": "Нигер"
        ,"sco": "Niger"
        },
    "Q1033":{        
        "ar": "نيجيريا"
        ,"de": "Nigeria"
        ,"el": "Νιγηρία"
        ,"en": "Nigeria"
        ,"eo": "Niĝerio"
        ,"es": "Nigeria"
        ,"et": "Nigeeria"
        ,"fa": "نیجریه"
        ,"fr": "Nigeria"
        ,"it": "Nigeria"
        ,"nb": "Nigeria"
        ,"nl": "Nigeria"
        ,"ru": "Нигерия"
        ,"sco": "Nigerie"
        },
    "Q1030":{        
        "ar": "ناميبيا"
        ,"de": "Namibia"
        ,"el": "Ναμίμπια"
        ,"en": "Namibia"
        ,"eo": "Namibio"
        ,"es": "Namibia"
        ,"et": "Namiibia"
        ,"fa": "نامیبیا"
        ,"fr": "Namibie"
        ,"it": "Namibia"
        ,"nb": "Namibia"
        ,"nl": "Namibië"
        ,"ru": "Намибия"
        ,"sco": "Namibie"
        },
    "Q191":{        
        "ar": "إستونيا"
        ,"de": "Estland"
        ,"el": "Εσθονία"
        ,"en": "Estonia"
        ,"eo": "Estonio"
        ,"es": "Estonia"
        ,"et": "Eesti"
        ,"fa": "استونی"
        ,"fr": "Estonie"
        ,"it": "Estonia"
        ,"nb": "Estland"
        ,"nl": "Estland"
        ,"ru": "Эстония"
        ,"sco": "Estonie"
        },
    "Q965":{        
        "ar": "بوركينا فاسو"
        ,"de": "Burkina Faso"
        ,"el": "Μπουρκίνα Φάσο"
        ,"en": "Burkina Faso"
        ,"eo": "Burkino"
        ,"es": "Burkina Faso"
        ,"et": "Burkina Faso"
        ,"fa": "بورکینافاسو"
        ,"fr": "Burkina Faso"
        ,"it": "Burkina Faso"
        ,"nb": "Burkina Faso"
        ,"nl": "Burkina Faso"
        ,"ru": "Буркина-Фасо"
        ,"sco": "Burkina Faso"
        },
    "Q967":{        
        "ar": "بوروندي"
        ,"de": "Burundi"
        ,"el": "Μπουρούντι"
        ,"en": "Burundi"
        ,"eo": "Burundo"
        ,"es": "Burundi"
        ,"et": "Burundi"
        ,"fa": "بوروندی"
        ,"fr": "Burundi"
        ,"it": "Burundi"
        ,"nb": "Burundi"
        ,"nl": "Burundi"
        ,"ru": "Бурунди"
        ,"sco": "Burundi"
        },
    "Q962":{        
        "ar": "بنين"
        ,"de": "Benin"
        ,"el": "Μπενίν"
        ,"en": "Benin"
        ,"eo": "Benino"
        ,"es": "Benín"
        ,"et": "Benin"
        ,"fa": "بنین"
        ,"fr": "Bénin"
        ,"it": "Benin"
        ,"nb": "Benin"
        ,"nl": "Benin"
        ,"ru": "Бенин"
        ,"sco": "Benin"
        },
    "Q963":{        
        "ar": "بوتسوانا"
        ,"de": "Botswana"
        ,"el": "Μποτσουάνα"
        ,"en": "Botswana"
        ,"eo": "Bocvano"
        ,"es": "Botsuana"
        ,"et": "Botswana"
        ,"fa": "بوتسوانا"
        ,"fr": "Botswana"
        ,"it": "Botswana"
        ,"nb": "Botswana"
        ,"nl": "Botswana"
        ,"ru": "Ботсвана"
        ,"sco": "Botswana"
        },
    "Q697":{        
        "ar": "ناورو"
        ,"de": "Nauru"
        ,"el": "Ναουρού"
        ,"en": "Nauru"
        ,"eo": "Nauro"
        ,"es": "Nauru"
        ,"et": "Nauru"
        ,"fa": "نائورو"
        ,"fr": "Nauru"
        ,"it": "Nauru"
        ,"nb": "Nauru"
        ,"nl": "Nauru"
        ,"ru": "Науру"
        ,"sco": "Nauru"
        },
    "Q298":{        
        "ar": "تشيلي"
        ,"de": "Chile"
        ,"el": "Χιλή"
        ,"en": "Chile"
        ,"eo": "Ĉilio"
        ,"es": "Chile"
        ,"et": "Tšiili"
        ,"fa": "شیلی"
        ,"fr": "Chili"
        ,"it": "Cile"
        ,"nb": "Chile"
        ,"nl": "Chili"
        ,"ru": "Чили"#
        ,"sco": "Chile"
        },
    "Q695":{        
        "ar": "بالاو"
        ,"de": "Palau"
        ,"el": "Παλάου"
        ,"en": "Palau"
        ,"eo": "Palaŭo"
        ,"es": "Palaos"
        ,"et": "Belau"
        ,"fa": "پالائو"
        ,"fr": "Palaos"
        ,"it": "Palau"
        ,"nb": "Palau"
        ,"nl": "Palau"
        ,"ru": "Палау"
        ,"sco": "Palau"
        },
    "Q115":{        
        "ar": "إثيوبيا"
        ,"de": "Äthiopien"
        ,"el": "Αιθιοπία"
        ,"en": "Ethiopia"
        ,"eo": "Etiopio"
        ,"es": "Etiopía"
        ,"et": "Etioopia"
        ,"fa": "اتیوپی"
        ,"fr": "Éthiopie"
        ,"it": "Etiopia"
        ,"nb": "Etiopia"
        ,"nl": "Ethiopië"
        ,"ru": "Эфиопия"
        ,"sco": "Ethiopie"
        },
    "Q114":{        
        "ar": "كينيا"
        ,"de": "Kenia"
        ,"el": "Κένυα"
        ,"en": "Kenya"
        ,"eo": "Kenjo"
        ,"es": "Kenia"
        ,"et": "Kenya"
        ,"fa": "کنیا"
        ,"fr": "Kenya"
        ,"it": "Kenya"
        ,"nb": "Kenya"
        ,"nl": "Kenia"
        ,"ru": "Кения"
        ,"sco": "Kenyae"
        },
    "Q117":{        
        "ar": "غانا"
        ,"de": "Ghana"
        ,"el": "Γκάνα"
        ,"en": "Ghana"
        ,"eo": "Ganao"
        ,"es": "Ghana"
        ,"et": "Ghana"
        ,"fa": "غنا"
        ,"fr": "Ghana"
        ,"it": "Ghana"
        ,"nb": "Ghana"
        ,"nl": "Ghana"
        ,"ru": "Гана"
        ,"sco": "Ghana"
        },
    "Q754":{        
        "ar": "ترينيداد وتوباغو"
        ,"de": "Trinidad und Tobago"
        ,"el": "Τρινιντάντ και Τομπάγκο"
        ,"en": "Trinidad and Tobago"
        ,"eo": "Trinidado kaj Tobago"
        ,"es": "Trinidad y Tobago"
        ,"et": "Trinidad ja Tobago"
        ,"fa": "ترینیداد و توباگو"
        ,"fr": "Trinité-et-Tobago"
        ,"it": "Trinidad e Tobago"
        ,"nb": "Trinidad og Tobago"
        ,"nl": "Trinidad en Tobago"
        ,"ru": "Тринидад и Тобаго"
        ,"sco": "Trinidad an Tobago"
        },
    "Q750":{        
        "ar": "بوليفيا"
        ,"de": "Bolivien"
        ,"el": "Βολιβία"
        ,"en": "Bolivia"
        ,"eo": "Bolivio"
        ,"es": "Bolivia"
        ,"et": "Boliivia"
        ,"fa": "بولیوی"
        ,"fr": "Bolivie"
        ,"it": "Bolivia"
        ,"nb": "Bolivia"
        ,"nl": "Bolivia"
        ,"ru": "Боливия"
        ,"sco": "Bolivie"
        },
    "Q212":{        
        "ar": "أوكرانيا"
        ,"de": "Ukraine"
        ,"el": "Ουκρανία"
        ,"en": "Ukraine"
        ,"eo": "Ukrainio"
        ,"es": "Ucrania"
        ,"et": "Ukraina"
        ,"fa": "اوکراین"
        ,"fr": "Ukraine"
        ,"it": "Ucraina"
        ,"nb": "Ukraina"
        ,"nl": "Oekraïne"
        ,"ru": "Украина"
        ,"sco": "Ukraine"
        },
    "Q213":{        
        "ar": "التشيك"
        ,"de": "Tschechien"
        ,"el": "Τσεχία"
        ,"en": "the Czech Republic"
        ,"eo": "Ĉeĥio"
        ,"es": "República Checa"
        ,"et": "Tšehhi"
        ,"fa": "جمهوری چک"
        ,"fr": "République tchèque"
        ,"it": "Repubblica Ceca"
        ,"nb": "Tsjekkia"
        ,"nl": "Tsjechië"
        ,"ru": "Чехия"
        ,"sco": "Czech Republic"
        },
    "Q211":{        
        "ar": "لاتفيا"
        ,"de": "Lettland"
        ,"el": "Λετονία"
        ,"en": "Latvia"
        ,"eo": "Latvio"
        ,"es": "Letonia"
        ,"et": "Läti"
        ,"fa": "لتونی"
        ,"fr": "Lettonie"
        ,"it": "Lettonia"
        ,"nb": "Latvia"
        ,"nl": "Letland"
        ,"ru": "Латвия"
        ,"sco": "Latvie"
        },
    "Q217":{        
        "ar": "مولدافيا"
        ,"de": "Moldawien"
        ,"el": "Μολδαβία"
        ,"en": "Moldova"
        ,"eo": "Moldavio"
        ,"es": "Moldavia"
        ,"et": "Moldova"
        ,"fa": "مولداوی"
        ,"fr": "Moldavie"
        ,"it": "Moldavia"
        ,"nb": "Moldova"
        ,"nl": "Moldavië"
        ,"ru": "Молдавия"
        ,"sco": "Moldovae"
        },
    "Q214":{        
        "ar": "سلوفاكيا"
        ,"de": "Slowakei"
        ,"el": "Σλοβακία"
        ,"en": "Slovakia"
        ,"eo": "Slovakio"
        ,"es": "Eslovaquia"
        ,"et": "Slovakkia"
        ,"fa": "اسلواکی"
        ,"fr": "Slovaquie"
        ,"it": "Slovacchia"
        ,"nb": "Slovakia"
        ,"nl": "Slowakije"
        ,"ru": "Словакия"
        ,"sco": "Slovakie"
        },
    "Q215":{        
        "ar": "سلوفينيا"
        ,"de": "Slowenien"
        ,"el": "Σλοβενία"
        ,"en": "Slovenia"
        ,"eo": "Slovenio"
        ,"es": "Eslovenia"
        ,"et": "Sloveenia"
        ,"fa": "اسلوونی"
        ,"fr": "Slovénie"
        ,"it": "Slovenia"
        ,"nb": "Slovenia"
        ,"nl": "Slovenië"
        ,"ru": "Словения"
        ,"sco": "Slovenie"
        },
    "Q218":{        
        "ar": "رومانيا"
        ,"de": "Rumänien"
        ,"el": "Ρουμανία"
        ,"en": "Romania"
        ,"eo": "Rumanio"
        ,"es": "Rumania"
        ,"et": "Rumeenia"
        ,"fa": "رومانی"
        ,"fr": "Roumanie"
        ,"it": "Romania"
        ,"nb": "Romania"
        ,"nl": "Roemenië"
        ,"ru": "Румыния"
        ,"sco": "Romanie"
        },
    "Q219":{        
        "ar": "بلغاريا"
        ,"de": "Bulgarien"
        ,"el": "Βουλγαρία"
        ,"en": "Bulgaria"
        ,"eo": "Bulgario"
        ,"es": "Bulgaria"
        ,"et": "Bulgaaria"
        ,"fa": "بلغارستان"
        ,"fr": "Bulgarie"
        ,"it": "Bulgaria"
        ,"nb": "Bulgaria"
        ,"nl": "Bulgarije"
        ,"ru": "Болгария"
        ,"sco": "Bulgarie"
        },
    "Q912":{        
        "ar": "مالي"
        ,"de": "Mali"
        ,"el": "Μάλι"
        ,"en": "Mali"
        ,"eo": "Malio"
        ,"es": "Malí"
        ,"et": "Mali"
        ,"fa": "مالی"
        ,"fr": "Mali"
        ,"it": "Mali"
        ,"nb": "Mali"
        ,"nl": "Mali"
        ,"ru": "Мали"
        ,"sco": "Mali"
        },
    "Q917":{        
        "ar": "بوتان"
        ,"de": "Bhutan"
        ,"el": "Μπουτάν"
        ,"en": "Bhutan"
        ,"eo": "Butano"
        ,"es": "Bután"
        ,"et": "Bhutan"
        ,"fa": "پادشاهی بوتان"
        ,"fr": "Bhoutan"
        ,"it": "Bhutan"
        ,"nb": "Bhutan"
        ,"nl": "Bhutan"
        ,"ru": "Бутан"
        ,"sco": "Bhutan"
        },
    "Q916":{        
        "ar": "أنغولا"
        ,"de": "Angola"
        ,"el": "Ανγκόλα"
        ,"en": "Angola"
        ,"eo": "Angolo"
        ,"es": "Angola"
        ,"et": "Angola"
        ,"fa": "آنگولا"
        ,"fr": "Angola"
        ,"it": "Angola"
        ,"nb": "Angola"
        ,"nl": "Angola"
        ,"ru": "Ангола"
        ,"sco": "Angolae"
        },
    "Q1000":{        
        "ar": "الغابون"
        ,"de": "Gabun"
        ,"el": "Γκαμπόν"
        ,"en": "Gabon"
        ,"eo": "Gabono"
        ,"es": "Gabón"
        ,"et": "Gabon"
        ,"fa": "گابن"
        ,"fr": "Gabon"
        ,"it": "Gabon"
        ,"nb": "Gabon"
        ,"nl": "Gabon"
        ,"ru": "Габон"
        ,"sco": "Gabon"
        },
    "Q1007":{        
        "ar": "غينيا بيساو"
        ,"de": "Guinea-Bissau"
        ,"el": "Γουινέα-Μπισσάου"
        ,"en": "Guinea-Bissau"
        ,"eo": "Gvineo Bisaŭa"
        ,"es": "Guinea-Bisáu"
        ,"et": "Guinea-Bissau"
        ,"fa": "گینه بیسائو"
        ,"fr": "Guinée-Bissau"
        ,"it": "Guinea-Bissau"
        ,"nb": "Guinea-Bissau"
        ,"nl": "Guinee-Bissau"
        ,"ru": "Гвинея-Бисау"
        ,"sco": "Guinea-Bissau"
        },
    "Q1006":{        
        "ar": "غينيا"
        ,"de": "Guinea"
        ,"el": "Γουινέα"
        ,"en": "Guinea"
        ,"eo": "Gvineo"
        ,"es": "Guinea"
        ,"et": "Guinea"
        ,"fa": "گینه"
        ,"fr": "Guinée"
        ,"it": "Guinea"
        ,"nb": "Guinea"
        ,"nl": "Guinee"
        ,"ru": "Гвинея"
        ,"sco": "Guinea"
        },
    "Q1005":{        
        "ar": "غامبيا"
        ,"de": "Gambia"
        ,"el": "Γκάμπια"
        ,"en": "Gambia"
        ,"eo": "Gambio"
        ,"es": "Gambia"
        ,"et": "Gambia"
        ,"fa": "گامبیا"
        ,"fr": "Gambie"
        ,"it": "Gambia"
        ,"nb": "Gambia"
        ,"nl": "Gambia"
        ,"ru": "Гамбия"
        ,"sco": "The Gambie"
        },
    "Q712":{        
        "ar": "فيجي"
        ,"de": "Fidschi"
        ,"el": "Φίτζι"
        ,"en": "Fiji"
        ,"eo": "Fiĝioj"
        ,"es": "Fiyi"
        ,"et": "Fidži"
        ,"fa": "فیجی"
        ,"fr": "Fidji"
        ,"it": "Figi"
        ,"nb": "Fiji"
        ,"nl": "Fiji"
        ,"ru": "Фиджи"
        ,"sco": "Fiji"
        },
    "Q977":{        
        "ar": "جيبوتي"
        ,"de": "Dschibuti"
        ,"el": "Τζιμπουτί"
        ,"en": "Djibouti"
        ,"eo": "Ĝibutio"
        ,"es": "Yibuti"
        ,"et": "Djibouti"
        ,"fa": "جیبوتی"
        ,"fr": "Djibouti"
        ,"it": "Gibuti"
        ,"nb": "Djibouti"
        ,"nl": "Djibouti"
        ,"ru": "Джибути"
        ,"sco": "Djibouti"
        },
    "Q1009":{        
        "ar": "الكاميرون"
        ,"de": "Kamerun"
        ,"el": "Καμερούν"
        ,"en": "Cameroon"
        ,"eo": "Kameruno"
        ,"es": "Camerún"
        ,"et": "Kamerun"
        ,"fa": "کامرون"
        ,"fr": "Cameroun"
        ,"it": "Camerun"
        ,"nb": "Kamerun"
        ,"nl": "Kameroen"
        ,"ru": "Камерун"
        ,"sco": "Cameroon"
        },
    "Q974":{        
        "ar": "جمهورية الكونغو الديمقراطية"
        ,"de": "Demokratische Republik Kongo"
        ,"el": "Λαϊκή Δημοκρατία του Κονγκό"
        ,"en": "Democratic Republic of the Congo"
        ,"eo": "Demokratia Respubliko Kongo"
        ,"es": "República Democrática del Congo"
        ,"et": "Kongo Demokraatlik Vabariik"
        ,"fa": "جمهوری دموکراتیک کنگو"
        ,"fr": "République démocratique du Congo"
        ,"it": "Repubblica Democratica del Congo"
        ,"nb": "Den demokratiske republikken Kongo"
        ,"nl": "Congo-Kinshasa"
        ,"ru": "Демократическая Республика Конго"
        ,"sco": "Democratic Republic o the Congo"
        },
    "Q971":{        
        "ar": "جمهورية الكونغو"
        ,"de": "Republik Kongo"
        ,"el": "Δημοκρατία του Κονγκό"
        ,"en": "Republic of the Congo"
        ,"eo": "Respubliko Kongo"
        ,"es": "República del Congo"
        ,"et": "Kongo Vabariik"
        ,"fa": "جمهوری کنگو"
        ,"fr": "République du Congo"
        ,"it": "Repubblica del Congo"
        ,"nb": "Republikken Kongo"
        ,"nl": "Republiek Congo"
        ,"ru": "Республика Конго"
        ,"sco": "Republic o the Congo"
        },
    "Q970":{        
        "ar": "جزر القمر"
        ,"de": "Komoren"
        ,"el": "Κομόρες"
        ,"en": "Comoros"
        ,"eo": "Komoroj"
        ,"es": "Comoras"
        ,"et": "Komoorid"
        ,"fa": "مجمع‌الجزایر قمر"
        ,"fr": "Comores"
        ,"it": "Comore"
        ,"nb": "Komorene"
        ,"nl": "de Comoren"
        ,"ru": "Коморы"
        ,"sco": "Comoros"
        },
    "Q683":{        
        "ar": "ساموا"
        ,"de": "Samoa"
        ,"el": "Σαμόα"
        ,"en": "Samoa"
        ,"eo": "Samoo"
        ,"es": "Samoa"
        ,"et": "Samoa"
        ,"fa": "ساموآ"
        ,"fr": "Samoa"
        ,"it": "Samoa"
        ,"nb": "Samoa"
        ,"nl": "Samoa"
        ,"ru": "Самоа"
        ,"sco": "Samoa"
        },
    "Q769":{        
        "ar": "غرينادا"
        ,"de": "Grenada"
        ,"el": "Γρενάδα"
        ,"en": "Grenada"
        ,"eo": "Grenado"
        ,"es": "Granada"
        ,"et": "Grenada"
        ,"fa": "گرنادا"
        ,"fr": "Grenade"
        ,"it": "Grenada"
        ,"nb": "Grenada"
        ,"nl": "Grenada"
        ,"ru": "Гренада"
        ,"sco": "Grenada"
        },
    "Q685":{        
        "ar": "جزر سليمان"
        ,"de": "Salomonen"
        ,"el": "Νήσοι Σολομώντα"
        ,"en": "the Solomon Islands"
        ,"eo": "Salomonoj"
        ,"es": "Islas Salomón"
        ,"et": "Saalomoni Saared"
        ,"fa": "جزایر سلیمان"
        ,"fr": "Salomon"
        ,"it": "Isole Salomone"
        ,"nb": "Salomonøyene"
        ,"nl": "de Salomonseilanden"
        ,"ru": "Соломоновы Острова"
        ,"sco": "Solomon Islands"
        },
    "Q686":{        
        "ar": "فانواتو"
        ,"de": "Vanuatu"
        ,"el": "Βανουάτου"
        ,"en": "Vanuatu"
        ,"eo": "Vanuatuo"
        ,"es": "Vanuatu"
        ,"et": "Vanuatu"
        ,"fa": "وانواتو"
        ,"fr": "Vanuatu"
        ,"it": "Vanuatu"
        ,"nb": "Vanuatu"
        ,"nl": "Vanuatu"
        ,"ru": "Вануату"
        ,"sco": "Vanuatu"
        },
    "Q836":{        
        "ar": "ميانمار"
        ,"de": "Myanmar"
        ,"el": "Μιανμάρ"
        ,"en": "Myanmar"
        ,"eo": "Birmo"
        ,"es": "Birmania"
        ,"et": "Birma"
        ,"fa": "میانمار"
        ,"fr": "Birmanie"
        ,"it": "Birmania"
        ,"nb": "Myanmar"
        ,"nl": "Myanmar"
        ,"ru": "Мьянма"
        ,"sco": "Burma"
        },
    "Q766":{        
        "ar": "جامايكا"
        ,"de": "Jamaika"
        ,"el": "Τζαμάικα"
        ,"en": "Jamaica"
        ,"eo": "Jamajko"
        ,"es": "Jamaica"
        ,"et": "Jamaica"
        ,"fa": "جامائیکا"
        ,"fr": "Jamaïque"
        ,"it": "Giamaica"
        ,"nb": "Jamaica"
        ,"nl": "Jamaica"
        ,"ru": "Ямайка"
        ,"sco": "Jamaica"
        },
    "Q574":{        
        "ar": "تيمور الشرقية"
        ,"de": "Osttimor"
        ,"el": "Ανατολικό Τιμόρ"
        ,"en": "East Timor"
        ,"eo": "Orienta Timoro"
        ,"es": "Timor Oriental"
        ,"et": "Ida-Timor"
        ,"fa": "تیمور شرقی"
        ,"fr": "Timor oriental"
        ,"it": "Timor Est"
        ,"nb": "Øst-Timor"
        ,"nl": "Oost-Timor"
        ,"ru": "Восточный Тимор"
        ,"sco": "East Timor"
        },
    "Q874":{        
        "ar": "تركمانستان"
        ,"de": "Turkmenistan"
        ,"el": "Τουρκμενιστάν"
        ,"en": "Turkmenistan"
        ,"eo": "Turkmenio"
        ,"es": "Turkmenistán"
        ,"et": "Türkmenistan"
        ,"fa": "ترکمنستان"
        ,"fr": "Turkménistan"
        ,"it": "Turkmenistan"
        ,"nb": "Turkmenistan"
        ,"nl": "Turkmenistan"
        ,"ru": "Туркмения"
        ,"sco": "Turkmenistan"
        },
    "Q6250":{        
        "ar": "الصحراء الغربية"
        ,"de": "Westsahara"
        ,"el": "Δυτική Σαχάρα"
        ,"en": "Western Sahara"
        ,"eo": "Okcidenta Saharo"
        ,"es": "Sahara Occidental"
        ,"et": "Lääne-Sahara"
        ,"fa": "صحرای غربی"
        ,"fr": "Sahara occidental"
        ,"it": "Sahara Occidentale"
        ,"nb": "Vest-Sahara"
        ,"nl": "Westelijke Sahara"
        ,"ru": "Западная Сахара"
        ,"sco": "Wastren Sahara"
        },
    "Q79":{        
        "ar": "مصر"
        ,"de": "Ägypten"
        ,"el": "Αίγυπτος"
        ,"en": "Egypt"
        ,"eo": "Egiptio"
        ,"es": "Egipto"
        ,"et": "Egiptus"
        ,"fa": "مصر"
        ,"fr": "Égypte"
        ,"it": "Egitto"
        ,"nb": "Egypt"
        ,"nl": "Egypte"
        ,"ru": "Египет"
        ,"sco": "Egyp"
        },
    "Q77":{        
        "ar": "الأوروغواي"
        ,"de": "Uruguay"
        ,"el": "Ουρουγουάη"
        ,"en": "Uruguay"
        ,"eo": "Urugvajo"
        ,"es": "Uruguay"
        ,"et": "Uruguay"
        ,"fa": "اروگوئه"
        ,"fr": "Uruguay"
        ,"it": "Uruguay"
        ,"nb": "Uruguay"
        ,"nl": "Uruguay"
        ,"ru": "Уругвай"
        ,"sco": "Uruguay"
        },
    "Q878":{        
        "ar": "الإمارات العربية المتحدة"
        ,"de": "Vereinigte Arabische Emirate"
        ,"el": "Ηνωμένα Αραβικά Εμιράτα"
        ,"en": "United Arab Emirates"
        ,"eo": "Unuiĝintaj Arabaj Emirlandoj"
        ,"es": "Emiratos Árabes Unidos"
        ,"et": "Araabia Ühendemiraadid"
        ,"fa": "امارات متحده عربی"
        ,"fr": "Émirats arabes unis"
        ,"it": "Emirati Arabi Uniti"
        ,"nb": "De forente arabiske emirater"
        ,"nl": "de Verenigde Arabische Emiraten"
        ,"ru": "Объединённые Арабские Эмираты"
        ,"sco": "Unitit Arab Emirates"
        },
    "Q774":{        
        "ar": "غواتيمالا"
        ,"de": "Guatemala"
        ,"el": "Γουατεμάλα"
        ,"en": "Guatemala"
        ,"eo": "Gvatemalo"
        ,"es": "Guatemala"
        ,"et": "Guatemala"
        ,"fa": "گواتمالا"
        ,"fr": "Guatemala"
        ,"it": "Guatemala"
        ,"nb": "Guatemala"
        ,"nl": "Guatemala"
        ,"ru": "Гватемала"
        ,"sco": "Guatemala"
        },
    "Q948":{        
        "ar": "تونس"
        ,"de": "Tunesien"
        ,"el": "Τυνησία"
        ,"en": "Tunisia"
        ,"eo": "Tunizio"
        ,"es": "Túnez"
        ,"et": "Tuneesia"
        ,"fa": "تونس"
        ,"fr": "Tunisie"
        ,"it": "Tunisia"
        ,"nb": "Tunisia"
        ,"nl": "Tunesië"
        ,"ru": "Тунис"
        ,"sco": "Tunisie"
        },
    "Q817":{        
        "ar": "الكويت"
        ,"de": "Kuwait"
        ,"el": "Κουβέιτ"
        ,"en": "Kuwait"
        ,"eo": "Kuvajto"
        ,"es": "Kuwait"
        ,"et": "Kuveit"
        ,"fa": "کویت"
        ,"fr": "Koweït"
        ,"it": "Kuwait"
        ,"nb": "Kuwait"
        ,"nl": "Koeweit"
        ,"ru": "Кувейт"
        ,"sco": "Kuwait"
        },
    "Q810":{        
        "ar": "الأردن"
        ,"de": "Jordanien"
        ,"el": "Ιορδανία"
        ,"en": "Jordan"
        ,"eo": "Jordanio"
        ,"es": "Jordania"
        ,"et": "Jordaania"
        ,"fa": "اردن"
        ,"fr": "Jordanie"
        ,"it": "Giordania"
        ,"nb": "Jordan"
        ,"nl": "Jordanië"
        ,"ru": "Иордания"
        ,"sco": "Jordan"
        },
    "Q811":{        
        "ar": "نيكاراغوا"
        ,"de": "Nicaragua"
        ,"el": "Νικαράγουα"
        ,"en": "Nicaragua"
        ,"eo": "Nikaragvo"
        ,"es": "Nicaragua"
        ,"et": "Nicaragua"
        ,"fa": "نیکاراگوئه"
        ,"fr": "Nicaragua"
        ,"it": "Nicaragua"
        ,"nb": "Nicaragua"
        ,"nl": "Nicaragua"
        ,"ru": "Никарагуа"
        ,"sco": "Nicaragua"
        },
    "Q813":{        
        "ar": "قيرغيزستان"
        ,"de": "Kirgisistan"
        ,"el": "Κιργιζία"
        ,"en": "Kyrgyzstan"
        ,"eo": "Kirgizio"
        ,"es": "Kirguistán"
        ,"et": "Kõrgõzstan"
        ,"fa": "قرقیزستان"
        ,"fr": "Kirghizistan"
        ,"it": "Kirghizistan"
        ,"nb": "Kirgisistan"
        ,"nl": "Kirgizië"
        ,"ru": "Киргизия"
        ,"sco": "Kyrgyzstan"
        },
    "Q1014":{        
        "ar": "ليبيريا"
        ,"de": "Liberia"
        ,"el": "Λιβερία"
        ,"en": "Liberia"
        ,"eo": "Liberio"
        ,"es": "Liberia"
        ,"et": "Libeeria"
        ,"fa": "لیبریا"
        ,"fr": "Liberia"
        ,"it": "Liberia"
        ,"nb": "Liberia"
        ,"nl": "Liberia"
        ,"ru": "Либерия"
        ,"sco": "Liberie"
        },
    "Q1016":{        
        "ar": "ليبيا"
        ,"de": "Libyen"
        ,"el": "Λιβύη"
        ,"en": "Libya"
        ,"eo": "Libio"
        ,"es": "Libia"
        ,"et": "Liibüa"
        ,"fa": "لیبی"
        ,"fr": "Libye"
        ,"it": "Libia"
        ,"nb": "Libya"
        ,"nl": "Libië"
        ,"ru": "Ливия"
        ,"sco": "Libie"
        },
    "Q1246":{        
        "ar": "كوسوفو"
        ,"de": "Kosovo"
        ,"el": "Κόσοβο"
        ,"en": "Kosovo"
        ,"eo": "Kosovo"
        ,"es": "Kosovo"
        ,"et": "Kosovo"
        ,"fa": "استان کوزووو"
        ,"fr": "Kosovo"
        ,"it": "Kosovo"
        ,"nb": "Kosovo"
        ,"nl": "Kosovo"
        ,"ru": "Республика Косово"
        ,"sco": "Kosovo"
        },
    "Q739":{        
        "ar": "كولومبيا"
        ,"de": "Kolumbien"
        ,"el": "Κολομβία"
        ,"en": "Colombia"
        ,"eo": "Kolombio"
        ,"es": "Colombia"
        ,"et": "Colombia"
        ,"fa": "کلمبیا"
        ,"fr": "Colombie"
        ,"it": "Colombia"
        ,"nb": "Colombia"
        ,"nl": "Colombia"
        ,"ru": "Колумбия"
        ,"sco": "Colombie"
        },
    "Q778":{        
        "ar": "باهاماس"
        ,"de": "Bahamas"
        ,"el": "Μπαχάμες"
        ,"en": "The Bahamas"
        ,"eo": "Bahamoj"
        ,"es": "Bahamas"
        ,"et": "Bahama"
        ,"fa": "باهاما"
        ,"fr": "Bahamas"
        ,"it": "Bahama"
        ,"nb": "Bahamas"
        ,"nl": "de Bahama's"#
        ,"ru": "Багамские Острова"
        ,"sco": "The Bahamas"
        },
    "Q945":{        
        "ar": "توغو"
        ,"de": "Togo"
        ,"el": "Τόγκο"
        ,"en": "Togo"
        ,"eo": "Togolando"
        ,"es": "Togo"
        ,"et": "Togo"
        ,"fa": "توگو"
        ,"fr": "Togo"
        ,"it": "Togo"
        ,"nb": "Togo"
        ,"nl": "Togo"
        ,"ru": "Того"
        ,"sco": "Togo"
        },
    "Q25228":{        
        "ar": "أنغويلا"
        ,"de": "Anguilla"
        ,"el": "Ανγκουίλα"
        ,"en": "Anguilla"
        ,"eo": "Angvilo"
        ,"es": "Anguila"
        ,"et": "Anguilla"
        ,"fa": "آنگویلا"
        ,"fr": "Anguilla"
        ,"it": "Anguilla"
        ,"nb": "Anguilla"
        ,"nl": "Anguilla"
        ,"ru": "Ангилья"
        ,"sco": "Anguilla"
        },
    "Q678":{        
        "ar": "تونغا"
        ,"de": "Tonga"
        ,"el": "Τόνγκα"
        ,"en": "Tonga"
        ,"eo": "Tongo"
        ,"es": "Tonga"
        ,"et": "Tonga"
        ,"fa": "تونگا"
        ,"fr": "Tonga"
        ,"it": "Tonga"
        ,"nb": "Tonga"
        ,"nl": "Tonga"
        ,"ru": "Тонга"
        ,"sco": "Tonga"
        },
    "Q26273":{        
        "ar": "سينت مارتن"
        ,"de": "Sint Maarten"
        ,"el": "Άγιος Μαρτίνος"
        ,"en": "Sint Maarten"
        ,"eo": "Sint-Maarten"
        ,"es": "Sint Maarten"
        ,"et": "Sint Maarten"
        ,"fa": "سینت مارتن"
        ,"fr": "Saint-Martin (Royaume des Pays-Bas)"
        ,"it": "Sint Maarten"
        ,"nb": "Sint Maarten"
        ,"nl": "Sint Maarten"
        ,"ru": "Синт-Мартен"
        ,"sco": "Sint Maarten"
        },
    "Q863":{        
        "ar": "طاجيكستان"
        ,"de": "Tadschikistan"
        ,"el": "Τατζικιστάν"
        ,"en": "Tajikistan"
        ,"eo": "Taĝikio"
        ,"es": "Tayikistán"
        ,"et": "Tadžikistan"
        ,"fa": "تاجیکستان"
        ,"fr": "Tadjikistan"
        ,"it": "Tagikistan"
        ,"nb": "Tadsjikistan"
        ,"nl": "Tadzjikistan"
        ,"ru": "Таджикистан"
        ,"sco": "Tajikistan"
        },
    "Q865":{        
        "ar": "تايوان"
        ,"de": "Republik China (Taiwan)"
        ,"el": "Δημοκρατία της Κίνας"
        ,"en": "Taiwan"
        ,"eo": "Tajvano"
        ,"es": "Taiwán"
        ,"et": "Hiina Vabariik"
        ,"fa": "تایوان"
        ,"fr": "République de Chine"
        ,"it": "Taiwan"
        ,"nb": "Republikken Kina"
        ,"nl": "Taiwan"
        ,"ru": "Китайская Республика"
        ,"sco": "Republic o Cheenae"
        },
    "Q869":{        
        "ar": "تايلاند"
        ,"de": "Thailand"
        ,"el": "Ταϊλάνδη"
        ,"en": "Thailand"
        ,"eo": "Tajlando"
        ,"es": "Tailandia"
        ,"et": "Tai"
        ,"fa": "تایلند"
        ,"fr": "Thaïlande"
        ,"it": "Thailandia"
        ,"nb": "Thailand"
        ,"nl": "Thailand"
        ,"ru": "Таиланд"
        ,"sco": "Thailand"
        },
    "Q953":{        
        "ar": "زامبيا"
        ,"de": "Sambia"
        ,"el": "Ζάμπια"
        ,"en": "Zambia"
        ,"eo": "Zambio"
        ,"es": "Zambia"
        ,"et": "Sambia"
        ,"fa": "زامبیا"
        ,"fr": "Zambie"
        ,"it": "Zambia"
        ,"nb": "Zambia"
        ,"nl": "Zambia"
        ,"ru": "Замбия"
        ,"sco": "Zambie"
        },

    }
