#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
#!/usr/bin/env python3

أوصاف مناطق جغرافية

"""
#
# (C) Ibrahem Qasim, 2022
#
'''SELECT 
(concat(', "' , str(?value), '" : {')  as ?value1)
(concat('"item" : "' , strafter(str(?item),"/entity/") , '" , ')  as ?item1)
(concat('"ar" : "' , str(?label) , '" , ')  as ?ar)
(concat('"en" : "' , str(?en) , '" } ')  as ?enen)

{
    ?item wdt:P2452 ?value .
    ?item rdfs:label ?label  filter (lang(?label) = "ar")
    ?item rdfs:label ?en  filter (lang(?en) = "en")
}
LIMIT 1000'''
P17Table = {
    'Kapupud-ang_Solomon' : { 'label': 'جزر سليمان', 'Q': 'Q685'} , 
    'Svalbard_and_Jan_Mayen' : { 'label': 'سفالبارد ويان ماين', 'Q': 'Q20'} , 
    'Swisa' : { 'label': 'سويسرا', 'Q': 'Q39'} , 
    'Tailandya' : { 'label': 'تايلاند', 'Q': 'Q869'} , 
    'Tanzania' : { 'label': 'تنزانيا', 'Q': 'Q924'} , 
    'Tayikistan' : { 'label': 'طاجيكستان', 'Q': 'Q863'} , 
    'Togo' : { 'label': 'توغو', 'Q': 'Q945'} , 
    'Tonga' : { 'label': 'تونغا', 'Q': 'Q678'} , 
    'Trinidad_ug_Tobago' : { 'label': 'ترينيداد وتوباغو', 'Q': 'Q754'} , 
    'Tsekya' : { 'label': 'التشيك', 'Q': 'Q213'} , 
    'Tsipre' : { 'label': 'قبرص', 'Q': 'Q229'} , 
    'Tunisia' : { 'label': 'تونس', 'Q': 'Q948'} , 
    'Turkiya' : { 'label': 'تركيا', 'Q': 'Q43'} , 
    'Ireland' : { 'label': 'أيرلندا', 'Q': 'Q27'} , 
    'Turkmenistan' : { 'label': 'تركمانستان', 'Q': 'Q874'} , 
    'Turks_and_Caicos_Islands' : { 'label': 'جزر توركس وكايكوس', 'Q': 'Q145'} ,# Q18221
    'U.S._Virgin_Islands' : { 'label': 'جزر العذراء الأمريكية', 'Q': 'Q30'} , #Q11703
    'Uganda' : { 'label': 'أوغندا', 'Q': 'Q1036'} , 
    'Ukranya' : { 'label': 'أوكرانيا', 'Q': 'Q212'} , 
    'Unggriya' : { 'label': 'المجر', 'Q': 'Q28'} , 
    'United_States_Minor_Outlying_Islands' : { 'label': 'جزر الولايات المتحدة الصغيرة النائية', 'Q': 'Q30'} , #Q16645
    'Uruguay' : { 'label': 'الأوروغواي', 'Q': 'Q77'} , 
    'Uzbekistan' : { 'label': 'أوزبكستان', 'Q': 'Q265'} , 
    'Vanuatu' : { 'label': 'فانواتو', 'Q': 'Q686'} , 
    'Venezuela' : { 'label': 'فنزويلا', 'Q': 'Q717'} , 
    'Wallis_and_Futuna' : { 'label': 'واليس وفوتونا', 'Q': 'Q35555'} , 
    #'Western_Sahara' : { 'label': 'الصحراء الغربية', 'Q': 'Q6250'} , 
    'Yemen' : { 'label': 'اليمن', 'Q': 'Q805'} , 
    'Yibuti' : { 'label': 'جيبوتي', 'Q': 'Q977'} , 
    'Zambia' : { 'label': 'زامبيا', 'Q': 'Q953'} , 
    'Zimbabwe' : { 'label': 'زيمبابوي', 'Q': 'Q954'} , 
    'Aland_Islands' : { 'label': 'جزر أولاند', 'Q': 'Q33'} , #Q33#Q5689
    'Albanya' : { 'label': 'ألبانيا', 'Q': 'Q222'} , 
    'Alemanya' : { 'label': 'ألمانيا', 'Q': 'Q183'} , 
    'American_Samoa' : { 'label': 'ساموا الأمريكية', 'Q': 'Q30'} , #Q16641
    'Amihanang_Korea' : { 'label': 'كوريا الشمالية', 'Q': 'Q423'} , 
    'Andorra' : { 'label': 'أندورا', 'Q': 'Q228'} , 
    'Angola' : { 'label': 'أنغولا', 'Q': 'Q916'} , 
    'Anguilla' : { 'label': 'أنغويلا', 'Q': 'Q25228'} , 
    #'Antarctica' : { 'label': 'القارة القطبية الجنوبية', 'Q': 'Q51'} , 
    'Antigua_ug_Barbuda' : { 'label': 'أنتيغوا وباربودا', 'Q': 'Q781'} , 
    'Apganistan' : { 'label': 'أفغانستان', 'Q': 'Q889'} , 
    'Arabyang_Saudita' : { 'label': 'السعودية', 'Q': 'Q851'} , 
    'Arhelya' : { 'label': 'الجزائر', 'Q': 'Q262'} , 
    'Arhentina' : { 'label': 'الأرجنتين', 'Q': 'Q414'} , 
    'Armenya' : { 'label': 'أرمينيا', 'Q': 'Q399'} , 
    'Aruba' : { 'label': 'أروبا', 'Q': 'Q21203'} , 
    'Aserbaiyan' : { 'label': 'أذربيجان', 'Q': 'Q227'} , 
    'Awstralya' : { 'label': 'أستراليا', 'Q': 'Q408'} , 
    'Awstriya' : { 'label': 'النمسا', 'Q': 'Q40'} , 
    'Bahamas' : { 'label': 'باهاماس', 'Q': 'Q778'} , 
    'Cabo_Verde' : { 'label': 'الرأس الأخضر', 'Q': 'Q1011'} , 
    'Canada' : { 'label': 'كندا', 'Q': 'Q16'} , 
    'Cayman_Islands' : { 'label': 'جزر كايمان', 'Q': 'Q145'} , 
    'Chad' : { 'label': 'تشاد', 'Q': 'Q657'} , 
    'Chile' : { 'label': 'تشيلي', 'Q': 'Q298'} , 
    'Christmas_Island' : { 'label': 'جزيرة عيد الميلاد', 'Q': 'Q408'} , 
    'Colombia' : { 'label': 'كولومبيا', 'Q': 'Q739'} , 
    'Comoros' : { 'label': 'جزر القمر', 'Q': 'Q970'} , 
    'Cook_Islands' : { 'label': 'جزر كوك', 'Q': 'Q664'} , 
    'Costa_Rica' : { 'label': 'كوستاريكا', 'Q': 'Q800'} , 
    'Cuba' : { 'label': 'كوبا', 'Q': 'Q241'} , 
    'Curaçao' : { 'label': 'كوراساو', 'Q': 'Q25279'} , 
    'Dinamarka' : { 'label': 'الدنمارك', 'Q': 'Q35'} , 
    'Dominica' : { 'label': 'دومينيكا', 'Q': 'Q784'} , 
    'Ecuador' : { 'label': 'الإكوادور', 'Q': 'Q736'} , 
    'Ehipto' : { 'label': 'مصر', 'Q': 'Q79'} , 
    'El_Salvador' : { 'label': 'السلفادور', 'Q': 'Q792'} , 
    'Eritrea' : { 'label': 'إريتريا', 'Q': 'Q986'} , 
    'Eslobakya' : { 'label': 'سلوفاكيا', 'Q': 'Q214'} , 
    'Eslobenya' : { 'label': 'سلوفينيا', 'Q': 'Q215'} , 
    'Espanya' : { 'label': 'إسبانيا', 'Q': 'Q29'} , 
    'Estados_Unidos' : { 'label': 'الولايات المتحدة', 'Q': 'Q30'} , 
    'Estonia' : { 'label': 'إستونيا', 'Q': 'Q191'} , 
    'Etiopia' : { 'label': 'إثيوبيا', 'Q': 'Q115'} , 
    'Fiji' : { 'label': 'فيجي', 'Q': 'Q712'} , 
    'Finlandia' : { 'label': 'فنلندا', 'Q': 'Q33'} , 
    'French_Polynesia' : { 'label': 'بولينزيا الفرنسية', 'Q': 'Q142'} , 
    'French_Southern_Territories' : { 'label': 'أراض فرنسية جنوبية وأنتارتيكية', 'Q': 'Q142'} , 
    'Gabon' : { 'label': 'الغابون', 'Q': 'Q1000'} , 
    'Gambia' : { 'label': 'غامبيا', 'Q': 'Q1005'} , 
    'Georgia_(nasod)' : { 'label': 'جورجيا', 'Q': 'Q230'} , 
    'Ghana' : { 'label': 'غانا', 'Q': 'Q117'} , 
    'Gibraltar' : { 'label': 'جبل طارق', 'Q': 'Q1410'} , 
    'Gineang_Ekwatoryal' : { 'label': 'غينيا الاستوائية', 'Q': 'Q983'} , 
    'Greenland' : { 'label': 'جرينلاند', 'Q': 'Q223'} , 
    'Grenada' : { 'label': 'غرينادا', 'Q': 'Q769'} , 
    'Gresya' : { 'label': 'اليونان', 'Q': 'Q41'} , 
    'Guadeloupe' : { 'label': 'غوادلوب', 'Q': 'Q142'} , 
    'Guam' : { 'label': 'غوام', 'Q': 'Q30'} , 
    'Guatemala' : { 'label': 'غواتيمالا', 'Q': 'Q774'} , 
    'Guernsey' : { 'label': 'غيرنزي', 'Q': 'Q25230'} , 
    'Guinea' : { 'label': 'غينيا', 'Q': 'Q1006'} , 
    'Guinea-Bissau' : { 'label': 'غينيا بيساو', 'Q': 'Q1007'} , 
    'Guyana' : { 'label': 'غيانا', 'Q': 'Q734'} , 
    'Bangladesh' : { 'label': 'بنغلاديش', 'Q': 'Q902'} , 
    'Barbados' : { 'label': 'باربادوس', 'Q': 'Q244'} , 
    'Bareyn' : { 'label': 'البحرين', 'Q': 'Q398'} , 
    'Baybayon_sa_Marpil' : { 'label': 'ساحل العاج', 'Q': 'Q1008'} , 
    'Belhika' : { 'label': 'بلجيكا', 'Q': 'Q31'} , 
    'Belize' : { 'label': 'بليز', 'Q': 'Q242'} , 
    'Benin' : { 'label': 'بنين', 'Q': 'Q962'} , 
    'Bermuda' : { 'label': 'برمودا', 'Q': 'Q23635'} , 
    'Bhutan' : { 'label': 'بوتان', 'Q': 'Q917'} , 
    'Biyelorusya' : { 'label': 'روسيا البيضاء', 'Q': 'Q184'} , 
    'Biyetnam' : { 'label': 'فيتنام', 'Q': 'Q881'} , 
    'Bolivia' : { 'label': 'بوليفيا', 'Q': 'Q750'} , 
    'Bonaire,_Saint_Eustatius_and_Saba' : { 'label': 'الجزر الكاريبية الهولندية', 'Q': 'Q55'} , #Q27561
    'Bosnia_ug_Herzegovina' : { 'label': 'البوسنة والهرسك', 'Q': 'Q225'} , 
    'Botswana' : { 'label': 'بوتسوانا', 'Q': 'Q963'} , 
    'Bouvet_Island' : { 'label': 'جزيرة بوفيه', 'Q': 'Q20'} , #Q23408
    'Brasil' : { 'label': 'البرازيل', 'Q': 'Q155'} , 
    'British_Indian_Ocean_Territory' : { 'label': 'إقليم المحيط الهندي البريطاني', 'Q': 'Q145'} , #Q43448
    'British_Virgin_Islands' : { 'label': 'جزر العذراء البريطانية', 'Q': 'Q145'} , #Q25305
    'Brunei' : { 'label': 'بروناي', 'Q': 'Q921'} , 
    'Bulgaria' : { 'label': 'بلغاريا', 'Q': 'Q219'} , 
    'Burkina_Faso' : { 'label': 'بوركينا فاسو', 'Q': 'Q965'} , 
    'Burma' : { 'label': 'ميانمار', 'Q': 'Q836'} , 
    'Burundi' : { 'label': 'بوروندي', 'Q': 'Q967'} , 
    'Mayotte' : { 'label': 'مايوت', 'Q': 'Q142'} , 
    'Mehiko' : { 'label': 'المكسيك', 'Q': 'Q96'} , 
    'Moldabya' : { 'label': 'مولدافيا', 'Q': 'Q217'} , 
    'Monako' : { 'label': 'موناكو', 'Q': 'Q235'} , 
    'Mongolia' : { 'label': 'منغوليا', 'Q': 'Q711'} , 
    'Montenegro' : { 'label': 'الجبل الأسود', 'Q': 'Q236'} , 
    'Montserrat' : { 'label': 'مونتسرات', 'Q': 'Q13353'} , 
    'Mozambique' : { 'label': 'موزمبيق', 'Q': 'Q1029'} , 
    'Namibya' : { 'label': 'ناميبيا', 'Q': 'Q1030'} , 
    'Nauru' : { 'label': 'ناورو', 'Q': 'Q697'} , 
    'Nepal' : { 'label': 'نيبال', 'Q': 'Q837'} , 
    'New_Zealand' : { 'label': 'نيوزيلندا', 'Q': 'Q664'} , 
    'Nicaragua' : { 'label': 'نيكاراغوا', 'Q': 'Q811'} , 
    'Niger' : { 'label': 'النيجر', 'Q': 'Q1032'} , 
    'Nigeria' : { 'label': 'نيجيريا', 'Q': 'Q1033'} , 
    'Noruwega' : { 'label': 'النرويج', 'Q': 'Q20'} , 
    'Olanda' : { 'label': 'هولندا', 'Q': 'Q55'} , 
    'Oman' : { 'label': 'سلطنة عمان', 'Q': 'Q842'} , 
    'Pakistan' : { 'label': 'باكستان', 'Q': 'Q843'} , 
    'Palau' : { 'label': 'بالاو', 'Q': 'Q695'} , 
    'Panama' : { 'label': 'بنما', 'Q': 'Q804'} , 
    'Paraguay' : { 'label': 'باراغواي', 'Q': 'Q733'} , 
    'Peru' : { 'label': 'بيرو', 'Q': 'Q419'} , 
    'Pilipinas' : { 'label': 'الفلبين', 'Q': 'Q928'} , 
    'Polonya' : { 'label': 'بولندا', 'Q': 'Q36'} , 
    'Portugal' : { 'label': 'البرتغال', 'Q': 'Q45'} , 
    'Pransiya' : { 'label': 'فرنسا', 'Q': 'Q142'} , 
    'Republika_sa_Congo' : { 'label': 'جمهورية الكونغو', 'Q': 'Q971'} , 
    'Republika_sa_Tsina' : { 'label': 'تايوان', 'Q': 'Q865'} , 
    'Republikang_Demokratiko_sa_Congo' : { 'label': 'جمهورية الكونغو الديمقراطية', 'Q': 'Q974'} , 
    'Republikang_Dominikano' : { 'label': 'جمهورية الدومينيكان', 'Q': 'Q786'} , 
    'Republikang_Popular_sa_Tsina' : { 'label': 'الصين', 'Q': 'Q148'} , 
    'Republikang_Sentral_Aprikano' : { 'label': 'جمهورية أفريقيا الوسطى', 'Q': 'Q929'} , 
    'Rumanya' : { 'label': 'رومانيا', 'Q': 'Q218'} , 
    'Rusya' : { 'label': 'روسيا', 'Q': 'Q159'} , 
    'Samoa' : { 'label': 'ساموا', 'Q': 'Q683'} , 
    'Senegal' : { 'label': 'السنغال', 'Q': 'Q1041'} , 
    'Serbya' : { 'label': 'صربيا', 'Q': 'Q403'} , 
    'Seychelles' : { 'label': 'سيشل', 'Q': 'Q1042'} , 
    'Sidlakang_Timor' : { 'label': 'تيمور الشرقية', 'Q': 'Q574'} , 
    'Sierra_Leone' : { 'label': 'سيراليون', 'Q': 'Q1044'} , 
    'Singgapura' : { 'label': 'سنغافورة', 'Q': 'Q334'} , 
    'Sint_Maarten' : { 'label': 'سينت مارتن', 'Q': 'Q26273'} , 
    'Siria' : { 'label': 'سوريا', 'Q': 'Q858'} , 
    'Somalia' : { 'label': 'الصومال', 'Q': 'Q1045'} , 
    'Sri_Lanka' : { 'label': 'سريلانكا', 'Q': 'Q854'} , 
    'Sudan' : { 'label': 'السودان', 'Q': 'Q1049'} , 
    'Surinam' : { 'label': 'سورينام', 'Q': 'Q730'} , 

    'Suwasilandiya' : { 'label': 'سوازيلاند', 'Q': 'Q1050'} , 
    'Suwesya' : { 'label': 'السويد', 'Q': 'Q34'} , 
    'Habagatang_Aprika' : { 'label': 'جنوب أفريقيا', 'Q': 'Q258'} , 
    'Habagatang_Korea' : { 'label': 'كوريا الجنوبية', 'Q': 'Q884'} , 
    'Habagatang_Sudan' : { 'label': 'جنوب السودان', 'Q': 'Q958'} , 
    'Haiti' : { 'label': 'هايتي', 'Q': 'Q790'} , 
    'Hapon' : { 'label': 'اليابان', 'Q': 'Q17'} , 
    'Hiniusang_Emiratong_Arabo' : { 'label': 'الإمارات العربية المتحدة', 'Q': 'Q878'} , 
    'Hiniusang_Gingharian' : { 'label': 'المملكة المتحدة', 'Q': 'Q145'} , 
    'Honduras' : { 'label': 'هندوراس', 'Q': 'Q783'} , 
    'Hordanya' : { 'label': 'الأردن', 'Q': 'Q810'} , 
    'Indonesia' : { 'label': 'إندونيسيا', 'Q': 'Q252'} , 
    'Indya' : { 'label': 'الهند', 'Q': 'Q668'} , 
    'Iran' : { 'label': 'إيران', 'Q': 'Q794'} , 
    'Iraq' : { 'label': 'العراق', 'Q': 'Q796'} , 
    'Islandya' : { 'label': 'آيسلندا', 'Q': 'Q189'} , 
    'Litwanya' : { 'label': 'ليتوانيا', 'Q': 'Q37'} , 
    'Luksemburgo' : { 'label': 'لوكسمبورغ', 'Q': 'Q32'} , 
    'Macao' : { 'label': 'ماكاو', 'Q': 'Q14773'} , 
    'Macedonia' : { 'label': 'جمهورية مقدونيا', 'Q': 'Q221'} , 
    'Madagascar' : { 'label': 'مدغشقر', 'Q': 'Q1019'} , 
    'Malasya' : { 'label': 'ماليزيا', 'Q': 'Q833'} , 
    'Malawi' : { 'label': 'ملاوي', 'Q': 'Q1020'} , 
    'Mali' : { 'label': 'مالي', 'Q': 'Q912'} , 
    'Malta' : { 'label': 'مالطا', 'Q': 'Q233'} , 
    'Maruwekos' : { 'label': 'المغرب', 'Q': 'Q1028'} , 
    'Maurisyo' : { 'label': 'موريشيوس', 'Q': 'Q1027'} , 
    'Mauritania' : { 'label': 'موريتانيا', 'Q': 'Q1025'} , 
    'Israel' : { 'label': 'إسرائيل', 'Q': 'Q801'} , 
    'Italya' : { 'label': 'إيطاليا', 'Q': 'Q38'} , 
    'Jamaica' : { 'label': 'جامايكا', 'Q': 'Q766'} , 
    'Jersey' : { 'label': 'جيرزي', 'Q': 'Q785'} , 
    'Kamboya' : { 'label': 'كمبوديا', 'Q': 'Q424'} , 
    'Kamerun' : { 'label': 'الكاميرون', 'Q': 'Q1009'} , 
    'Kasahistan' : { 'label': 'كازاخستان', 'Q': 'Q232'} , 
    'Katar' : { 'label': 'قطر', 'Q': 'Q846'} , 
    'Kenya' : { 'label': 'كينيا', 'Q': 'Q114'} , 
    'Kirgistan' : { 'label': 'قيرغيزستان', 'Q': 'Q813'} , 
    'Kiribati' : { 'label': 'كيريباتي', 'Q': 'Q710'} , 
    'Kosobo' : { 'label': 'كوسوفو', 'Q': 'Q1246'} , 
    'Krowasya' : { 'label': 'كرواتيا', 'Q': 'Q224'} , 
    'Kuwait' : { 'label': 'الكويت', 'Q': 'Q817'} , 
    'Laos' : { 'label': 'لاوس', 'Q': 'Q819'} , 
    'Latvia' : { 'label': 'لاتفيا', 'Q': 'Q211'} , 
    'Lesotho' : { 'label': 'ليسوتو', 'Q': 'Q1013'} , 
    'Libano' : { 'label': 'لبنان', 'Q': 'Q822'} , 
    'Liberya' : { 'label': 'ليبيريا', 'Q': 'Q1014'} , 
    'Libya' : { 'label': 'ليبيا', 'Q': 'Q1016'} , 
    'Liechtenstein' : { 'label': 'ليختنشتاين', 'Q': 'Q347'} , 
        }
ContriesTable = {
    "PW" : {"item" : "Q695", "ar" : "بالاو"} , 
    "GD" : {"item" : "Q769", "ar" : "غرينادا"} , 
    "FR" : {"item" : "Q142", "ar" : "فرنسا"} , 
    "GN" : {"item" : "Q1006", "ar" : "غينيا"} , 
    "PF" : {"item" : "Q142", "ar" : "فرنسا"} , 
    #"PF" : {"item" : "Q30971", "ar" : "بولينزيا الفرنسية"} , 
    "YT" : {"item" : "Q17063", "ar" : "مايوت"} , 
    "HU" : {"item" : "Q28", "ar" : "المجر"} , 
    "TZ" : {"item" : "Q924", "ar" : "تنزانيا"} , 
    "SG" : {"item" : "Q334", "ar" : "سنغافورة"} , 
    "MF" : {"item" : "Q126125", "ar" : "تجمع سان مارتين"} , 
    "PY" : {"item" : "Q733", "ar" : "باراغواي"} , 
    "FI" : {"item" : "Q33", "ar" : "فنلندا"} , 
    "DO" : {"item" : "Q786", "ar" : "جمهورية الدومينيكان"} , 
    "ZM" : {"item" : "Q953", "ar" : "زامبيا"} , 
    "MX" : {"item" : "Q96", "ar" : "المكسيك"} , 
    "CL" : {"item" : "Q298", "ar" : "تشيلي"} , 
    "CW" : {"item" : "Q25279", "ar" : "كوراساو"} , 
    "CY" : {"item" : "Q229", "ar" : "قبرص"} , 
    "CU" : {"item" : "Q241", "ar" : "كوبا"} , 
    "AX" : {"item" : "Q33", "ar" : "فنلندا"} , 
    "LY" : {"item" : "Q1016", "ar" : "ليبيا"} , 
    #"GF" : {"item" : "Q3769", "ar" : "غويانا الفرنسية"} , 
    "GF" : {"item" : "Q142", "ar" : "فرنسا"} , 
    "AR" : {"item" : "Q414", "ar" : "الأرجنتين"} , 
    "SE" : {"item" : "Q34", "ar" : "السويد"} , 
    "PA" : {"item" : "Q804", "ar" : "بنما"} , 
    "LV" : {"item" : "Q211", "ar" : "لاتفيا"} , 
    "BY" : {"item" : "Q2895", "ar" : "جمهورية بيلاروس السوفيتية الاشتراكية"} , 
    "CF" : {"item" : "Q929", "ar" : "جمهورية أفريقيا الوسطى"} , 
    "NU" : {"item" : "Q34020", "ar" : "نييوي"} , 
    "NA" : {"item" : "Q1030", "ar" : "ناميبيا"} , 
    "YU" : {"item" : "Q838261", "ar" : "جمهورية يوغوسلافيا الاتحادية"} , 
    "JP" : {"item" : "Q17", "ar" : "اليابان"} , 
    "SB" : {"item" : "Q685", "ar" : "جزر سليمان"} , 
    "BI" : {"item" : "Q967", "ar" : "بوروندي"} , 
    "ST" : {"item" : "Q1039", "ar" : "ساو تومي وبرينسيب"} , 
    "BJ" : {"item" : "Q962", "ar" : "بنين"} , 
    "LC" : {"item" : "Q760", "ar" : "سانت لوسيا"} , 
    "AF" : {"item" : "Q889", "ar" : "أفغانستان"} , 
    "BZ" : {"item" : "Q242", "ar" : "بليز"} , 
    "AU" : {"item" : "Q408", "ar" : "أستراليا"} , 
    "TL" : {"item" : "Q574", "ar" : "تيمور الشرقية"} , 
    "TH" : {"item" : "Q869", "ar" : "تايلاند"} , 
    "LI" : {"item" : "Q347", "ar" : "ليختنشتاين"} , 
    "TC" : {"item" : "Q145", "ar" : "المملكة المتحدة"} , 
    #"HM" : {"item" : "Q131198", "ar" : "جزيرة هيرد وجزر ماكدونالد"} , 
    "HM" : {"item" : "Q408", "ar" : "أستراليا"} , 
    "TT" : {"item" : "Q754", "ar" : "ترينيداد وتوباغو"} , 
    "LU" : {"item" : "Q32", "ar" : "لوكسمبورغ"} , 
    "GI" : {"item" : "Q1410", "ar" : "جبل طارق"} , 
    "UA" : {"item" : "Q212", "ar" : "أوكرانيا"} , 
    "RE" : {"item" : "Q17070", "ar" : "ريونيون"} , 
    "TV" : {"item" : "Q672", "ar" : "توفالو"} , 
    "OM" : {"item" : "Q842", "ar" : "سلطنة عمان"} , 
    "PE" : {"item" : "Q419", "ar" : "بيرو"} , 
    "BO" : {"item" : "Q750", "ar" : "بوليفيا"} , 
    "TM" : {"item" : "Q874", "ar" : "تركمانستان"} , 
    "SK" : {"item" : "Q214", "ar" : "سلوفاكيا"} , 
    "SA" : {"item" : "Q851", "ar" : "المملكة العربية السعودية"} , 
    "KR" : {"item" : "Q884", "ar" : "كوريا الجنوبية"} , 
    "SC" : {"item" : "Q1042", "ar" : "سيشل"} , 
    "GR" : {"item" : "Q41", "ar" : "اليونان"} , 
    "JE" : {"item" : "Q785", "ar" : "جيرزي"} , 
    "AL" : {"item" : "Q222", "ar" : "ألبانيا"} , 
    "GT" : {"item" : "Q774", "ar" : "غواتيمالا"} , 
    "GA" : {"item" : "Q1000", "ar" : "الغابون"} , 
    "IO" : {"item" : "Q145", "ar" : "المملكة المتحدة"} , 
    "UY" : {"item" : "Q77", "ar" : "الأوروغواي"} , 
    "JM" : {"item" : "Q766", "ar" : "جامايكا"} , 
    "MO" : {"item" : "Q14773", "ar" : "ماكاو"} , 
    "GP" : {"item" : "Q17012", "ar" : "غوادلوب"} , 
    "TK" : {"item" : "Q36823", "ar" : "توكيلاو"} , 
    "CO" : {"item" : "Q739", "ar" : "كولومبيا"} , 
    "BT" : {"item" : "Q917", "ar" : "بوتان"} , 
    "DK" : {"item" : "Q35", "ar" : "الدنمارك"} , 
    "MR" : {"item" : "Q1025", "ar" : "موريتانيا"} , 
    "SX" : {"item" : "Q26273", "ar" : "سينت مارتن"} , 
    "VU" : {"item" : "Q686", "ar" : "فانواتو"} , 
    "CM" : {"item" : "Q1009", "ar" : "الكاميرون"} , 
    "TR" : {"item" : "Q43", "ar" : "تركيا"} , 
    "MG" : {"item" : "Q1019", "ar" : "مدغشقر"} , 
    "ME" : {"item" : "Q236", "ar" : "الجبل الأسود"} , 
    "PT" : {"item" : "Q45", "ar" : "البرتغال"} , 
    "SD" : {"item" : "Q1049", "ar" : "السودان"} , 
    "IM" : {"item" : "Q9676", "ar" : "جزيرة مان"} , 
    "SI" : {"item" : "Q215", "ar" : "سلوفينيا"} , 
    "MD" : {"item" : "Q217", "ar" : "مولدافيا"} , 
    "RW" : {"item" : "Q1037", "ar" : "رواندا"} , 
    "ES" : {"item" : "Q29", "ar" : "إسبانيا"} , 
    "DM" : {"item" : "Q784", "ar" : "دومينيكا"} , 
    "CI" : {"item" : "Q1008", "ar" : "ساحل العاج"} , 
    "GL" : {"item" : "Q223", "ar" : "غرينلاند"} , 
    "BR" : {"item" : "Q155", "ar" : "البرازيل"} , 
    "SR" : {"item" : "Q730", "ar" : "سورينام"} , 
    "GB" : {"item" : "Q145", "ar" : "المملكة المتحدة"} , 
    "MK" : {"item" : "Q221", "ar" : "جمهورية مقدونيا"} , 
    "CA" : {"item" : "Q16", "ar" : "كندا"} , 
    "JO" : {"item" : "Q810", "ar" : "الأردن"} , 
    "AI" : {"item" : "Q25228", "ar" : "أنغويلا"} , 
    "HK" : {"item" : "Q8646", "ar" : "هونغ كونغ"} , 
    "AE" : {"item" : "Q878", "ar" : "الإمارات العربية المتحدة"} , 
    "EH" : {"item" : "Q6250", "ar" : "الصحراء الغربية"} , 
    "HR" : {"item" : "Q224", "ar" : "كرواتيا"} , 
    "NL" : {"item" : "Q55", "ar" : "هولندا"} , 
    "VG" : {"item" : "Q145", "ar" : "المملكة المتحدة"} , 
    "AZ" : {"item" : "Q227", "ar" : "أذربيجان"} , 
    "HN" : {"item" : "Q783", "ar" : "هندوراس"} , 
    "CZ" : {"item" : "Q213", "ar" : "التشيك"} , 
    "AT" : {"item" : "Q40", "ar" : "النمسا"} , 
    "MT" : {"item" : "Q233", "ar" : "مالطا"} , 
    "BS" : {"item" : "Q778", "ar" : "باهاماس"} , 
    "RS" : {"item" : "Q403", "ar" : "صربيا"} , 
    "IS" : {"item" : "Q189", "ar" : "آيسلندا"} , 
    "FJ" : {"item" : "Q712", "ar" : "فيجي"} , 
    "PL" : {"item" : "Q36", "ar" : "بولندا"} , 
    "EE" : {"item" : "Q191", "ar" : "إستونيا"} , 
    #"TF" : {"item" : "Q129003", "ar" : "أراض فرنسية جنوبية وأنتارتيكية"} , 
    "TF" : {"item" : "Q142", "ar" : "فرنسا"} , 
    "LR" : {"item" : "Q1014", "ar" : "ليبيريا"} , 
    "BG" : {"item" : "Q219", "ar" : "بلغاريا"} , 
    #"PS" : {"item" : "Q407199", "ar" : "الضفة الغربية وقطاع غزة"} , 
    "PS" : {"item" : "Q219060", "ar" : "فلسطين"} , 
    "GY" : {"item" : "Q734", "ar" : "غيانا"} , 
    "KG" : {"item" : "Q813", "ar" : "قيرغيزستان"} , 
    "BV" : {"item" : "Q23408", "ar" : "جزيرة بوفيه"} , 
    "KN" : {"item" : "Q763", "ar" : "سانت كيتس ونيفيس"} , 
    "DD" : {"item" : "Q16957", "ar" : "ألمانيا الشرقية"} , 
    "MV" : {"item" : "Q826", "ar" : "جزر المالديف"} , 
    "MM" : {"item" : "Q836", "ar" : "ميانمار"} , 
    "MA" : {"item" : "Q1028", "ar" : "المغرب"} , 
    "ET" : {"item" : "Q115", "ar" : "إثيوبيا"} , 
    "SV" : {"item" : "Q792", "ar" : "السلفادور"} , 
    "LT" : {"item" : "Q37", "ar" : "ليتوانيا"} , 
    "NG" : {"item" : "Q1033", "ar" : "نيجيريا"} , 
    "RO" : {"item" : "Q218", "ar" : "رومانيا"} , 
    "GE" : {"item" : "Q230", "ar" : "جورجيا"} , 
    "KY" : {"item" : "Q5785", "ar" : "جزر كايمان"} , 
    "NP" : {"item" : "Q837", "ar" : "نيبال"} , 
    "NR" : {"item" : "Q697", "ar" : "ناورو"} , 
    "VE" : {"item" : "Q717", "ar" : "فنزويلا"} , 
    "KI" : {"item" : "Q710", "ar" : "كيريباتي"} , 
    "LS" : {"item" : "Q1013", "ar" : "ليسوتو"} , 
    "LK" : {"item" : "Q854", "ar" : "سريلانكا"} , 
    "YE" : {"item" : "Q805", "ar" : "اليمن"} , 
    "VN" : {"item" : "Q881", "ar" : "فيتنام"} , 
    "EG" : {"item" : "Q79", "ar" : "مصر"} , 
    "BH" : {"item" : "Q398", "ar" : "البحرين"} , 
    "GG" : {"item" : "Q25230", "ar" : "غيرنزي"} , 
    "XK" : {"item" : "Q1246", "ar" : "كوسوفو"} , 
    "PR" : {"item" : "Q1183", "ar" : "بورتوريكو"} , 
    "UZ" : {"item" : "Q265", "ar" : "أوزبكستان"} , 
    "CX" : {"item" : "Q31063", "ar" : "جزيرة عيد الميلاد"} , 
    "MP" : {"item" : "Q16644", "ar" : "جزر ماريانا الشمالية"} , 
    "IT" : {"item" : "Q38", "ar" : "إيطاليا"} , 
    "BQ" : {"item" : "Q55", "ar" : "هولندا"} , 
    "NF" : {"item" : "Q31057", "ar" : "جزيرة نورفولك"} , 
    "SJ" : {"item" : "Q842829", "ar" : "سفالبارد ويان ماين"} , 
    "QA" : {"item" : "Q846", "ar" : "قطر"} , 
    "LA" : {"item" : "Q819", "ar" : "لاوس"} , 
    "DJ" : {"item" : "Q977", "ar" : "جيبوتي"} , 
    "SS" : {"item" : "Q958", "ar" : "جنوب السودان"} , 
    "FO" : {"item" : "Q4628", "ar" : "جزر فارو"} , 
    "BN" : {"item" : "Q921", "ar" : "بروناي"} , 
    "IL" : {"item" : "Q801", "ar" : "إسرائيل"} , 
    "BB" : {"item" : "Q244", "ar" : "باربادوس"} , 
    "SN" : {"item" : "Q1041", "ar" : "السنغال"} , 
    "AQ" : {"item" : "Q21590062", "ar" : "منطقة معاهدة القطب الجنوبي"} , 
    "DE" : {"item" : "Q183", "ar" : "ألمانيا"} , 
    "CG" : {"item" : "Q971", "ar" : "جمهورية الكونغو"} , 
    "LB" : {"item" : "Q822", "ar" : "لبنان"} , 
    "NO" : {"item" : "Q20", "ar" : "النرويج"} , 
    "TD" : {"item" : "Q657", "ar" : "تشاد"} , 
    "AG" : {"item" : "Q781", "ar" : "أنتيغوا وباربودا"} , 
    "ZW" : {"item" : "Q954", "ar" : "زيمبابوي"} , 
    "UM" : {"item" : "Q30", "ar" : "الولايات المتحدة الأمريكية"} , 
    "AM" : {"item" : "Q399", "ar" : "أرمينيا"} , 
    "CD" : {"item" : "Q974", "ar" : "جمهورية الكونغو الديمقراطية"} , 
    "NZ" : {"item" : "Q664", "ar" : "نيوزيلندا"} , 
    #"AN" : {"item" : "Q25227", "ar" : "جزر الأنتيل الهولندية"} , 
    "AN" :{"item" : "Q55", "ar" : "هولندا"} ,  
    "US" : {"item" : "Q30", "ar" : "الولايات المتحدة الأمريكية"} , 
    "MY" : {"item" : "Q833", "ar" : "ماليزيا"} , 
    "SY" : {"item" : "Q858", "ar" : "سوريا"} , 
    "CS" : {"item" : "Q37024", "ar" : "صربيا والجبل الأسود"} , 
    "DZ" : {"item" : "Q262", "ar" : "الجزائر"} , 
    "AS" : {"item" : "Q30", "ar" : "الولايات المتحدة الأمريكية"} , 
    "PH" : {"item" : "Q928", "ar" : "الفلبين"} , 
    "GM" : {"item" : "Q1005", "ar" : "غامبيا"} , 
    #"SH" : {"item" : "Q192184", "ar" : "جزر سانت هيلينا وأسينشين وتريستان دا كونا"} , 
    "SH" : {"item" : "Q145", "ar" : "المملكة المتحدة"} , 
    "FM" : {"item" : "Q702", "ar" : "ولايات ميكرونيسيا المتحدة"} , 
    "TN" : {"item" : "Q948", "ar" : "تونس"} , 
    "KZ" : {"item" : "Q232", "ar" : "كازاخستان"} , 
    "MZ" : {"item" : "Q1029", "ar" : "موزمبيق"} , 
    "FK" : {"item" : "Q9648", "ar" : "جزر فوكلاند"} , 
    "ID" : {"item" : "Q252", "ar" : "إندونيسيا"} , 
    "TJ" : {"item" : "Q863", "ar" : "طاجيكستان"} , 
    "CR" : {"item" : "Q800", "ar" : "كوستاريكا"} , 
    "MN" : {"item" : "Q711", "ar" : "منغوليا"} , 
    "PN" :  {"item" : "Q145", "ar" : "المملكة المتحدة"} , #{"item" : "Q35672", "ar" : "جزر بيتكيرن"} , 
    "UG" : {"item" : "Q1036", "ar" : "أوغندا"} , 
    "CN" : {"item" : "Q148", "ar" : "الصين"} , 
    #"CC" : {"item" : "Q36004", "ar" : "جزر كوكس"} , 
    "CC" : {"item" : "Q408", "ar" : "أستراليا"} , 
    "SL" : {"item" : "Q1044", "ar" : "سيراليون"} , 
    "BM" : {"item" : "Q145", "ar" : "المملكة المتحدة"} ,# {"item" : "Q23635", "ar" : "جزر برمودا"} , 
    "CK" : {"item" : "Q26988", "ar" : "جزر كوك"} , 
    "HT" : {"item" : "Q790", "ar" : "هايتي"} , 
    "GH" : {"item" : "Q117", "ar" : "غانا"} , 
    "VA" : {"item" : "Q237", "ar" : "الفاتيكان"} , 
    "MQ" : {"item" : "Q17054", "ar" : "مارتينيك"} , 
    "CH" : {"item" : "Q39", "ar" : "سويسرا"} , 
    "GW" : {"item" : "Q1007", "ar" : "غينيا بيساو"} , 
    "BA" : {"item" : "Q225", "ar" : "البوسنة والهرسك"} , 
    "KH" : {"item" : "Q424", "ar" : "كمبوديا"} , 
    "KM" : {"item" : "Q970", "ar" : "جزر القمر"} , 
    "MS" : {"item" : "Q13353", "ar" : "مونتسرات"} , 
    "MU" : {"item" : "Q1027", "ar" : "موريشيوس"} , 
    "MH" : {"item" : "Q709", "ar" : "جزر مارشال"} , 
    "NE" : {"item" : "Q1032", "ar" : "النيجر"} , 
    "TO" : {"item" : "Q678", "ar" : "تونغا"} , 
    "KP" : {"item" : "Q423", "ar" : "كوريا الشمالية"} , 
    "BF" : {"item" : "Q965", "ar" : "بوركينا فاسو"} , 
    "VC" : {"item" : "Q757", "ar" : "سانت فينسنت والغرينادين"} , 
    "ML" : {"item" : "Q912", "ar" : "مالي"} , 
    "AW" : {"item" : "Q21203", "ar" : "أروبا"} , 
    "BL" : {"item" : "Q25362", "ar" : "سان بارتيلمي"} , 
    "BE" : {"item" : "Q31", "ar" : "بلجيكا"} , 
    "ER" : {"item" : "Q986", "ar" : "إريتريا"} , 
    "NC" : {"item" : "Q33788", "ar" : "كاليدونيا الجديدة"} , 
    "AD" : {"item" : "Q228", "ar" : "أندورا"} , 
    "SM" : {"item" : "Q238", "ar" : "سان مارينو"} , 
    "MC" : {"item" : "Q235", "ar" : "موناكو"} , 
    "EC" : {"item" : "Q736", "ar" : "الإكوادور"} , 
    "GU" : {"item" : "Q16635", "ar" : "غوام"} , 
    "SZ" : {"item" : "Q1050", "ar" : "سوازيلاند"} , 
    "KW" : {"item" : "Q817", "ar" : "الكويت"} , 
    "IE" : {"item" : "Q27", "ar" : "جمهورية أيرلندا"} , 
    "IN" : {"item" : "Q668", "ar" : "الهند"} , 
    "AO" : {"item" : "Q916", "ar" : "أنغولا"} , 
    "CV" : {"item" : "Q1011", "ar" : "الرأس الأخضر"} , 
    "IR" : {"item" : "Q794", "ar" : "إيران"} , 
    "NI" : {"item" : "Q811", "ar" : "نيكاراغوا"} , 
    "IQ" : {"item" : "Q796", "ar" : "العراق"} , 
    "PM" : {"item" : "Q34617", "ar" : "سان بيير وميكلون"} , 
    "VI" : {"item" : "Q30", "ar" : "الولايات المتحدة الأمريكية"} , 
    "TG" : {"item" : "Q945", "ar" : "توغو"} , 
    "WF" : {"item" : "Q35555", "ar" : "واليس وفوتونا"} , 
    "RU" : {"item" : "Q159", "ar" : "روسيا"} , 
    "WS" : {"item" : "Q683", "ar" : "ساموا"} , 
    "PK" : {"item" : "Q843", "ar" : "باكستان"} , 
    "KE" : {"item" : "Q114", "ar" : "كينيا"} , 
    "TW" : {"item" : "Q865", "ar" : "تايوان"} , 
    "BW" : {"item" : "Q963", "ar" : "بوتسوانا"} , 
    "MW" : {"item" : "Q1020", "ar" : "مالاوي"} , 
    "BD" : {"item" : "Q902", "ar" : "بنغلاديش"} , 
    #"GS" : {"item" : "Q35086", "ar" : "جورجيا الجنوبية وجزر ساندويتش الجنوبية"} , 
    "GS" :  {"item" : "Q145", "ar" : "المملكة المتحدة"} ,
    "PG" : {"item" : "Q691", "ar" : "بابوا غينيا الجديدة"} , 
    "ZA" : {"item" : "Q258", "ar" : "جنوب أفريقيا"} , 
    "GQ" : {"item" : "Q983", "ar" : "غينيا الاستوائية"} , 
    "SO" : {"item" : "Q1045", "ar" : "الصومال"} , 
    }
