many_lang_qid_desc = {
    "Q11173": {
        "af": "chemiese verbinding",
        "an": "compuesto quimico",
        "ru": "химическое соединение",
        "ar": "مركب كيميائي",
        "ast": "compuestu químicu",
        "bn": "রাসায়নিক যৌগ",
        "ca": "compost químic",
        "cs": "chemická sloučenina",
        "da": "kemisk forbindelse",
        "de": "chemische Verbindung",
        "en": "chemical compound",
        "sl": "kemična spojina",
        "eo": "kemia kombinaĵo",
        "es": "compuesto químico",
        "eu": "konposatu kimiko",
        "fi": "kemiallinen yhdiste",
        "fr": "composé chimique",
        "gl": "composto químico",
        "he": "תרכובת",
        "hr": "kemijski spoj",
        "hy": "քիմիական միացություն",
        "id": "senyawa kimia",
        "it": "composto chimico",
        "la": "compositum chemicum",
        "lb": "cheemesch Verbindung",
        "lv": "ķīmisks savienojums",
        "nb": "kjemisk forbindelse",
        "nl": "chemische verbinding",
        "nn": "kjemisk sambinding",
        "oc": "component quimic",
        "pl": "związek chemiczny",
        "pt": "composto químico",
        "pt-br": "composto químico",
        "ro": "compus chimic",
        "sk": "chemická zlúčenina",
        "sq": "komponim kimik",
        "tg-cyrl": "пайвастагии химиявӣ",
        "tg-latn": "payvastagii khimiyaviy",
    },
    "Q6979593": {  # national association football team
        "ar": "منتخب كرة قدم وطني",
        "sl": "nacionalna nogometna reprezentanca",
        "en": "national association football team",
        "hr": "nacionalna nogometna reprezentacija",
        "nl": "nationaal voetbalteam",
        "tg-cyrl": "ассотсиатсияи миилии бошгоҳи футбол",
        "tg-latn": "assotsiatsiyoi millie boshgohe futbol",
    },
    "Q24856": {  # film series
        "ar": "سلسلة أفلام",
        "sl": "filmska serija",
        "en": "film series",
        "tg-cyrl": "силсилаи филмҳо",
        "tg-latn": "silsilai filmho",
    },
    "Q15184295": {  # Wikimedia module
        "ar": "وحدة ويكيميديا",
        "bg": "Уикимедия модул",
        "en": "Wikimedia module",
        "fr": "Module Wikimedia",
        "he": "יחידה של ויקימדיה",
        "hr": "modul za wikimedije",
        "ilo": "Modulo ti lua",
        "ko": "위키미디어 루아 모듈",
        "lb": "Wikimedia-Modul",
        "nl": "Wikimedia-module",
        "pl": "moduł Lua",
        "sl": "modul Wikimedie",
        "tg-cyrl": "модули Викимедиа",
        "tg-latn": "moduli Vikimediya",
        "vi": "mô đun Lua",
    },
    "Q1013520000000000000000000000000000": {  # family name # Q1013520
        "af": "van",
        "an": "apelliu",
        "ar": "اسم العائلة",
        "ast": "apellíu",
        "az": "soyadı",
        "bar": "Schreibnam",
        "be": "прозвішча",
        "be-tarask": "прозьвішча",
        "bg": "презиме",
        "bn": "পারিবারিক নাম",
        "br": "anv-tiegezh",
        "bs": "prezime",
        "ca": "cognom",
        "crh": "soyadı",
        "cs": "příjmení",
        "csb": "nôzwëskò",
        "cv": "хушамат",
        "cy": "cyfenw",
        "da": "efternavn",
        "de": "Familienname",
        "el": "επώνυμο",
        "en": "family name",
        "en-gb": "surname",
        "eo": "familia nomo",
        "es": "apellido",
        "et": "perekonnanimi",
        "eu": "abizen",
        "fa": "نام خانوادگی",
        "fi": "sukunimi",
        "fit": "sukunimi",
        "fo": "ættarnavn",
        "fr": "nom de famille",
        "fy": "efternamme",
        "ga": "sloinne",
        "gan": "姓氏箋釋",
        "gan-hans": "姓氏笺释",
        "gan-hant": "姓氏箋釋",
        "gd": "sloinneadh",
        "gl": "apelido",
        "gsw": "Familiename",
        "gu": "અટક",
        "gv": "sliennoo",
        "he": "שם משפחה",
        "hi": "उपनाम",
        "hr": "prezime",
        "hu": "családnév",  # [[Topic:Y4mda8gast0i6t9o]] "hu": "vezetéknév",
        "hy": "ազգանուն",
        "id": "nama keluarga",
        "ig": "ahà nnà",
        "io": "surnomo",
        "is": "eftirnafn",
        "it": "cognome",
        "ja": "姓",
        "jut": "efternavn",
        "jv": "jeneng pancer",
        "ka": "გვარი",
        "kk": "тек, ата-тек, әулет есім",
        "kk-cyrl": "тек, ата-тек, әулет есім",
        "kk-latn": "tek, ata-tek, äwlet esim",
        "kk-kz": "тек, ата-тек, әулет есім",
        "kk-tr": "tek, ata-tek, äwlet esim",
        "ko": "성씨",
        "ksh": "Nohnahme",
        "kw": "hanow",
        "la": "nomen gentilicium",
        "lad": "alkunya",
        "lb": "Familljennumm",
        "lt": "pavardė",
        "lv": "uzvārds",
        "lzh": "姓氏",
        "mhr": "тукымлӱм",
        "mi": "ingoa whānau",
        "min": "namo asli",
        "mk": "презиме",
        "mn": "овог нэр",
        "ms": "nama keluarga",
        "mt": "kunjom",
        "nb": "etternavn",
        "nds": "Familiennaam",
        "ne": "थर",
        "new": "उपनां",
        "nl": "familienaam",
        "nn": "etternamn",
        "oc": "nom d’ostal",
        "or": "ସାଙ୍ଗିଆ",
        "os": "мыггаг",
        "pl": "nazwisko",
        "pms": "cognòm",
        "pt": "sobrenome",
        "pt-br": "nome de familia",
        "ro": "nume de familie",
        "ru": "фамилия",
        "rue": "прузвище",
        "sco": "faimily name",
        "se": "goargu",
        "sh": "prezime",
        "sje": "maŋŋepnamma",
        "sk": "priezvisko",
        "sl": "priimek",
        "sma": "fuelhkienomme",
        "smj": "maŋepnamma",
        "smn": "suhânommâ",
        "sn": "Mazita eMhuri",
        "sq": "mbiemër",
        "sr": "презиме",
        "sr-ec": "презиме",
        "sr-el": "prezime",
        "sv": "efternamn",
        "sw": "jina la ukoo",
        "ta": "குடும்பப் பெயர்",
        "te": "ఇంటి పేర్లు",
        "tg": "насаб",
        "tg-cyrl": "насаб",
        "tg-latn": "nasab",
        "th": "นามสกุล",
        "tl": "apelyido",
        "tr": "soyadı",  # Topic:V9p2mhq3iro7lp6y
        "uk": "прізвище",
        "uz": "familiya",
        "vi": "họ",
        "wa": "no d’ famile",
        "war": "apelyidu",
        "xh": "ifani",
        "yi": "פֿאַמיליע נאָמען",
        "yue": "姓",
        "zh": "姓氏",
        "zh-cn": "姓氏",
        "zh-hans": "姓氏",
        "zh-hant": "姓氏",
        "zh-hk": "姓氏",
        "zh-mo": "姓氏",
        "zh-my": "姓氏",
        "zh-sg": "姓氏",
        "zh-tw": "姓氏",
        "zu": "isibongo",
    },
    "Q11879590": {  # female given name
        "af": "vroulike voornaam",
        "ar": "اسم مؤنث معطى",
        "ast": "nome femenín",
        "bar": "Weiwanam",
        "be": "жаночае асабістае імя",
        "be-tarask": "жаночае асабовае імя",
        "bg": "женско собствено име",
        "bn": "প্রদত্ত মহিলা নাম",
        "br": "anv merc’hed",
        "bs": "žensko ime",
        "ca": "prenom femení",
        "ce": "зудчун шен цӀе",
        "cs": "ženské křestní jméno",
        "cy": "enw personol benywaidd",
        "da": "pigenavn",
        "de": "weiblicher Vorname",
        "el": "γυναικείο όνομα",
        "en": "female given name",
        "eo": "virina persona nomo",
        "es": "nombre femenino",
        "et": "naisenimi",
        "eu": "emakumezko izena",
        "fa": "نام‌های زنانه",
        "fi": "naisen etunimi",
        "fr": "prénom féminin",
        "fy": "famkesnamme",
        "gl": "nome feminino",
        "he": "שם פרטי של אישה",
        "hr": "žensko ime",
        "hsb": "žónske předmjeno",
        "hu": "női utónév",  # [[Topic:Y4mda8gast0i6t9o]] # "hu": "női keresztnév",
        "hy": "իգական անձնանուն",
        "id": "nama perempuan feminin",
        "is": "kvenmannsnafn",
        "it": "prenome femminile",
        "ja": "女性の名前",
        "ko": "여성의 이름",
        "la": "praenomen femininum",
        "lb": "weibleche Virnumm",
        "lt": "moteriškas vardas",
        "lv": "sieviešu personvārds",
        "mk": "женско лично име",
        "nb": "kvinnenavn",
        "ne": "स्त्रीलिङ्गी नाम",
        "nl": "vrouwelijke voornaam",
        "nn": "kvinnenamn",
        "pl": "imię żeńskie",
        "pt": "nome próprio feminino",
        "pt-br": "nome próprio feminino",
        "ro": "prenume feminin",
        "ru": "женское личное имя",
        "sr": "женско лично име",
        "sr-ec": "женско лично име",
        "scn": "nomu di battìu fimmininu",
        "sco": "female gien name",
        "sk": "ženské krstné meno",
        "sl": "žensko osebno ime",
        "smn": "nissoon ovdânommâ",
        "sq": "emër femëror",
        "sr-el": "žensko lično ime",
        "sv": "kvinnonamn",
        "sw": "jina la mwanamke",
        "ta": "பெண்களுக்கு சூட்டிய பெயர்",
        "tg": "номи шахсии занона",
        "th": "ชื่อผู้หญิง",
        "tr": "kadın adı",  # # "tr":"kadın ismidir", Topic:V9p2mhq3iro7lp6y
        "uk": "жіноче особове ім’я",
        "yue": "女人名",
        "zh": "女性人名",
        "zh-cn": "女性人名 ",
        "zh-hans": "女性人名",
        "zh-hant": "女性人名",
        "zh-hk": "女性人名",
        "zh-mo": "女性人名",
        "zh-my": "女性人名",
        "zh-sg": "女性人名",
        "zh-tw": "女性人名",
        "tg-cyrl": "номи занона",
        "tg-latn": "nomi zanona",
    },
    "Q3409032": {  # unisex given name
        "tr": "ön ad",  # [[Topic:Vavf6jigl4dwgkc4]]
        "hu": "uniszex név",  # [[Topic:Y4mda8gast0i6t9o]] "hu": "unisex név",
        "ar": "اسم شخصي محايد",
        "be": "унісекс-імя",
        "bs": "muško i žensko ime",
        "ca": "prenom ambigu",
        "cs": "obourodé jméno",
        "de": "geschlechtsneutraler Vorname",
        "el": "ανδρικό ή γυναικείο όνομα",
        "en": "unisex given name",
        "eo": "seksneŭtra persona nomo",
        "es": "nombre ambiguo",
        "eu": "izen unisex",
        "fr": "prénom épicène",
        "gsw": "gschlächtsneutrale Vorname",
        "hr": "muško i žensko ime",
        "hy": "երկսեռ անձնանուն",
        "it": "prenome sia maschile che femminile",
        "ja": "男女両用の名前",
        "ko": "남녀공통 이름",
        "lb": "geschlechtsneutrale Virnumm",
        "mk": "бесполово име",
        "nb": "kjønnsnøytralt navn",
        "ne": "स्त्री र पुरूष दुबैले प्रयोग गर्ने नाम",
        "nl": "genderneutrale voornaam",
        "pl": "imię uniseksowe",
        "pt": "nome unissex",
        "ru": "унисекс-имя",
        "scn": "nomu di battìu masculinu e fimmininu",
        "sco": "unisex name",
        "sl": "obojespolno osebno ime",
        "sr": "унисекс име",
        "sr-ec": "унисекс име",
        "sr-el": "uniseks ime",
        "sv": "könsneutralt namn",
        "uk": "унісекс ім’я",
        "vi": "tên trung tính",
        "zh": "中性人名",
    },
    "Q50823455": {
        "ar": "سنة في التقويم العبري",
        "bn": "হিব্রু পঞ্জিকার বছর",
        "ca": "any de calendari hebreu",
        "sl": "hebrejsko koledarsko leto",
        "en": "Hebrew calendar year",
        "es": "año del calendario hebreo",
        "fa": "سال در گاه‌شماری عبری",
        "fr": "année hébraïque",
        "he": "שנה עברית",
        "hy": "Հրեական օրացույցի տարեթիվ",
        "id": "tahun kalendar Ibrani",
        "nb": "hebraisk kalenderår",
        "nn": "hebraisk kalenderår",
        "ru": "год еврейского календаря",
        "sq": "vit i kalendarik hebraik",
        "tg-cyrl": "тақвими солшумории ибрӣ",
        "tg-latn": "taqvimi solshumorii hibri",
    },
    "Q4146861": {
        "ar": "سنة في التقويم الهجري",
        "bn": "ইসলামী পঞ্জিকার বছর",
        "sl": "islamsko koledarsko leto",
        "en": "Islamic calendar year",
        "es": "año del calendario musulmán",
        "he": "שנה בלוח השנה המוסלמי",
        "id": "tahun kalendar Islam",
        "nb": "islamsk kalenderår",
        "nn": "islamsk kalenderår",
        "sq": "vit i kalendarik islamik",
    },
    "Q12308941": {  # male given name
        "af": "manlike voornaam",
        "ar": "اسم مذكر معطى",
        "ast": "nome masculín",
        "bar": "Mannanam",
        "be": "мужчынскае асабістае імя",
        "be-tarask": "мужчынскае асабістае імя",
        "bg": "мъжко собствено име",
        "bn": "প্রদত্ত পুরুষ নাম",
        "br": "anv paotr",
        "bs": "muško ime",
        "ca": "prenom masculí",
        "ce": "стеган шен цӀе",
        "cs": "mužské křestní jméno",
        "cy": "enw personol gwrywaidd",
        "da": "drengenavn",
        "de": "männlicher Vorname",
        "el": "ανδρικό όνομα",
        "en": "male given name",
        "eo": "vira persona nomo",
        "es": "nombre masculino",
        "et": "mehenimi",
        "eu": "gizonezko izena",
        "fa": "نام کوچک مردانه",
        "fi": "miehen etunimi",
        "fr": "prénom masculin",
        "fy": "jongesnamme",
        "gl": "nome masculino",
        "gsw": "männlige Vorname",
        "he": "שם פרטי של גבר",
        "hr": "muško ime",
        "hu": "férfiutónév",  # [[Topic:Y4mda8gast0i6t9o]] "hu": "férfikeresztnév",
        "hsb": "muske předmjeno",
        "hy": "արական անձնանուն",
        "id": "nama pemberian maskulin",
        "is": "mannsnafn",
        "it": "prenome maschile",
        "ja": "男性の名前",
        "ka": "მამაკაცის საკუთარი სახელი",
        "ko": "남성의 이름",
        "la": "praenomen masculinum",
        "lb": "männleche Virnumm",
        "lt": "vyriškas vardas",
        "lv": "vīriešu personvārds",
        "mk": "машко лично име",
        "nb": "mannsnavn",
        "ne": "पुलिङ्गी नाम",
        "nl": "mannelijke voornaam",
        "nn": "mannsnamn",
        "or": "ପୁରୁଷଙ୍କ ନାମ",
        "pl": "imię męskie",
        "pt": "nome próprio masculino",
        "pt-br": "nome próprio masculino",
        "ro": "prenume masculin",
        "ru": "мужское личное имя",
        "scn": "nomu di battìu masculinu",
        "sco": "male first name",
        "sk": "mužské meno",
        "sl": "moško osebno ime",
        "smn": "almaa ovdânommâ",
        "sq": "emër mashkullor",
        "sr": "мушко лично име",
        "sr-el": "muško lično ime",
        "sr-ec": "мушко лично име",
        "sv": "mansnamn",
        "sw": "jina la mwanaume",
        "ta": "ஆண்களுக்கு சூட்டிய பெயர்",
        "tg": "номи мардона",
        "th": "ชื่อผู้ชาย",
        "tr": "erkek adı",  # # "tr":"erkek ismidir", Topic:V9p2mhq3iro7lp6y
        "uk": "чоловіче особове ім’я",
        "ur": "مردانہ ذاتی نام",
        "yue": "男人名",
        "zh": "男性人名",
        "zh-cn": "男性人名",
        "zh-hans": "男性名",
        "zh-hant": "男性人名",
        "zh-hk": "男性人名",
        "zh-mo": "男性人名",
        "zh-my": "男性人名",
        "zh-sg": "男性人名",
        "zh-tw": "男性人名",
        "tg-cyrl": "номи мардона",
        "tg-latn": "nomi mardona",
    },
    "Q21199": {  # natural number
        "af": "natuurlike getal",
        "als": "natürlige Zahle",
        "sl": "naravno število",
        "an": "numero natural",
        "ar": "عدد طبيعي",
        "bn": "প্রাকৃতিক সংখ্যা",
        "ca": "nombre natural",
        "en": "natural number",
        "eo": "natura nombro",
        "es": "número natural",
        "he": "מספר טבעי",
        "hi": "प्राकृतिक संख्या",
        "hr": "prirodni broj",
        "hy": "Բնական թիվ",
        "ia": "numero natural",
        "id": "bilangan asli",  # angka alami[[Topic:Vrehx2184pi27t0o]]
        "ka": "ნატურალური რიცხვი",
        "kn": "ಸ್ವಾಭಾವಿಕ ಸಂಖ್ಯೆ",
        "it": "numero naturale",
        "la": "numerus naturalis",
        "lb": "natierlech Zuel",
        "mwl": "númaro natural",
        "nb": "naturlig tall",
        "nn": "naturleg tal",
        "pms": "nùmer natural",
        "pt": "número natural",
        "ro": "număr natural",
        "scn": "nùmmuru naturali",
        "sco": "naitural nummer",
        "sc": "nùmeru naturale",
        "szl": "naturalno nůmera",
        "ru": "натуральное число",
        "sq": "numër natyror",
        "uk": "натуральне число",
        "tg-cyrl": "рақами натуралӣ",
        "tg-latn": "raqami naturaliy",
    },
    "Q13100073": {
        "an": "pueblo d'a Republica Popular de China",  # o 'pueblo de China'
        "ar": "قرية في الصين",
        "bn": "চীনের একটি গ্রাম",
        "ca": "poble de la Xina",
        "de": "Dorf in China",
        "el": "οικισμός της Λαϊκής Δημοκρατίας της Κίνας",
        "en": "village in China",
        "sl": "vas na Kitajskem",
        "eo": "vilaĝo en Ĉinujo",
        "es": "aldea de la República Popular China",
        "fi": "kylä Kiinassa",
        "fr": "village chinois",
        "he": "כפר ברפובליקה העממית של סין",
        "hr": "naselje u Kini",
        "hy": "գյուղ Չինաստանում",
        "id": "desa di Tiongkok",
        "it": "villaggio cinese",
        "nb": "landsby i Kina",
        "nn": "landsby i Kina",
        "nl": "dorp in China",
        "oc": "vilatge chinés",
        "pt-br": "vila chinesa",
        "ro": "sat din China",
        "ru": "деревня КНР",
        "sq": "fshat në Kinë",
        "tg-cyrl": "русто дар Чин",
        "tg-latn": "rusto dar Xitoy",
    },
    "Q4167836": {  # Wikimedia category
        "ace": "kawan Wikimèdia",
        "af": "Wikimedia-kategorie",
        "an": "categoría de Wikimedia",
        "ar": "تصنيف ويكيميديا",
        # "arz":"ويكيبيديا:تصنيف",
        "ast": "categoría de Wikimedia",
        "ba": "Викимедиа категорияһы",
        "bar": "Wikimedia-Kategorie",
        "be": "катэгорыя ў праекце Вікімедыя",
        "be-tarask": "катэгорыя ў праектах Вікімэдыі",
        # "be-tarask": "катэгорыя ў праекце Вікімэдыя",
        "bg": "категория на Уикимедия",
        "bho": "विकिमीडिया श्रेणी",
        "bjn": "tumbung Wikimedia",
        "bn": "উইকিমিডিয়া বিষয়শ্রেণী",
        "br": "pajenn rummata eus Wikimedia",
        "bs": "kategorija na Wikimediji",
        "bug": "kategori Wikimedia",
        "ca": "categoria de Wikimedia",
        # "ce":"Викимедиа проектан категореш",
        # "ceb":"Wikimedia:Kategorisasyon",
        "ckb": "پۆلی ویکیمیدیا",
        "cs": "kategorie na projektech Wikimedia",
        "cy": "tudalen categori Wikimedia",
        "da": "Wikimedia-kategori",
        "de": "Wikimedia-Kategorie",
        "de-at": "Wikimedia-Kategorie",
        "de-ch": "Wikimedia-Kategorie",
        "el": "κατηγορία εγχειρημάτων Wikimedia",
        "en": "Wikimedia category",
        # "en-ca": "Wikimedia category",
        # "en-gb": "Wikimedia category",
        "eo": "kategorio en Vikimedio",
        "es": "categoría de Wikimedia",
        "et": "Wikimedia kategooria",
        "eu": "Wikimediako kategoria",
        "fa": "ردهٔ ویکی‌پدیا",
        "fi": "Wikimedia-luokka",
        "fr": "page de catégorie d'un projet Wikimédia",  # page de catégorie de Wikimedia",
        "fy": "Wikimedia-kategory",
        "gl": "categoría de Wikimedia",
        "gsw": "Wikimedia-Kategorie",
        "gu": "વિકિપીડિયા શ્રેણી",
        "he": "קטגוריה במיזמי ויקימדיה",
        "hi": "विकिमीडिया श्रेणी",
        "hr": "kategorija u wikimediju",
        "hu": "Wikimédia-kategória",
        "hy": "Վիքիմեդիայի նախագծի կատեգորիա",
        "id": "kategori Wikimedia",
        "ilo": "kategoria ti Wikimedia",
        "it": "categoria di un progetto Wikimedia",
        "ja": "ウィキメディアのカテゴリ",
        "kaa": "Wikimedia kategoriyası",
        "ko": "위키미디어 분류",
        "ky": "Wikimedia категориясы",
        "la": "categoria Vicimediorum",
        "lb": "Wikimedia-Kategorie",
        "li": "Wikimedia-categorie",
        "lv": "Wikimedia projekta kategorija",
        "mk": "Викимедиина категорија",
        "nap": "categurìa 'e nu pruggette Wikimedia",
        "nb": "Wikimedia-kategori",
        "nds": "Wikimedia-Kategorie",
        "nl": "Wikimedia-categorie",
        "nn": "Wikimedia-kategori",
        "pl": "kategoria w projekcie Wikimedia",
        "pt": "categoria de um projeto da Wikimedia",
        "pt-br": "categoria de um projeto da Wikimedia",
        "ro": "categorie în cadrul unui proiect Wikimedia",  # https://www.wikidata.org/w/index.php?title=User_talk%3AMr._Ibrahem#c-Vargenau-20250307094900-Romanian_description_for_categories
        "ru": "категория в проекте Викимедиа",
        "sco": "Wikimedia category",
        "se": "Wikimedia-kategoriija",
        "sk": "kategória projektov Wikimedia",
        "sl": "kategorija Wikimedie",  # kategorija Wikimedije  [[wd:Topic:Xjpu4y312bxi699q]]
        "smn": "Wikimedia-luokka",
        "sq": "kategori e Wikimedias",
        "sr": "категорија на Викимедији",
        "sv": "Wikimedia-kategori",
        "sw": "jamii ya Wikimedia",
        "tg": "гурӯҳи Викимедиа",
        "tg-cyrl": "гурӯҳи Викимедиа",
        "tg-latn": "guruhi Vikimedia",
        "tr": "Vikimedya kategorisi",
        "uk": "категорія проєкту Вікімедіа",  # категорія в проекті Вікімедіа [[Topic:Xdnbrl1aqt1lou5u]]
        "vi": "thể loại Wikimedia",
        "yi": "וויקימעדיע קאַטעגאָריע",
        "yo": "ẹ̀ka Wikimedia",
        "yue": "維基媒體分類",
        "zea": "Wikimedia-categorie",
        "zh": "维基媒体分类",
        "zh-cn": "维基媒体分类",
        "zh-hans": "维基媒体分类",
        "zh-hant": "維基媒體分類",
        "zh-hk": "維基媒體分類",
        "zh-mo": "維基媒體分類",
        "zh-my": "维基媒体分类",
        "zh-sg": "维基媒体分类",
        "zh-tw": "維基媒體分類",
    },
    "Q4167410": {  # Wikimedia disambiguation page
        "ast": "páxina de dixebra de Wikimedia",
        "an": "pachina de desambigación",
        "ar": "صفحة توضيح لويكيميديا",
        "be": "старонка неадназначнасці ў праекце Вікімедыя",
        "be-tarask": "старонка-неадназначнасьць Вікімэдыі",
        "bg": "Уикимедия пояснителна страница",
        "bn": "উইকিমিডিয়ার দ্ব্যর্থতা নিরসন পাতা",
        "br": "pajenn disheñvelout eus Wikimedia",
        "bs": "čvor stranica na Wikimediji",
        "ca": "pàgina de desambiguació de Wikimedia",
        "ckb": "پەڕەی ڕوونکردنەوەی ویکیمیدیا",
        "cs": "rozcestník na projektech Wikimedia",
        "da": "Wikimedia-flertydigside",
        "de": "Wikimedia-Begriffsklärungsseite",
        "de-at": "Wikimedia-Begriffsklärungsseite",
        "de-ch": "Wikimedia-Begriffsklärungsseite",
        "el": "σελίδα αποσαφήνισης εγχειρημάτων Wikimedia",
        "en": "Wikimedia disambiguation page",
        "eo": "Vikimedia apartigilo",
        "es": "página de desambiguación de Wikimedia",
        "et": "Wikimedia täpsustuslehekülg",
        "eu": "Wikimediako argipen orri",
        # "fa":"یک صفحهٔ ابهام‌زدایی در ویکی‌پدیا",
        "fa": "یک صفحهٔ ابهام‌زدایی در ویکی‌مدیا",
        "fi": "Wikimedia-täsmennyssivu",
        "fr": "page d'homonymie de Wikimédia",
        "fy": "Wikimedia-betsjuttingsside",
        "gl": "páxina de homónimos de Wikimedia",
        "gsw": "Wikimedia-Begriffsklärigssite",
        "gu": "સ્પષ્ટતા પાનું",
        "he": "דף פירושונים",
        "hi": "बहुविकल्पी पृष्ठ",
        "hr": "razdvojbena stranica",
        "hu": "Wikimédia-egyértelműsítőlap",
        "hy": "Վիքիմեդիայի նախագծի բազմիմաստության փարատման էջ",
        "id": "halaman disambiguasi",
        "is": "aðgreiningarsíða á Wikipediu",
        "it": "pagina di disambiguazione di un progetto Wikimedia",
        "ja": "ウィキメディアの曖昧さ回避ページ",
        "ka": "მრავალმნიშვნელოვანი",
        "ko": "위키미디어 동음이의어 문서",
        "la": "pagina discretiva Vicimediorum",
        "lb": "Wikimedia-Homonymiesäit",
        "li": "Wikimedia-verdudelikingspazjena",
        "lv": "Wikimedia projekta nozīmju atdalīšanas lapa",
        "min": "laman disambiguasi",
        "mk": "појаснителна страница на Викимедија",
        "ms": "laman nyahkekaburan",
        "nb": "Wikimedia-pekerside",
        "nds": "Sied för en mehrdüdig Begreep op Wikimedia",
        "nl": "Wikimedia-doorverwijspagina",
        "nn": "Wikimedia-fleirtydingsside",
        "or": "ବହୁବିକଳ୍ପ ପୃଷ୍ଠା",
        "pl": "strona ujednoznaczniająca w projekcie Wikimedia",
        "pt": "página de desambiguação da Wikimedia",
        "ro": "pagină de dezambiguizare Wikimedia",
        "ru": "страница значений в проекте Викимедиа",
        "sco": "Wikimedia disambiguation page",
        "sk": "rozlišovacia stránka",
        "sl": "razločitvena stran Wikimedie",  # razločitvena stran Wikimedije [[wd:Topic:Xjpu4y312bxi699q]]
        "smn": "Wikimedia-tärkkilistemsijđo",
        "sq": "faqe kthjelluese e Wikimedias",
        "sr": "вишезначна одредница на Викимедији",
        "sv": "Wikimedia-förgreningssida",
        "sw": "ukarasa wa maana wa Wikimedia",
        "tg": "саҳифаи маъноҳои Викимедиа",
        "tg-cyrl": "саҳифаи маъноҳои Викимедиа",
        "tg-latn": "sahifai ma'nohoi Vikimedia",
        "tr": "Vikimedya anlam ayrımı sayfası",
        "tt": "Мәгънәләр бите Викимедиа проектында",
        "tt-cyrl": "Мәгънәләр бите Викимедиа проектында",
        "tt-latn": "Mäğnälär bite Wikimedia proyektında",
        # "uk":"сторінка значень в проекті Вікімедіа",сторінка-список в проекті Вікімедіа
        # "uk":"сторінка-список у проекті Вікімедіа",
        # "uk":"сторінка значень у проекті Вікімедіа",
        "uk": "сторінка значень у проєкті Вікімедіа",
        "vi": "trang định hướng Wikimedia",
        "yi": "וויקימעדיע באַדייטן בלאַט",
        "yo": "ojúewé ìṣojútùú Wikimedia",
        "yue": "維基媒體搞清楚頁",
        "zea": "Wikimedia-deurverwiespagina",
        "zh": "维基媒体消歧义页",
        "zh-cn": "维基媒体消歧义页",
        "zh-hans": "维基媒体消歧义页",
        "zh-hant": "維基媒體消歧義頁",
        "zh-hk": "維基媒體消歧義頁",
        "zh-mo": "維基媒體消歧義頁",
        "zh-my": "维基媒体消歧义页",
        "zh-sg": "维基媒体消歧义页",
        "zh-tw": "維基媒體消歧義頁",
    },
    "Q13406463": {  # Wikimedia list article
        "ace": "teunuléh dapeuta Wikimèdia",
        "af": "Wikimedia lysartikel",
        "an": "articlo de lista de Wikimedia",
        "ar": "قائمة ويكيميديا",
        "as": "ৱিকিপিডিয়া:ৰচনাশৈলীৰ হাতপুথি",
        "ast": "artículu de llista de Wikimedia",
        "bar": "Wikimedia-Listn",
        "ba": "Wikimedia-Listn",
        "be": "спіс артыкулаў у адным з праектаў Вікімедыя",  # [[Topic:Wk7s8mkiocfk2axa]]
        "be-tarask": "артыкул-сьпіс Вікімэдыі",
        "bn": "উইকিমিডিয়ার তালিকা নিবন্ধ",
        "br": "roll eus Wikimedia",
        "bs": "spisak na Wikimediji",
        "ca": "article de llista de Wikimedia",
        "cs": "seznam na projektech Wikimedia",
        "da": "Wikimedia liste",
        "de": "Wikimedia-Liste",
        "de-at": "Wikimedia-Liste",
        "de-ch": "Wikimedia-Liste",
        "el": "κατάλογος εγχειρήματος Wikimedia",
        "en": "Wikimedia list article",
        "eo": "listartikolo en Vikimedio",
        "es": "artículo de lista de Wikimedia",
        "eu": "Wikimediako zerrenda artikulua",
        "fi": "Wikimedia-luetteloartikkeli",
        "fr": "liste d'un projet Wikimedia",
        "fy": "Wikimedia-list",
        "gl": "artigo de listas da Wikimedia",
        "he": "רשימת ערכים במיזמי ויקימדיה",
        "hr": "popis u wikimediju",
        "hsb": "lisćina Wikimedije",
        "hy": "Վիքիմեդիայի նախագծի ցանկ",
        "id": "artikel daftar Wikimedia",
        "ia": "lista de un projecto de Wikimedia",
        "it": "lista di un progetto Wikimedia",
        "ja": "ウィキメディアの一覧記事",
        "ko": "위키미디어 목록 항목",
        "lb": "Wikimedia-Lëschtenartikel",
        "li": "Wikimedia-lies",
        "mk": "список на статии на Викимедија",
        "ms": "rencana senarai Wikimedia",
        "nb": "Wikimedia-listeartikkel",
        "nl": "Wikimedia-lijst",
        "nn": "Wikimedia-listeartikkel",
        "oc": "lista d'un projècte Wikimèdia",
        "pl": "lista w projekcie Wikimedia",
        "pt": "lista de um projeto Wikimedia",
        "pt-br": "lista de um projeto Wikimedia",
        "ro": "articol-listă în cadrul unui proiect Wikimedia",
        "ru": "статья-список в проекте Викимедиа",
        "sco": "Wikimedia leet airticle",
        "si": "විකිමීඩියා ලැයිස්තු ලිපිය",
        "sk": "zoznamový článok projektov Wikimedia",
        "sl": "seznam Wikimedie",  # seznam Wikimedije [[wd:Topic:Xjpu4y312bxi699q]]
        "smn": "Wikimedia-luvâttâllâmartikkâl",
        "sq": "artikull-listë e Wikimedias",
        "sr": "списак на Викимедији",
        "sv": "Wikimedia-listartikel",
        "sw": "orodha ya makala za Wikimedia",
        "ta": "விக்கிப்பீடியா:பட்டியலிடல்",
        "tg": "саҳифаи феҳристӣ",
        "tg-cyrl": "саҳифаи феҳристӣ",
        "tg-latn": "sahifai fehristiy",
        "th": "บทความรายชื่อวิกิมีเดีย",
        "tr": "Vikimedya liste maddesi",
        "uk": "стаття-список у проєкті Вікімедіа",  # сторінка-список у проекті Вікімедіа [[Topic:Xdnbrl1aqt1lou5u]]
        "vi": "bài viết danh sách Wikimedia",
        "yi": "וויקימעדיע ליסטע אַרטיקל",
        "yo": "ojúewé àtojọ Wikimedia",
        "yue": "維基媒體一覽文",
        "zea": "Wikimedia-lieste",
        "zh": "维基媒体列表条目",
        "zh-cn": "维基媒体列表条目",
        "zh-hans": "维基媒体列表条目",
        "zh-hant": "維基媒體列表條目",
        "zh-hk": "維基媒體列表條目",
        "zh-mo": "維基媒體列表條目",
        "zh-my": "维基媒体列表条目",
        "zh-sg": "维基媒体列表条目",
        "zh-tw": "維基媒體列表條目",
    },
    "Q17633526": {
        "an": "articlo de Wikinews",
        "ar": "مقالة ويكي أخبار",
        "bar": "Artike bei Wikinews",
        "bn": "উইকিসংবাদের নিবন্ধ",
        "bs": "Wikinews članak",
        "ca": "article de Viquinotícies",
        "cs": "článek na Wikizprávách",
        "da": "Wikinews-artikel",
        "de": "Artikel bei Wikinews",
        "el": "Άρθρο των Βικινέων",
        "sl": "članek Wikinovic",
        "en": "Wikinews article",
        "eo": "artikolo de Vikinovaĵoj",
        "es": "artículo de Wikinoticias",
        "eu": "Wikialbisteakeko artikulua",
        "fi": "Wikiuutisten artikkeli",
        "fr": "article de Wikinews",
        "fy": "Wikinews-artikel",
        "he": "כתבה בוויקיחדשות",
        "hu": "Wikihírek-cikk",
        "hy": "Վիքիլուրերի հոդված",
        "id": "artikel Wikinews",
        "it": "articolo di Wikinotizie",
        "ja": "ウィキニュースの記事",
        "ko": "위키뉴스 기사",
        "ku-latn": "gotara li ser Wîkînûçeyê",
        "li": "Wikinews-artikel",
        "lt": "Vikinaujienų straipsnis",
        "mk": "напис на Викивести",
        "nb": "Wikinytt-artikkel",
        "nl": "Wikinieuws-artikel",
        "nn": "Wikinytt-artikkel",
        "or": "ଉଇକି ସୂଚନା ପତ୍ରିକା",
        "pl": "artykuł w Wikinews",
        "ps": "د ويکيخبرونو ليکنه",
        "pt": "artigo do Wikinotícias",
        "ro": "articol în Wikiștiri",
        "ru": "статья Викиновостей",
        "sq": "artikull i Wikinews",
        "sr": "чланак са Викивести",
        "sv": "Wikinews-artikel",
        "te": "వికీవార్త వ్యాసం",
        "tg": "саҳифаи Викиахбор",
        "tg-cyrl": "мақолаи Викиахбор",
        "tg-latn": "maqolai Vikimedia",
        "th": "เนื้อหาวิกิข่าว",
        "tr": "Vikihaber maddesi",
        "uk": "стаття Вікіновин",
        "zea": "Wikinews-artikel",
        "zh": "維基新聞新聞稿",
        "zh-cn": "维基新闻新闻稿",
        "zh-hans": "维基新闻新闻稿",
        "zh-hant": "維基新聞新聞稿",
        "zh-hk": "維基新聞新聞稿",
        "zh-mo": "維基新聞新聞稿",
        "zh-my": "维基新闻新闻稿",
        "zh-sg": "维基新闻新闻稿",
        "zh-tw": "維基新聞新聞稿",
    },
    "Q577": {
        "af": "jaar",
        "an": "anyo",
        "ar": "سنة",
        "ast": "añu",
        "be": "год",
        "be-tarask": "год",
        "bg": "година",
        "bn": "বছর",
        "br": "bloavezh",
        "bs": "godina",
        "ca": "any",
        "ckb": "ساڵ",
        "cs": "rok",
        "da": "år",
        "de": "Jahr",
        "el": "έτος",
        "en": "year",
        "eo": "jaro",
        "es": "año",
        "et": "Aasta",
        "eu": "urte",
        "fa": "سال",
        "fi": "vuosi",
        "fr": "année",
        "fy": "jier",
        "gl": "ano",
        "gsw": "joor",
        "gu": "વર્ષ",
        "he": "שנה",
        "hr": "godina",
        "ht": "Lane",
        "hu": "év",
        "hy": "տարեթիվ",
        "ia": "anno",
        "id": "tahun",
        "ilo": "Tawen",
        "is": "ár",
        "it": "anno",
        "ja": "年",
        "ka": "წელი",
        "ko": "연도",
        "ku": "Sal",
        "la": "annus",
        "lb": "Joer",
        "lt": "Metai",
        "lv": "gads",
        "mhr": "Идалык",
        "min": "taun",
        "mk": "година",
        "ms": "Tahun",
        "nan": "Nî",
        "nb": "år",
        "nds": "Johr",
        "nl": "jaar",
        "nn": "år",
        "or": "ବର୍ଷ",
        "pl": "rok",
        "pt": "ano",
        "ro": "an",
        "ru": "год",
        "se": "jahki",
        "sh": "godina",
        "sje": "jahke",
        "sk": "rok",
        "sl": "leto",
        "sma": "jaepie",
        "smj": "jahke",
        "smn": "ihe",
        "sq": "viti",
        "sr": "година",
        "srn": "Yari",
        "sv": "år",
        "sw": "mwaka",
        "tr": "yıl",
        "uk": "рік",
        "ur": "سال",
        "vi": "Năm",
        "war": "Tuig",
        "yi": "יאָר",
        "yue": "年",
        "zh": "年份",
        "zh-cn": "年份",
        "zh-hans": "年份",
        "zh-hant": "年份",
        "zh-hk": "年份",
        "zh-mo": "年份",
        "zh-sg": "年份",
        "zh-tw": "年份"
    }
}

many_lang_qid_desc["Q11266439"] = {  # Wikimedia template#Q11753321
    "ab": "ашаблон Авикипедиа",
    "ace": "pola Wikimèdia",
    "af": "sjabloon Wikimedia",
    "ak": "şablon Wikimedia",
    "am": "መለጠፊያ ውክፔዲያ",
    "an": "plantilla de Wikimedia",
    "ang": "Ƿikipǣdia bysen",
    "ar": "قالب ويكيميديا",
    "arc": "ܩܠܒܐ ܘܝܩܝܦܕܝܐ",
    "arz": "قالب ويكيبيديا",
    "as": "সাঁচ ৱিকিপিডিয়া",
    "ast": "plantía de Wikimedia",
    "av": "шаблон Википедия",
    "ay": "plantilla Wikipidiya",
    "az": "şablon Vikipediya",
    "ba": "Викимедиа ҡалыбы",
    "bar": "Wikimedia-Vorlog",
    "bcl": "plantilya Wikimedia",
    "be": "шаблон праекта Вікімедыя",
    "be-tarask": "шаблён праекту Вікімэдыя",
    "bg": "Уикимедия шаблон",
    "bho": "विकिमीडिया टेम्पलेट",
    "bjn": "citakan Wikimedia",
    "bm": "modèle Wikipedi",
    "bn": "উইকিমিডিয়া টেমপ্লেট",
    "bo": "དཔེ་པང་། ལྦེ་ཁེ་རིག་མཛོད།",
    "bpy": "মডেল উইকিপিডিয়া",
    "br": "patrom Wikimedia",
    "bs": "šablon Wikimedia",
    "bug": "templat Wikimedia",
    "ca": "plantilla de Wikimedia",
    "cbk-zam": "plantilla Wikimedia",
    "ce": "Викимедин проектан кеп",
    "ceb": "plantilya Wikipedya",
    "ckb": "داڕێژەی ویکیمیدیا",
    "crh-latn": "şablon Vikipediya",
    "cs": "šablona na projektech Wikimedia",
    "csb": "szablóna Wikipedijô",
    "cv": "шаблон Википеди",
    "cy": "nodyn Wikimedia",
    "da": "Wikimedia-skabelon",
    "de": "Wikimedia-Vorlage",
    "de-at": "Wikimedia-Vorlage",
    "de-ch": "Wikimedia-Vorlage",
    "diq": "şablon Wikipediya",
    "dsb": "Wikimedija pśedłoga",
    "dv": "ފަންވަތް ވިކިޕީޑިޔާ",
    "el": "Πρότυπο εγχειρήματος Wikimedia",
    "eml": "template Vichipedia",
    "en": "Wikimedia template",
    "eo": "Vikimedia ŝablono",
    "es": "plantilla de Wikimedia",
    "et": "Wikimedia mall",
    "eu": "Wikimediako txantiloia",
    "ext": "prantilla Güiquipeya",
    "fa": "الگوی ویکی‌مدیا",
    "ff": "modèle Wikipeediya",
    "fi": "Wikimedia-malline",
    "fo": "fyrimynd Wikimedia",
    "fr": "modèle de Wikimedia",
    "frp": "modèlo Wikimedia",
    "frr": "Wikimedia-föörlaag",
    "fur": "model Vichipedie",
    "fy": "Wikimedia-berjocht",
    "ga": "teimpléad Wikimedia",
    "gag": "şablon Vikipediya",
    "gan": "模板 維基百科",
    "gd": "Uicipeid teamplaid",
    "gl": "modelo da Wikimedia",
    "glk": "الگو ویکیپدیا",
    "gn": "tembiecharã Vikipetã",
    "got": "𐍅𐌹𐌺𐌹𐍀𐌰𐌹𐌳𐌾𐌰 𐍆𐌰𐌿𐍂𐌰𐌼𐌴𐌻𐌴𐌹𐌽𐍃",
    "gsw": "Wikimedia-Vorlage",
    "gu": "વિકિપીડિયા ઢાંચો",
    "gv": "clowan Wikimedia",
    "haw": "anakuhi ʻo Wikipikia",
    "he": "תבנית של ויקימדיה",
    "hi": "साँचा विकिपीडिया",
    "hr": "predložak za wikimedije",
    "hsb": "předłoha Wikimedije",
    "ht": "modèl Wikipedya",
    "hu": "Wikimédia-sablon",
    "hy": "Վիքիմեդիայի նախագծի կաղապար",
    "ia": "Wikimedia patrono",
    "id": "templat Wikimedia",
    "ie": "avise Wikimedia",
    "ig": "àtụ Wikimedia",
    "ilo": "plantilia ti Wikimedia",
    "io": "shablono Wikipedio",
    "is": "snið Wikimedia",
    "it": "template di un progetto Wikimedia",
    "ja": "ウィキメディアのテンプレート",
    "jv": "cithakan Wikimedia",
    "ka": "ვიკიმედიის თარგი",
    "kaa": "Wikimedia úlgisi",
    "kk": "Уикимедиа үлгісі",
    "kl": "ilisserut Wikimedia",
    "km": "វិគីភីឌា ទំព័រគំរូ",
    "kn": "ಟೆಂಪ್ಲೇಟು ವಿಕಿಪೀಡಿಯ",
    "ko": "위키미디어 틀",
    "koi": "шаблон Википедия",
    "ks": "فرماویکیپیٖڈیا",
    "ku": "şablon Wîkîpediya",
    "ku-latn": "şablona Wîkîmediyayê",
    "kw": "skantlyn Wikipedya",
    "ky": "калып Уикипедия",
    "la": "formula Vicimediorum",
    "lad": "xablón Vikipedya",
    "lb": "Wikimedia-Schabloun",
    "li": "Wikimedia-sjabloon",
    "lmo": "Wikimedia mudel",
    "ln": "Wikimedia modèle",
    "lo": "ແມ່ແບບ ວິກິພີເດຍ",
    "lt": "Vikimedijos šablonas",
    "lv": "Wikimedia projekta veidne",
    "lzh": "template 維基大典",
    "map-bms": "cithakan Wikimedia",
    "mdf": "шаблон Википедиесь",
    "mg": "Wikimedia endrika",
    "mhr": "кышкар Википедий",
    "min": "templat Wikimedia",
    "mk": "шаблон на Викимедија",
    "ml": "വിക്കിമീഡിയ ഫലകം",
    "mn": "загвар Википедиа",
    "mr": "विकिपीडिया:साचा",
    "ms": "Templat Wikimedia",
    "mt": "mudell Wikimedia",
    "mwl": "modelo Biquipédia",
    "my": "ဝီကီပီးဒီးယား template",
    "mzn": "شابلون ویکی‌پدیا",
    "nb": "Wikimedia-mal",
    "nds": "Wikimedia-Vörlaag",
    "nds-nl": "Wikimedia-mal",
    "ne": "ढाँचा विकिपीडिया",
    "new": "विकिपिडिया template",
    "nl": "Wikimedia-sjabloon",
    "nn": "Wikimedia-mal",
    "oc": "modèl de Wikimèdia",
    "or": "ଉଇକିମିଡ଼ିଆ ଛାଞ୍ଚ",
    "os": "хуызæг Википеди",
    "pa": "ਫਰਮਾ ਵਿਕੀਪੀਡੀਆ",
    "pam": "Ulmang pang-Wikimedia",
    "pi": "पटिरूप विकिपीडिया",
    "pl": "szablon w projekcie Wikimedia",
    "pnb": "template وکیپیڈیا",
    "pnt": "πρότυπον Βικιπαίδεια",
    "ps": "ويکيمېډيا کينډۍ",
    "pt": "predefinição da Wikimedia",
    "pt-br": "predefinição da Wikimedia",
    "qu": "plantilla Wikipidiya",
    "rm": "model Vichipedia",
    "rmy": "sikavno Vikipidiya",
    "ro": "format Wikimedia",
    "ru": "шаблон проекта Викимедиа",
    "rue": "шаблона Вікімедія",
    "sa": "फलकम् विकिपीडिया",
    "sah": "халыып Бикипиэдьийэ",
    "sd": "سانچو وڪيپيڊيا",
    "sg": "modèle Wïkïpêdïyäa",
    "sgs": "šabluons Vikipedėjė",
    "sh": "šablon Wikipediju",
    "si": "සැකිල්ල විකිපීඩියා",
    "sco": "Wikimedia template",
    "se": "Wikimedia-málle",
    "sk": "šablóna projektov Wikimedia",
    "sl": "predloga Wikimedie",
    "smn": "Wikimedia-myenster",
    "sq": "stampë e Wikimedias",
    "sr": "Викимедијин шаблон",
    "sr-ec": "Викимедијин шаблон",
    "srn": "ankra Wikipedia",
    "stq": "Wikimedia-Foarloage",
    "su": "citakan Wikipédia",
    "sv": "Wikimedia-mall",
    "sw": "kigezo cha Wikimedia",
    "ta": "விக்கிமீடியா வார்ப்புரு",
    "te": "వికీమీడియా మూస",
    "tg": "шаблони лоиҳаи Викимедиа",
    "tg-cyrl": "шаблони Викимедиа",
    "tg-latn": "shabloni Vikimedia",
    "th": "หน้าแม่แบบวิกิมีเดีย",
    "tk": "şablon Wikipediýa",
    "tl": "Padrong pang-Wikimedia",
    "tpi": "Wikimedia templet",
    "tr": "Vikimedya şablonu",
    "ts": "template Wikimedia",
    "tt": "калып Викимедиа",
    "ug": "قېلىپ ۋىكىپېدىيە",
    "uk": "шаблон проєкту Вікімедіа",  # шаблон проекту Вікімедіа[[Topic:Xdnbrl1aqt1lou5u]]
    "ur": "سانچہ ویکیپیڈیا",
    "uz": "andoza Vikipediya",
    "vi": "bản mẫu Wikimedia",
    "vro": "näüdüs Vikipeediä",
    "wa": "modele Wikimedia",
    "war": "batakan Wikimedia",
    "wuu": "模板 维基百科",
    "xal": "кевләр Бикипеди",
    "xmf": "თარგი ვიკიპედია",
    "yi": "וויקימעדיע מוסטער",
    "yo": "àdàkọ Wikimedia",
    "yue": "維基媒體模",
    "za": "模板 Veizgiek Bakgoh",
    "zea": "Wikimedia-sjabloon",
    "zh": "维基媒体模板",
    "zh-cn": "维基媒体模板",
    "zh-hans": "维基媒体模板",
    "zh-hant": "維基媒體模板",
    "zh-hk": "維基媒體模板",
    "zh-mo": "維基媒體模板",
    "zh-sg": "维基媒体模板",
    "zh-tw": "維基媒體模板",
}


# https://www.wikidata.org/wiki/MediaWiki:Gadget-autoEdit.js
many_lang_qid_desc["Q11266439_xx"] = {  # Wikimedia template#Q11753321
    "ab": "ашаблон Авикипедиа",
    "ace": "pola Wikimèdia",
    "af": "sjabloon Wikimedia",
    "ak": "şablon Wikimedia",
    "am": "መለጠፊያ ውክፔዲያ",
    "an": "plantilla de Wikimedia",
    "ang": "Ƿikipǣdia bysen",
    "ar": "قالب ويكيميديا",
    "arc": "ܩܠܒܐ ܘܝܩܝܦܕܝܐ",
    "arz": "قالب ويكيبيديا",
    "as": "সাঁচ ৱিকিপিডিয়া",
    "ast": "plantía de Wikimedia",
    "av": "шаблон Википедия",
    "ay": "plantilla Wikipidiya",
    "az": "şablon Vikipediya",
    "ba": "ҡалып Википедия",
    # "ba": "Викимедиа ҡалыбы",
    "bar": "Wikimedia-Vorlog",
    "bcl": "plantilya Wikimedia",
    "be": "шаблон праекта Вікімедыя",
    "be-tarask": "шаблён Вікімэдыі",
    # "be-tarask": "шаблён праекту Вікімэдыя",
    "bg": "Уикимедия шаблон",
    "bho": "विकिमीडिया टेम्पलेट",
    "bjn": "citakan Wikimedia",
    "bm": "modèle Wikipedi",
    "bn": "উইকিমিডিয়া টেমপ্লেট",
    "bo": "དཔེ་པང་། ལྦེ་ཁེ་རིག་མཛོད།",
    "bpy": "মডেল উইকিপিডিয়া",
    "br": "patrom Wikimedia",
    "bs": "šablon Wikimedia",
    "bug": "templat Wikimedia",
    "ca": "plantilla de Wikimedia",
    "cbk-zam": "plantilla Wikimedia",
    "ce": "куцкеп Википеди",
    # "ce": "Викимедин проектан кеп",
    "ceb": "plantilya Wikipedya",
    "ckb": "داڕێژەی ویکیمیدیا",
    "crh-latn": "şablon Vikipediya",
    "cs": "šablona na projektech Wikimedia",
    "csb": "szablóna Wikipedijô",
    "cv": "шаблон Википеди",
    "cy": "Wicipedia nodyn",
    # "cy": "nodyn Wikimedia",
    "da": "Wikimedia-skabelon",
    "de": "Wikimedia-Vorlage",
    "de-at": "Wikimedia-Vorlage",
    "de-ch": "Wikimedia-Vorlage",
    "diq": "şablon Wikipediya",
    "dsb": "Wikimedija pśedłoga",
    "dv": "ފަންވަތް ވިކިޕީޑިޔާ",
    "el": "Πρότυπο εγχειρήματος Wikimedia",
    "eml": "template Vichipedia",
    "en": "Wikimedia template",
    "eo": "Vikimedia ŝablono",
    "es": "plantilla de Wikimedia",
    "et": "Wikimedia mall",
    "eu": "Wikimediako txantiloi",
    # "eu": "Wikimediako txantiloia",
    "ext": "prantilla Güiquipeya",
    "fa": "الگو ویکی‌پدیا",
    # "fa": "الگوی ویکی‌مدیا",
    "ff": "modèle Wikipeediya",
    "fi": "Wikimedia-malline",
    "fo": "fyrimynd Wikimedia",
    "fr": "modèle de Wikimedia",
    "frp": "modèlo Wikimedia",
    "frr": "Wikimediavorlage",
    # "frr": "Wikimedia-föörlaag",
    "fur": "model Vichipedie",
    "fy": "Wikimedia-berjocht",
    "ga": "teimpléad Wikimedia",
    "gag": "şablon Vikipediya",
    "gan": "模板 維基百科",
    "gd": "Uicipeid teamplaid",
    "gl": "modelo de Wikimedia",
    # "gl": "modelo da Wikimedia",
    "glk": "الگو ویکیپدیا",
    "gn": "tembiecharã Vikipetã",
    "got": "𐍅𐌹𐌺𐌹𐍀𐌰𐌹𐌳𐌾𐌰 𐍆𐌰𐌿𐍂𐌰𐌼𐌴𐌻𐌴𐌹𐌽𐍃",
    "gsw": "Wikimedia-Vorlage",
    "gu": "ઢાંચો વિકિપીડિયા",
    # "gu": "વિકિપીડિયા ઢાંચો",
    "gv": "clowan Wikimedia",
    "haw": "anakuhi ʻo Wikipikia",
    "he": "דף תבנית במיזמי ויקימדיה",
    # "he": "תבנית של ויקימדיה",
    "hi": "साँचा विकिपीडिया",
    "hr": "predložak za wikimedije",
    "hsb": "předłoha Wikimedije",
    "ht": "modèl Wikipedya",
    "hu": "Wikimédia-sablon",
    "hy": "Վիքիմեդիայի նախագծի կաղապար",
    "ia": "Wikimedia patrono",
    "id": "templat Wikimedia",
    "ie": "avise Wikimedia",
    "ig": "àtụ Wikimedia",
    "ilo": "plantilia ti Wikimedia",
    "io": "shablono Wikipedio",
    "is": "snið Wikimedia",
    "it": "template di un progetto Wikimedia",
    "ja": "ウィキメディアのテンプレート",
    "jv": "cithakan Wikimedia",
    "ka": "თარგი ვიკიპედია",
    # "ka": "ვიკიმედიის თარგი",
    "kaa": "shablon Wikimedia",
    "kk": "Уикимедиа үлгісі",
    "kl": "ilisserut Wikimedia",
    "km": "វិគីភីឌា ទំព័រគំរូ",
    "kn": "ಟೆಂಪ್ಲೇಟು ವಿಕಿಪೀಡಿಯ",
    "ko": "위키미디어 틀",
    "koi": "шаблон Википедия",
    "ks": "فرماویکیپیٖڈیا",
    "ku": "şablon Wîkîpediya",
    "ku-latn": "şablona Wîkîmediyayê",
    "kw": "skantlyn Wikipedya",
    "ky": "калып Уикипедия",
    "la": "formula Vicimediorum",
    "lad": "xablón Vikipedya",
    "lb": "Wikimedia-Schabloun",
    "li": "sjabloon Wikimedia",
    # "li": "Wikimedia-sjabloon",
    "lmo": "Wikimedia mudel",
    "ln": "Wikimedia modèle",
    "lo": "ແມ່ແບບ ວິກິພີເດຍ",
    "lt": "šablonas Vikipedija",
    # "lt": "Vikimedijos šablonas",
    "lv": "Wikimedia projekta veidne",
    "lzh": "template 維基大典",
    "map-bms": "cithakan Wikimedia",
    "mdf": "шаблон Википедиесь",
    "mg": "Wikimedia endrika",
    "mhr": "кышкар Википедий",
    "min": "templat Wikimedia",
    "mk": "шаблон на Викимедија",
    "ml": "ഫലകം വിക്കിപീഡിയ",
    # "ml": "വിക്കിമീഡിയ ഫലകം",
    "mn": "загвар Википедиа",
    "mr": "विकिपीडिया साचा",
    "ms": "templat Wikimedia",
    # "mr": "विकिपीडिया:साचा",
    # "ms": "Templat Wikimedia",
    "mt": "mudell Wikimedia",
    "mwl": "modelo Biquipédia",
    "my": "ဝီကီပီးဒီးယား template",
    "mzn": "شابلون ویکی‌پدیا",
    "nb": "Wikimedia-mal",
    "nds": "Wikimedia-Vörlaag",
    "nds-nl": "Wikimedia-mal",
    "ne": "ढाँचा विकिपीडिया",
    "new": "विकिपिडिया template",
    "nl": "Wikimedia-sjabloon",
    "nn": "Wikimedia-mal",
    "oc": "modèl Wikimedia",
    "or": "ଉଇକିପିଡ଼ିଆ ଛାଞ୍ଚ",
    # "oc": "modèl de Wikimèdia",
    # "or": "ଉଇକିମିଡ଼ିଆ ଛାଞ୍ଚ",
    "os": "хуызæг Википеди",
    "pa": "ਫਰਮਾ ਵਿਕੀਪੀਡੀਆ",
    "pam": "Ulmang pang-Wikimedia",
    "pi": "पटिरूप विकिपीडिया",
    "pl": "szablon w projekcie Wikimedia",
    "pnb": "template وکیپیڈیا",
    "pnt": "πρότυπον Βικιπαίδεια",
    "ps": "کينډۍ ويکيپېډيا",
    "pt": "predefinição Wikimedia",
    # "ps": "ويکيمېډيا کينډۍ",
    # "pt": "predefinição da Wikimedia",
    "pt-br": "predefinição da Wikimedia",
    "qu": "plantilla Wikipidiya",
    "rm": "model Vichipedia",
    "rmy": "sikavno Vikipidiya",
    "ro": "format Wikimedia",
    "ru": "шаблон в проекте Викимедиа",
    # "ru": "шаблон проекта Викимедиа",
    "rue": "шаблона Вікімедія",
    "sa": "फलकम् विकिपीडिया",
    "sah": "халыып Бикипиэдьийэ",
    "sd": "سانچو وڪيپيڊيا",
    "sg": "modèle Wïkïpêdïyäa",
    "sgs": "šabluons Vikipedėjė",
    "sh": "šablon Wikipediju",
    "si": "සැකිල්ල විකිපීඩියා",
    "sco": "Wikimedia template",
    "se": "Wikimedia-málle",
    "sk": "šablóna projektov Wikimedia",
    "sl": "predloga Wikimedie",
    "smn": "Wikimedia-myenster",
    "sq": "stampë e Wikimedias",
    "sr": "Викимедијин шаблон",
    "sr-ec": "Викимедијин шаблон",
    "srn": "ankra Wikipedia",
    # "stq": "Wikimedia-Foarloage",
    "stq": "foarloage Wikipedia",
    "su": "citakan Wikipédia",
    "sv": "Wikimedia-mall",
    "sw": "kigezo cha Wikimedia",
    "ta": "வார்ப்புரு விக்கிப்பீடியா",
    "te": "మూస వికీపీడియా",
    "tg": "шаблон Википедиа",
    # "ta": "விக்கிமீடியா வார்ப்புரு",
    # "te": "వికీమీడియా మూస",
    # "tg": "шаблони лоиҳаи Викимедиа",
    "tg-cyrl": "шаблони Викимедиа",
    "tg-latn": "shabloni Vikimedia",
    "th": "แม่แบบ วิกิพีเดีย",
    # "th": "หน้าแม่แบบวิกิมีเดีย",
    "tk": "şablon Wikipediýa",
    # "tl": "Padrong pang-Wikimedia",
    "tl": "padron Wikimedia",
    "tpi": "Wikimedia templet",
    "tr": "Vikimedya şablonu",
    "ts": "template Wikimedia",
    "tt": "калып Викимедиа",
    "ug": "قېلىپ ۋىكىپېدىيە",
    "uk": "шаблон проєкту Вікімедіа",  # шаблон проекту Вікімедіа[[Topic:Xdnbrl1aqt1lou5u]]
    "ur": "سانچہ ویکیپیڈیا",
    "uz": "andoza Vikipediya",
    "vi": "bản mẫu Wikimedia",
    "vro": "näüdüs Vikipeediä",
    "wa": "modele Wikimedia",
    "war": "batakan Wikimedia",
    "wuu": "模板 维基百科",
    "xal": "кевләр Бикипеди",
    "xmf": "თარგი ვიკიპედია",
    "yi": "וויקימעדיע מוסטער",
    "yo": "àdàkọ Wikimedia",
    "yue": "維基媒體模",
    "za": "模板 Veizgiek Bakgoh",
    "zea": "Wikimedia-sjabloon",
    "zh": "维基媒体模板",
    "zh-cn": "维基媒体模板",
    "zh-hans": "维基媒体模板",
    "zh-hant": "維基媒體模板",
    "zh-hk": "維基媒體模板",
    "zh-mo": "維基媒體模板",
    "zh-sg": "维基媒体模板",
    "zh-tw": "維基媒體模板",
}
