#!/usr/bin/python3
"""

إضافة تسميات عناصر ويكي بيانات

بناءاً على خاصية سبقه أو تبعه


"""

Sports_Keys_For_Label = {
    "acrobatic gymnastics": "الجمباز الاكروباتيكي",
    "acrobatic gymnastics racing": "سباق الجمباز الاكروباتيكي",
    "aerobics": "جمباز أيروبيكس",
    "aerobics racing": "سباق جمباز أيروبيكس",
    "alpine skiing": "التزلج على المنحدرات الثلجية",
    "alpine skiing racing": "سباق التزلج على المنحدرات الثلجية",
    "american football": "كرة القدم الأمريكية",
    "american football racing": "سباق كرة القدم الأمريكية",
    "american-football": "كرة القدم الأمريكية",
    "american-football racing": "سباق كرة القدم الأمريكية",
    "aquatic sports": "الرياضات المائية",
    "aquatic sports racing": "سباق الرياضات المائية",
    "aquatics": "الرياضات المائية",
    "aquatics racing": "سباق الرياضات المائية",
    "archery": "النبالة",
    "archery racing": "سباق النبالة",
    "artistic gymnastics": "الجمباز الفني",
    "artistic gymnastics racing": "سباق الجمباز الفني",
    "artistic swimming": "السباحة الفنية",
    "artistic swimming racing": "سباق السباحة الفنية",
    "association football": "كرة القدم",
    "association football racing": "سباق كرة القدم",
    "athletics": "ألعاب القوى",
    "athletics racing": "سباق ألعاب القوى",
    "australian rules football": "كرة القدم الأسترالية",
    "australian rules football racing": "سباق كرة القدم الأسترالية",
    "auto racing": "سباق السيارات",
    "automobile racing": "سباق السيارات",
    "badminton": "تنس الريشة",
    "badminton racing": "سباق تنس الريشة",
    "ball hockey": "هوكي الكرة",
    "ball hockey racing": "سباق هوكي الكرة",
    "bandy": "باندي",
    "bandy racing": "سباق باندي",
    "baseball": "كرة القاعدة",
    "baseball racing": "سباق كرة القاعدة",
    "basketball": "كرة السلة",
    "basketball racing": "سباق كرة السلة",
    "basque pelota": "كرة الباسك",
    "basque pelota racing": "سباق كرة الباسك",
    "beach handball": "كرة اليد الشاطئية",
    "beach handball racing": "سباق كرة اليد الشاطئية",
    "beach soccer": "كرة القدم الشاطئية",
    "beach soccer racing": "سباق كرة القدم الشاطئية",
    "beach volleyball": "كرة الطائرة الشاطئية",
    "beach volleyball racing": "سباق كرة الطائرة الشاطئية",
    "biathlon": "البياثلون",
    "biathlon racing": "سباق البياثلون",
    "bicycle motocross": "بي ام اكس",
    "bicycle motocross racing": "سباق بي ام اكس",
    "bmx": "سباق البي إم إكس",
    "bmx racing": "سباق البي إم إكس",
    "board games": "ألعاب الطاولة",
    "board games racing": "سباق ألعاب الطاولة",
    "boat racing": "سباق الزوارق",
    "bobsleigh": "الزلاجة الجماعية",
    "bobsleigh racing": "سباق الزلاجة الجماعية",
    "boccia": "البوتشيا",
    "boccia racing": "سباق البوتشيا",
    "bodybuilding": "كمال الأجسام",
    "bodybuilding racing": "سباق كمال الأجسام",
    "bouldering": "بولدرنق",
    "bouldering racing": "سباق بولدرنق",
    "boules": "بوتشي",
    "boules racing": "سباق بوتشي",
    "bowling": "بولينج",
    "bowling racing": "سباق بولينج",
    "bowls": "البولينج",
    "bowls racing": "سباق البولينج",
    "boxing": "البوكسينغ",
    "boxing racing": "سباق البوكسينغ",
    "bullfighting": "مصارعة الثيران",
    "bullfighting racing": "سباق مصارعة الثيران",
    "canadian football": "كرة القدم الكندية",
    "canadian football racing": "سباق كرة القدم الكندية",
    "canadian-football": "كرة القدم الكندية",
    "canadian-football racing": "سباق كرة القدم الكندية",
    "canoe sprint": "سباق القوارب",
    "canoeing": "ركوب الكنو",
    "canoeing and kayaking": "كانو-كاياك",
    "canoeing and kayaking racing": "سباق كانو-كاياك",
    "canoeing racing": "سباق ركوب الكنو",
    "chess": "الشطرنج",
    "chess racing": "سباق الشطرنج",
    "chinese martial arts": "الفنون القتالية الصينية",
    "chinese martial arts racing": "سباق الفنون القتالية الصينية",
    "climbing": "التسلق",
    "climbing racing": "سباق التسلق",
    "college": "الكليات",
    "college racing": "سباق الكليات",
    "cricket": "الكريكت",
    "cricket racing": "سباق الكريكت",
    "croquet": "الكروكيت",
    "croquet racing": "سباق الكروكيت",
    "cross country": "العدو الريفي",
    "cross country racing": "سباق العدو الريفي",
    "cross country running": "العدو الريفي",
    "cross country running racing": "سباق العدو الريفي",
    "cross-country skiing": "التزلج الريفي",
    "cross-country skiing racing": "سباق التزلج الريفي",
    "cue sports": "بلياردو",
    "cue sports racing": "سباق بلياردو",
    "curling": "الكيرلنغ",
    "curling racing": "سباق الكيرلنغ",
    "cycle": "الدراجات",
    "cycle race": "سباق الدراجات",
    "cycle racing": "سباق الدراجات",
    "cycle speedway": "سباق الدراجات النارية على المنعطفات",
    "cycling": "سباق الدراجات الهوائية",
    "cycling road race": "سباق الدراجات على الطريق",
    "cyclo-cross": "سيكلو كروس",
    "cyclo-cross racing": "سباق سيكلو كروس",
    "darts": "السهام المريشة",
    "darts racing": "سباق السهام المريشة",
    "davis cup": "كأس ديفيز",
    "davis cup racing": "سباق كأس ديفيز",
    "discus throw": "رمي القرص",
    "discus throw racing": "سباق رمي القرص",
    "diving": "الغطس",
    "diving racing": "سباق الغطس",
    "dragon boat": "سباق قوارب التنين",
    "dragon boat racing": "سباق قوارب التنين",
    "draughts": "ضامة",
    "draughts racing": "سباق ضامة",
    "dressage": "ترويض الخيول",
    "dressage racing": "سباق ترويض الخيول",
    "equestrian": "الفروسية",
    "equestrian racing": "سباق الفروسية",
    "equestrianism": "الفروسية",
    "equestrianism racing": "سباق الفروسية",
    "esports": "رياضة إلكترونية",
    "esports racing": "سباق رياضة إلكترونية",
    "eventing": "محاكمة الخيول",
    "eventing racing": "سباق محاكمة الخيول",
    "fencing": "مبارزة سيف الشيش",
    "fencing racing": "سباق مبارزة سيف الشيش",
    "field hockey": "هوكي الميدان",
    "field hockey racing": "سباق هوكي الميدان",
    "fifa futsal world cup": "كأس العالم لكرة الصالات",
    "fifa futsal world cup racing": "سباق كأس العالم لكرة الصالات",
    "fifa world cup": "كأس العالم لكرة القدم",
    "fifa world cup racing": "سباق كأس العالم لكرة القدم",
    "figure skating": "التزلج الفني",
    "figure skating racing": "سباق التزلج الفني",
    "floorball": "كرة الأرض",
    "floorball racing": "سباق كرة الأرض",
    "football": "كرة القدم",
    "football racing": "سباق كرة القدم",
    "formula e": "فورمولا إي",
    "formula e racing": "سباق فورمولا إي",
    "formula one": "فورمولا ون",
    "formula one racing": "سباق فورمولا ون",
    "formula racing": "سباقات فورمولا",
    "freestyle skiing": "التزلج الحر",
    "freestyle skiing racing": "سباق التزلج الحر",
    "freestyle wrestling": "المصارعة الحرة",
    "freestyle wrestling racing": "سباق المصارعة الحرة",
    "futsal": "كرة صالات",
    "futsal racing": "سباق كرة صالات",
    "gaelic football": "كرة القدم الغالية",
    "gaelic football racing": "سباق كرة القدم الغالية",
    "go": "غو",
    "go racing": "سباق غو",
    "goalball": "كرة الهدف",
    "goalball racing": "سباق كرة الهدف",
    "golf": "الغولف",
    "golf racing": "سباق الغولف",
    "greco-roman wrestling": "المصارعة اليونانية الرومانية",
    "greco-roman wrestling racing": "سباق المصارعة اليونانية الرومانية",
    "gridiron football": "كرة القدم الأمريكية الشمالية",
    "gridiron football racing": "سباق كرة القدم الأمريكية الشمالية",
    "gymnastics": "الجمباز",
    "gymnastics racing": "سباق الجمباز",
    "hammer throw": "رمي المطرقة",
    "hammer throw racing": "سباق رمي المطرقة",
    "handball": "كرة اليد",
    "handball racing": "سباق كرة اليد",
    "high jump": "القفز العالي",
    "high jump racing": "سباق القفز العالي",
    "high school": "المدارس الثانوية",
    "high school racing": "سباق المدارس الثانوية",
    "hockey": "هوكي",
    "hockey racing": "سباق هوكي",
    "hurling": "القذف",
    "hurling racing": "سباق القذف",
    "ice dancing": "الرقص على الجليد",
    "ice dancing racing": "سباق الرقص على الجليد",
    "ice hockey": "هوكي الجليد",
    "ice hockey racing": "سباق هوكي الجليد",
    "ice skating": "تزلج على الجليد",
    "ice skating racing": "سباق تزلج على الجليد",
    "ice sledge hockey": "هوكي المزلجة على الجليد",
    "ice sledge hockey racing": "سباق هوكي المزلجة على الجليد",
    "inline hockey": "هوكي مضمن",
    "inline hockey racing": "سباق هوكي مضمن",
    "javelin throw": "رمي الرمح",
    "javelin throw racing": "سباق رمي الرمح",
    "ju-jitsu": "جوجوتسو",
    "ju-jitsu racing": "سباق جوجوتسو",
    "judo": "الجودو",
    "judo racing": "سباق الجودو",
    "jujutsu": "جوجوتسو",
    "jujutsu racing": "سباق جوجوتسو",
    "kabaddi": "الكابادي",
    "kabaddi racing": "سباق الكابادي",
    "karate": "الكاراتيه",
    "karate racing": "سباق الكاراتيه",
    "kick boxing": "الكيك بوكسينغ",
    "kick boxing racing": "سباق الكيك بوكسينغ",
    "kickboxing": "الكيك بوكسينغ",
    "kickboxing racing": "سباق الكيك بوكسينغ",
    "korfball": "كورفبال",
    "korfball racing": "سباق كورفبال",
    "kurash": "كوراش",
    "kurash racing": "سباق كوراش",
    "lacrosse": "لاكروس",
    "lacrosse racing": "سباق لاكروس",
    "lawn bowls": "البولينغ العشبي",
    "lawn bowls racing": "سباق البولينغ العشبي",
    "long jump": "القفز الطويل",
    "long jump racing": "سباق القفز الطويل",
    "long-distance running": "ركض المسافات الطويلة",
    "long-distance running racing": "سباق ركض المسافات الطويلة",
    "luge": "الزحف الثلجي",
    "luge racing": "سباق الزحف الثلجي",
    "marathon running": "سباق الماراثون",
    "martial arts": "الفنون القتالية",
    "martial arts racing": "سباق الفنون القتالية",
    "middle-distance running": "ركض المسافات المتوسطة",
    "middle-distance running racing": "سباق ركض المسافات المتوسطة",
    "mixed martial arts": "فنون القتال المختلطة",
    "mixed martial arts racing": "سباق فنون القتال المختلطة",
    "modern pentathlon": "الخماسي الحديث",
    "modern pentathlon racing": "سباق الخماسي الحديث",
    "motocross": "موتو كروس",
    "motocross racing": "سباق موتو كروس",
    "motor": "المحركات",
    "motor racing": "سباق المحركات",
    "motorboat": "الزوارق النارية",
    "motorboat racing": "سباق الزوارق النارية",
    "motorcycle": "الدراجات النارية",
    "motorcycle racing": "سباق الدراجات النارية",
    "motorsport": "رياضة المحركات",
    "motorsport racing": "سباق رياضة المحركات",
    "motorsports": "رياضة المحركات",
    "motorsports racing": "سباق رياضة المحركات",
    "mountain bike": "سباق الدراجات الجبلية",
    "mountain bike racing": "سباق الدراجات الجبلية",
    "muay thai": "موياي تاي",
    "muay thai racing": "سباق موياي تاي",
    "netball": "كرة الشبكة",
    "netball racing": "سباق كرة الشبكة",
    "nordic combined": "التزلج النوردي المزدوج",
    "nordic combined racing": "سباق التزلج النوردي المزدوج",
    "orienteering": "سباق موجه",
    "pair skating": "التزلج الفني على الجليد",
    "pair skating racing": "سباق التزلج الفني على الجليد",
    "pencak silat": "بنكات سيلات",
    "pencak silat racing": "سباق بنكات سيلات",
    "pentathlon": "الخماسي",
    "pentathlon racing": "سباق الخماسي",
    "pesäpallo": "بيسبالو",
    "pesäpallo racing": "سباق بيسبالو",
    "poker": "البوكر",
    "poker racing": "سباق البوكر",
    "pole vault": "القفز بالزانة",
    "pole vault racing": "سباق القفز بالزانة",
    "polo": "البولو",
    "polo racing": "سباق البولو",
    "powerlifting": "رياضة القوة",
    "powerlifting racing": "سباق رياضة القوة",
    "professional wrestling": "مصارعة المحترفين",
    "professional wrestling racing": "سباق مصارعة المحترفين",
    "racewalking": "سباق الجري",
    "racingxx": "سباق السيارات",
    "racquetball": "كرة الراح",
    "racquetball racing": "سباق كرة الراح",
    "racquets": "لعبة الراح",
    "racquets racing": "سباق لعبة الراح",
    "rally": "الرالي",
    "rally racing": "سباق الرالي",
    "rally raid": "الرالي رايد",
    "rally raid racing": "سباق الرالي رايد",
    "rallying": "الراليات",
    "rallying racing": "سباق الراليات",
    "relay race": "سباق تتابع",
    "rhythmic gymnastics": "الجمباز الإيقاعي",
    "rhythmic gymnastics racing": "سباق الجمباز الإيقاعي",
    "rifle shooting": "رماية البندقية",
    "rifle shooting racing": "سباق رماية البندقية",
    "road bicycle racing": "سباق الدراجات على الطريق",
    "road cycling": "سباق الدراجات على الطريق",
    "road race": "سباق الدراجات على الطريق",
    "roller hockey": "هوكي الدحرجة",
    "roller hockey (quad)": "هوكي الدحرجة",
    "roller hockey (quad) racing": "سباق هوكي الدحرجة",
    "roller hockey racing": "سباق هوكي الدحرجة",
    "roller skating": "التزلج بالعجلات",
    "roller skating racing": "سباق التزلج بالعجلات",
    "rowing": "التجديف",
    "rowing racing": "سباق التجديف",
    "rugby": "الرجبي",
    "rugby football": "كرة قدم الرجبي",
    "rugby football racing": "سباق كرة قدم الرجبي",
    "rugby league": "دوري الرجبي",
    "rugby league racing": "سباق دوري الرجبي",
    "rugby racing": "سباق الرجبي",
    "rugby sevens": "سباعيات الرجبي",
    "rugby sevens racing": "سباق سباعيات الرجبي",
    "rugby union": "اتحاد الرجبي",
    "rugby union racing": "سباق اتحاد الرجبي",
    "rugbyunion": "اتحاد الرجبي",
    "rugbyunion racing": "سباق اتحاد الرجبي",
    "running": "الركض",
    "running racing": "سباق الركض",
    "sailing": "الإبحار",
    "sailing (sport)": "رياضة الإبحار",
    "sailing (sport) racing": "سباق رياضة الإبحار",
    "sailing racing": "سباق الإبحار",
    "sambo": "سامبو",
    "sambo racing": "سباق سامبو",
    "sepak takraw": "سيباك تاكرو",
    "sepak takraw racing": "سباق سيباك تاكرو",
    "shooting": "الرماية",
    "shooting racing": "سباق الرماية",
    "shooting sport": "الرماية",
    "shooting sport racing": "سباق الرماية",
    "shooting sports": "الرماية",
    "shooting sports racing": "سباق الرماية",
    "short track speed skating": "التزلج على مسار قصير",
    "short track speed skating racing": "سباق التزلج على مسار قصير",
    "shot put": "دفع الثقل",
    "shot put racing": "سباق دفع الثقل",
    "show jumping": "قفز الحواجز",
    "show jumping racing": "سباق قفز الحواجز",
    "silat": "سيلات",
    "silat racing": "سباق سيلات",
    "single skating": "التزلج الفردي على الجليد",
    "single skating racing": "سباق التزلج الفردي على الجليد",
    "skateboarding": "التزلج على اللوح",
    "skateboarding racing": "سباق التزلج على اللوح",
    "skating": "التزلج",
    "skating racing": "سباق التزلج",
    "skeleton": "الزلاجات الصدرية",
    "skeleton racing": "سباق الزلاجات الصدرية",
    "ski flying": "التزلج الطائر",
    "ski flying racing": "سباق التزلج الطائر",
    "ski jumping": "القفز التزلجي",
    "ski jumping racing": "سباق القفز التزلجي",
    "ski-orienteering": "سباق تزلج موجه",
    "skiing": "التزلج",
    "skiing racing": "سباق التزلج",
    "sledge hockey": "هوكي المزلجة",
    "sledge hockey racing": "سباق هوكي المزلجة",
    "snooker": "السنوكر",
    "snooker racing": "سباق السنوكر",
    "snowboarding": "التزلج على الثلوج",
    "snowboarding racing": "سباق التزلج على الثلوج",
    "soccer": "كرة القدم",
    "soccer racing": "سباق كرة القدم",
    "soft tennis": "كرة المضرب اللينة",
    "soft tennis racing": "سباق كرة المضرب اللينة",
    "softball": "الكرة اللينة",
    "softball racing": "سباق الكرة اللينة",
    "speed skating": "التزلج السريع",
    "speed skating racing": "سباق التزلج السريع",
    "speed skiing": "التزلج السريع",
    "speed skiing racing": "سباق التزلج السريع",
    "sport climbing": "التسلق",
    "sport climbing racing": "سباق التسلق",
    "sprinting": "الجري السريع",
    "sprinting racing": "سباق الجري السريع",
    "squash": "اسكواش",
    "squash racing": "سباق اسكواش",
    "submission wrestling": "مصارعة الخضوع",
    "submission wrestling racing": "سباق مصارعة الخضوع",
    "sumo": "السومو",
    "sumo racing": "سباق السومو",
    "surfing": "الركمجة",
    "surfing racing": "سباق الركمجة",
    "swimming": "السباحة",
    "swimming racing": "سباق السباحة",
    "synchronised swimming": "السباحة المتزامنة",
    "synchronised swimming racing": "سباق السباحة المتزامنة",
    "synchronized swimming": "السباحة المتزامنة",
    "synchronized swimming racing": "سباق السباحة المتزامنة",
    "table tennis": "كرة الطاولة",
    "table tennis racing": "سباق كرة الطاولة",
    "taekwondo": "التايكوندو",
    "taekwondo racing": "سباق التايكوندو",
    "tennis": "كرة المضرب",
    "tennis racing": "سباق كرة المضرب",
    "time trial": "سباق الدراجات ضد الساعة",
    "track and field": "سباقات المضمار والميدان",
    "track cycling": "سباق الدراجات على المضمار",
    "track-and-field athletics": "ألعاب قوى المضمار والميدان",
    "track-and-field athletics racing": "سباق ألعاب قوى المضمار والميدان",
    "trampolining": "جمباز القفز",
    "trampolining racing": "سباق جمباز القفز",
    "triathlon": "السباق الثلاثي",
    "triple jump": "القفز الثلاثي",
    "triple jump racing": "سباق القفز الثلاثي",
    "uiiu 22 formula e season": "موسم فورمولا إي",
    "uiiu 22 formula e season racing": "سباق موسم فورمولا إي",
    "underwater hockey": "هوكي تحت الماء",
    "underwater hockey racing": "سباق هوكي تحت الماء",
    "volleyball": "كرة الطائرة",
    "volleyball racing": "سباق كرة الطائرة",
    "water polo": "كرة الماء",
    "water polo racing": "سباق كرة الماء",
    "water skiing": "التزلج على الماء",
    "water skiing racing": "سباق التزلج على الماء",
    "waterskiing": "التزلج على الماء",
    "waterskiing racing": "سباق التزلج على الماء",
    "weightlifting": "رفع الأثقال",
    "weightlifting racing": "سباق رفع الأثقال",
    "wheelchair basketball": "كرة السلة على الكراسي المتحركة",
    "wheelchair beach handball": "كرة اليد الشاطئية على الكراسي المتحركة",
    "wheelchair curling": "الكيرلنغ على الكراسي المتحركة",
    "wheelchair fencing": "مبارزة سيف الشيش على الكراسي المتحركة",
    "wheelchair handball": "كرة اليد على الكراسي المتحركة",
    "wheelchair rugby": "الرجبي على الكراسي المتحركة",
    "wheelchair rugby league": "دوري الرجبي على الكراسي المتحركة",
    "wheelchair tennis": "كرة المضرب على الكراسي المتحركة",
    "windsurfing": "ركوب القوارب الشراعية",
    "windsurfing racing": "سباق ركوب القوارب الشراعية",
    "wrestling": "المصارعة",
    "wrestling racing": "سباق المصارعة",
    "wushu": "ووشو",
    "wushu racing": "سباق ووشو",
    "xiangqi": "الشطرنج الصيني",
    "xiangqi racing": "سباق الشطرنج الصيني",
    "yacht racing": "سباقات اليخوت"
}
Sports_Keys_For_Team = {
    "acrobatic gymnastics": "للجمباز الاكروباتيكي",
    "acrobatic gymnastics racing": "لسباق الجمباز الاكروباتيكي",
    "aerobics": "لجمباز أيروبيكس",
    "aerobics racing": "لسباق جمباز أيروبيكس",
    "alpine skiing": "للتزلج على المنحدرات الثلجية",
    "alpine skiing racing": "لسباق التزلج على المنحدرات الثلجية",
    "american football": "لكرة القدم الأمريكية",
    "american football racing": "لسباق كرة القدم الأمريكية",
    "american-football": "لكرة القدم الأمريكية",
    "american-football racing": "لسباق كرة القدم الأمريكية",
    "aquatic sports": "للرياضات المائية",
    "aquatic sports racing": "لسباق الرياضات المائية",
    "aquatics": "للرياضات المائية",
    "aquatics racing": "لسباق الرياضات المائية",
    "archery": "للنبالة",
    "archery racing": "لسباق النبالة",
    "artistic gymnastics": "للجمباز الفني",
    "artistic gymnastics racing": "لسباق الجمباز الفني",
    "artistic swimming": "للسباحة الفنية",
    "artistic swimming racing": "لسباق السباحة الفنية",
    "association football": "لكرة القدم",
    "association football racing": "لسباق كرة القدم",
    "athletics": "لألعاب القوى",
    "athletics racing": "لسباق ألعاب القوى",
    "australian rules football": "لكرة القدم الأسترالية",
    "australian rules football racing": "لسباق كرة القدم الأسترالية",
    "auto racing": "لسباق السيارات",
    "automobile racing": "لسباق السيارات",
    "badminton": "لتنس الريشة",
    "badminton racing": "لسباق تنس الريشة",
    "ball hockey": "لهوكي الكرة",
    "ball hockey racing": "لسباق هوكي الكرة",
    "bandy": "للباندي",
    "bandy racing": "لسباق باندي",
    "baseball": "لكرة القاعدة",
    "baseball racing": "لسباق كرة القاعدة",
    "basketball": "لكرة السلة",
    "basketball racing": "لسباق كرة السلة",
    "basque pelota": "لكرة الباسك",
    "basque pelota racing": "لسباق كرة الباسك",
    "beach handball": "لكرة اليد الشاطئية",
    "beach handball racing": "لسباق كرة اليد الشاطئية",
    "beach soccer": "لكرة القدم الشاطئية",
    "beach soccer racing": "لسباق كرة القدم الشاطئية",
    "beach volleyball": "لكرة الطائرة الشاطئية",
    "beach volleyball racing": "لسباق كرة الطائرة الشاطئية",
    "biathlon": "للبياثلون",
    "biathlon racing": "لسباق البياثلون",
    "bicycle motocross": "للبي ام اكس",
    "bicycle motocross racing": "لسباق بي ام اكس",
    "bmx": "لسباق البي إم إكس",
    "bmx racing": "لسباق البي إم إكس",
    "board games": "لألعاب الطاولة",
    "board games racing": "لسباق ألعاب الطاولة",
    "boat racing": "لسباق الزوارق",
    "bobsleigh": "للزلاجة الجماعية",
    "bobsleigh racing": "لسباق الزلاجة الجماعية",
    "boccia": "للبوتشيا",
    "boccia racing": "لسباق البوتشيا",
    "bodybuilding": "لكمال الأجسام",
    "bodybuilding racing": "لسباق كمال الأجسام",
    "bouldering": "للبولدرنق",
    "bouldering racing": "لسباق بولدرنق",
    "boules": "للبوتشي",
    "boules racing": "لسباق بوتشي",
    "bowling": "للبولينج",
    "bowling racing": "لسباق بولينج",
    "bowls": "للبولينج",
    "bowls racing": "لسباق البولينج",
    "boxing": "للبوكسينغ",
    "boxing racing": "لسباق البوكسينغ",
    "bullfighting": "لمصارعة الثيران",
    "bullfighting racing": "لسباق مصارعة الثيران",
    "canadian football": "لكرة القدم الكندية",
    "canadian football racing": "لسباق كرة القدم الكندية",
    "canadian-football": "لكرة القدم الكندية",
    "canadian-football racing": "لسباق كرة القدم الكندية",
    "canoe sprint": "لسباق القوارب",
    "canoeing": "لركوب الكنو",
    "canoeing and kayaking": "للكانو كاياك",
    "canoeing and kayaking racing": "لسباق كانو-كاياك",
    "canoeing racing": "لسباق ركوب الكنو",
    "chess": "للشطرنج",
    "chess racing": "لسباق الشطرنج",
    "chinese martial arts": "للفنون القتالية الصينية",
    "chinese martial arts racing": "لسباق الفنون القتالية الصينية",
    "climbing": "للتسلق",
    "climbing racing": "لسباق التسلق",
    "college": "للكليات",
    "college racing": "لسباق الكليات",
    "cricket": "للكريكت",
    "cricket racing": "لسباق الكريكت",
    "croquet": "للكروكيت",
    "croquet racing": "لسباق الكروكيت",
    "cross country": "للعدو الريفي",
    "cross country racing": "لسباق العدو الريفي",
    "cross country running": "للعدو الريفي",
    "cross country running racing": "لسباق العدو الريفي",
    "cross-country skiing": "للتزلج الريفي",
    "cross-country skiing racing": "لسباق التزلج الريفي",
    "cue sports": "للبلياردو",
    "cue sports racing": "لسباق بلياردو",
    "curling": "للكيرلنغ",
    "curling racing": "لسباق الكيرلنغ",
    "cycle": "للدراجات",
    "cycle race": "لسباق الدراجات",
    "cycle racing": "لسباق الدراجات",
    "cycle speedway": "لسباق الدراجات النارية على المنعطفات",
    "cycling": "لسباق الدراجات الهوائية",
    "cycling road race": "لسباق الدراجات على الطريق",
    "cyclo-cross": "للسيكلو كروس",
    "cyclo-cross racing": "لسباق سيكلو كروس",
    "darts": "للسهام المريشة",
    "darts racing": "لسباق السهام المريشة",
    "davis cup": "لكأس ديفيز",
    "davis cup racing": "لسباق كأس ديفيز",
    "discus throw": "لرمي القرص",
    "discus throw racing": "لسباق رمي القرص",
    "diving": "للغطس",
    "diving racing": "لسباق الغطس",
    "dragon boat": "لسباق قوارب التنين",
    "dragon boat racing": "لسباق قوارب التنين",
    "draughts": "للضامة",
    "draughts racing": "لسباق ضامة",
    "dressage": "لترويض الخيول",
    "dressage racing": "لسباق ترويض الخيول",
    "equestrian": "للفروسية",
    "equestrian racing": "لسباق الفروسية",
    "equestrianism": "للفروسية",
    "equestrianism racing": "لسباق الفروسية",
    "esports": "للرياضة الإلكترونية",
    "esports racing": "لسباق رياضة إلكترونية",
    "eventing": "لمحاكمة الخيول",
    "eventing racing": "لسباق محاكمة الخيول",
    "fencing": "لمبارزة سيف الشيش",
    "fencing racing": "لسباق مبارزة سيف الشيش",
    "field hockey": "لهوكي الميدان",
    "field hockey racing": "لسباق هوكي الميدان",
    "fifa futsal world cup": "لكأس العالم لكرة الصالات",
    "fifa futsal world cup racing": "لسباق كأس العالم لكرة الصالات",
    "fifa world cup": "لكأس العالم لكرة القدم",
    "fifa world cup racing": "لسباق كأس العالم لكرة القدم",
    "figure skating": "للتزلج الفني",
    "figure skating racing": "لسباق التزلج الفني",
    "floorball": "لكرة الأرض",
    "floorball racing": "لسباق كرة الأرض",
    "football": "لكرة القدم",
    "football racing": "لسباق كرة القدم",
    "formula e": "للفورمولا إي",
    "formula e racing": "لسباق فورمولا إي",
    "formula one": "للفورمولا ون",
    "formula one racing": "لسباق فورمولا ون",
    "formula racing": "لسباقات الفورمولا",
    "freestyle skiing": "للتزلج الحر",
    "freestyle skiing racing": "لسباق التزلج الحر",
    "freestyle wrestling": "للمصارعة الحرة",
    "freestyle wrestling racing": "لسباق المصارعة الحرة",
    "futsal": "لكرة الصالات",
    "futsal racing": "لسباق كرة صالات",
    "gaelic football": "لكرة القدم الغالية",
    "gaelic football racing": "لسباق كرة القدم الغالية",
    "go": "للغو",
    "go racing": "لسباق غو",
    "goalball": "لكرة الهدف",
    "goalball racing": "لسباق كرة الهدف",
    "golf": "للغولف",
    "golf racing": "لسباق الغولف",
    "greco-roman wrestling": "للمصارعة اليونانية الرومانية",
    "greco-roman wrestling racing": "لسباق المصارعة اليونانية الرومانية",
    "gridiron football": "لكرة القدم الأمريكية الشمالية",
    "gridiron football racing": "لسباق كرة القدم الأمريكية الشمالية",
    "gymnastics": "للجمباز",
    "gymnastics racing": "لسباق الجمباز",
    "hammer throw": "لرمي المطرقة",
    "hammer throw racing": "لسباق رمي المطرقة",
    "handball": "لكرة اليد",
    "handball racing": "لسباق كرة اليد",
    "high jump": "للقفز العالي",
    "high jump racing": "لسباق القفز العالي",
    "high school": "للمدارس الثانوية",
    "high school racing": "لسباق المدارس الثانوية",
    "hockey": "للهوكي",
    "hockey racing": "لسباق هوكي",
    "hurling": "للقذف",
    "hurling racing": "لسباق القذف",
    "ice dancing": "للرقص على الجليد",
    "ice dancing racing": "لسباق الرقص على الجليد",
    "ice hockey": "لهوكي الجليد",
    "ice hockey racing": "لسباق هوكي الجليد",
    "ice skating": "للتزلج على الجليد",
    "ice skating racing": "لسباق تزلج على الجليد",
    "ice sledge hockey": "لهوكي المزلجة على الجليد",
    "ice sledge hockey racing": "لسباق هوكي المزلجة على الجليد",
    "inline hockey": "للهوكي المضمن",
    "inline hockey racing": "لسباق هوكي مضمن",
    "javelin throw": "لرمي الرمح",
    "javelin throw racing": "لسباق رمي الرمح",
    "ju-jitsu": "للجوجوتسو",
    "ju-jitsu racing": "لسباق جوجوتسو",
    "judo": "للجودو",
    "judo racing": "لسباق الجودو",
    "jujutsu": "للجوجوتسو",
    "jujutsu racing": "لسباق جوجوتسو",
    "kabaddi": "للكابادي",
    "kabaddi racing": "لسباق الكابادي",
    "karate": "للكاراتيه",
    "karate racing": "لسباق الكاراتيه",
    "kick boxing": "للكيك بوكسينغ",
    "kick boxing racing": "لسباق الكيك بوكسينغ",
    "kickboxing": "للكيك بوكسينغ",
    "kickboxing racing": "لسباق الكيك بوكسينغ",
    "korfball": "للكورفبال",
    "korfball racing": "لسباق كورفبال",
    "kurash": "للكوراش",
    "kurash racing": "لسباق كوراش",
    "lacrosse racing": "لسباق لاكروس",
    "lawn bowls": "للبولينغ العشبي",
    "lawn bowls racing": "لسباق البولينغ العشبي",
    "long jump": "للقفز الطويل",
    "long jump racing": "لسباق القفز الطويل",
    "long-distance running": "لركض المسافات الطويلة",
    "long-distance running racing": "لسباق ركض المسافات الطويلة",
    "luge": "للزحف الثلجي",
    "luge racing": "لسباق الزحف الثلجي",
    "marathon running": "لسباق الماراثون",
    "martial arts": "للفنون القتالية",
    "martial arts racing": "لسباق الفنون القتالية",
    "middle-distance running": "لركض المسافات المتوسطة",
    "middle-distance running racing": "لسباق ركض المسافات المتوسطة",
    "mixed martial arts": "لفنون القتال المختلطة",
    "mixed martial arts racing": "لسباق فنون القتال المختلطة",
    "modern pentathlon": "للخماسي الحديث",
    "modern pentathlon racing": "لسباق الخماسي الحديث",
    "motocross": "للموتو كروس",
    "motocross racing": "لسباق موتو كروس",
    "motor": "للمحركات",
    "motor racing": "لسباق المحركات",
    "motorboat": "للزوارق النارية",
    "motorboat racing": "لسباق الزوارق النارية",
    "motorcycle": "للدراجات النارية",
    "motorcycle racing": "لسباق الدراجات النارية",
    "motorsport": "لرياضة المحركات",
    "motorsport racing": "لسباق رياضة المحركات",
    "motorsports": "لرياضة المحركات",
    "motorsports racing": "لسباق رياضة المحركات",
    "mountain bike": "لسباق الدراجات الجبلية",
    "mountain bike racing": "لسباق الدراجات الجبلية",
    "muay thai": "للموياي تاي",
    "muay thai racing": "لسباق موياي تاي",
    "netball": "لكرة الشبكة",
    "netball racing": "لسباق كرة الشبكة",
    "nordic combined": "للتزلج النوردي المزدوج",
    "nordic combined racing": "لسباق التزلج النوردي المزدوج",
    "orienteering": "لسباق الموجه",
    "pair skating": "للتزلج الفني على الجليد",
    "pair skating racing": "لسباق التزلج الفني على الجليد",
    "pencak silat": "للبنكات سيلات",
    "pencak silat racing": "لسباق بنكات سيلات",
    "pentathlon": "للخماسي",
    "pentathlon racing": "لسباق الخماسي",
    "pesäpallo": "للبيسبالو",
    "pesäpallo racing": "لسباق بيسبالو",
    "poker": "للبوكر",
    "poker racing": "لسباق البوكر",
    "pole vault": "للقفز بالزانة",
    "pole vault racing": "لسباق القفز بالزانة",
    "polo": "للبولو",
    "polo racing": "لسباق البولو",
    "powerlifting": "لرياضة القوة",
    "powerlifting racing": "لسباق رياضة القوة",
    "professional wrestling": "لمصارعة المحترفين",
    "professional wrestling racing": "لسباق مصارعة المحترفين",
    "racewalking": "لسباق الجري",
    "racingxx": "لسباق السيارات",
    "racquetball": "لكرة الراح",
    "racquetball racing": "لسباق كرة الراح",
    "racquets": "للعبة الراح",
    "racquets racing": "لسباق لعبة الراح",
    "rally": "للرالي",
    "rally racing": "لسباق الرالي",
    "rally raid": "للرالي رايد",
    "rally raid racing": "لسباق الرالي رايد",
    "rallying": "للراليات",
    "rallying racing": "لسباق الراليات",
    "relay race": "لسباق التتابع",
    "rhythmic gymnastics": "للجمباز الإيقاعي",
    "rhythmic gymnastics racing": "لسباق الجمباز الإيقاعي",
    "rifle shooting": "لرماية البندقية",
    "rifle shooting racing": "لسباق رماية البندقية",
    "road bicycle racing": "لسباق الدراجات على الطريق",
    "road cycling": "لسباق الدراجات على الطريق",
    "road race": "لسباق الدراجات على الطريق",
    "roller hockey": "لهوكي الدحرجة",
    "roller hockey (quad)": "لهوكي الدحرجة",
    "roller hockey (quad) racing": "لسباق هوكي الدحرجة",
    "roller hockey racing": "لسباق هوكي الدحرجة",
    "roller skating": "للتزلج بالعجلات",
    "roller skating racing": "لسباق التزلج بالعجلات",
    "rowing": "للتجديف",
    "rowing racing": "لسباق التجديف",
    "rugby": "للرجبي",
    "rugby football": "لكرة قدم الرجبي",
    "rugby football racing": "لسباق كرة قدم الرجبي",
    "rugby league": "لدوري الرجبي",
    "rugby league racing": "لسباق دوري الرجبي",
    "rugby racing": "لسباق الرجبي",
    "rugby sevens": "لسباعيات الرجبي",
    "rugby sevens racing": "لسباق سباعيات الرجبي",
    "rugby union": "لاتحاد الرجبي",
    "rugby union racing": "لسباق اتحاد الرجبي",
    "rugbyunion": "لاتحاد الرجبي",
    "rugbyunion racing": "لسباق اتحاد الرجبي",
    "running": "للركض",
    "running racing": "لسباق الركض",
    "sailing": "للإبحار",
    "sailing (sport)": "لرياضة الإبحار",
    "sailing (sport) racing": "لسباق رياضة الإبحار",
    "sailing racing": "لسباق الإبحار",
    "sambo": "للسامبو",
    "sambo racing": "لسباق سامبو",
    "sepak takraw": "للسيباك تاكرو",
    "sepak takraw racing": "لسباق سيباك تاكرو",
    "shooting": "للرماية",
    "shooting racing": "لسباق الرماية",
    "shooting sport": "للرماية",
    "shooting sport racing": "لسباق الرماية",
    "shooting sports": "للرماية",
    "shooting sports racing": "لسباق الرماية",
    "short track speed skating": "للتزلج على مسار قصير",
    "short track speed skating racing": "لسباق التزلج على مسار قصير",
    "shot put": "لدفع الثقل",
    "shot put racing": "لسباق دفع الثقل",
    "show jumping": "لقفز الحواجز",
    "show jumping racing": "لسباق قفز الحواجز",
    "silat": "للسيلات",
    "silat racing": "لسباق سيلات",
    "single skating": "للتزلج الفردي على الجليد",
    "single skating racing": "لسباق التزلج الفردي على الجليد",
    "skateboarding": "للتزلج على اللوح",
    "skateboarding racing": "لسباق التزلج على اللوح",
    "skating": "للتزلج",
    "skating racing": "لسباق التزلج",
    "skeleton": "للزلاجات الصدرية",
    "skeleton racing": "لسباق الزلاجات الصدرية",
    "ski flying": "لتزلج طائر",
    "ski flying racing": "لسباق التزلج الطائر",
    "ski jumping": "للقفز التزلجي",
    "ski jumping racing": "لسباق القفز التزلجي",
    "ski-orienteering": "لسباق التزلج الموجه",
    "skiing": "للتزلج",
    "skiing racing": "لسباق التزلج",
    "sledge hockey": "لهوكي المزلجة",
    "sledge hockey racing": "لسباق هوكي المزلجة",
    "snooker": "للسنوكر",
    "snooker racing": "لسباق السنوكر",
    "snowboarding": "للتزلج على الثلوج",
    "snowboarding racing": "لسباق التزلج على الثلوج",
    "soccer": "لكرة القدم",
    "soccer racing": "لسباق كرة القدم",
    "soft tennis": "لكرة المضرب اللينة",
    "soft tennis racing": "لسباق كرة المضرب اللينة",
    "softball": "للكرة اللينة",
    "softball racing": "لسباق الكرة اللينة",
    "speed skating": "لتزلج السريع",
    "speed skating racing": "لسباق التزلج السريع",
    "speed skiing": "للتزلج السريع",
    "speed skiing racing": "لسباق التزلج السريع",
    "sport climbing": "للتسلق",
    "sport climbing racing": "لسباق التسلق",
    "sprinting": "للجري السريع",
    "sprinting racing": "لسباق الجري السريع",
    "squash": "للاسكواش",
    "squash racing": "لسباق اسكواش",
    "submission wrestling": "لمصارعة الخضوع",
    "submission wrestling racing": "لسباق مصارعة الخضوع",
    "sumo": "للسومو",
    "sumo racing": "لسباق السومو",
    "surfing": "للركمجة",
    "surfing racing": "لسباق الركمجة",
    "swimming": "للسباحة",
    "swimming racing": "لسباق السباحة",
    "synchronised swimming": "للسباحة المتزامنة",
    "synchronised swimming racing": "لسباق السباحة المتزامنة",
    "synchronized swimming": "للسباحة المتزامنة",
    "synchronized swimming racing": "لسباق السباحة المتزامنة",
    "table tennis": "لكرة الطاولة",
    "table tennis racing": "لسباق كرة الطاولة",
    "taekwondo": "للتايكوندو",
    "taekwondo racing": "لسباق التايكوندو",
    "tennis": "لكرة المضرب",
    "tennis racing": "لسباق كرة المضرب",
    "time trial": "لسباق الدراجات ضد الساعة",
    "track and field": "لسباقات المضمار والميدان",
    "track cycling": "لسباق الدراجات على المضمار",
    "track-and-field athletics": "لألعاب قوى المضمار والميدان",
    "track-and-field athletics racing": "لسباق ألعاب قوى المضمار والميدان",
    "trampolining": "لجمباز القفز",
    "trampolining racing": "لسباق جمباز القفز",
    "triathlon": "للسباق الثلاثي",
    "triple jump": "للقفز الثلاثي",
    "triple jump racing": "لسباق القفز الثلاثي",
    "uiiu 22 formula e season racing": "لسباق موسم فورمولا إي",
    "underwater hockey": "للهوكي تحت الماء",
    "underwater hockey racing": "لسباق هوكي تحت الماء",
    "volleyball": "لكرة الطائرة",
    "volleyball racing": "لسباق كرة الطائرة",
    "water polo": "لكرة الماء",
    "water polo racing": "لسباق كرة الماء",
    "water skiing": "لتزلج على الماء",
    "water skiing racing": "لسباق التزلج على الماء",
    "waterskiing": "للتزلج على الماء",
    "waterskiing racing": "لسباق التزلج على الماء",
    "weightlifting": "لرفع الأثقال",
    "weightlifting racing": "لسباق رفع الأثقال",
    "wheelchair basketball": "لكرة السلة على الكراسي المتحركة",
    "wheelchair beach handball": "لكرة اليد الشاطئية على الكراسي المتحركة",
    "wheelchair curling": "للكيرلنغ على الكراسي المتحركة",
    "wheelchair fencing": "لمبارزة سيف الشيش على الكراسي المتحركة",
    "wheelchair handball": "لكرة اليد على الكراسي المتحركة",
    "wheelchair rugby": "للرجبي على الكراسي المتحركة",
    "wheelchair rugby league": "لدوري الرجبي على الكراسي المتحركة",
    "wheelchair tennis": "لكرة المضرب على الكراسي المتحركة",
    "windsurfing": "لركوب القوارب الشراعية",
    "windsurfing racing": "لسباق ركوب القوارب الشراعية",
    "wrestling": "للمصارعة",
    "wrestling racing": "لسباق المصارعة",
    "wushu": "للووشو",
    "wushu racing": "لسباق ووشو",
    "xiangqi": "للشطرنج الصيني",
    "xiangqi racing": "لسباق الشطرنج الصيني",
    "yacht racing": "لسباقات اليخوت"
}

Sports_Keys_Lab = Sports_Keys_For_Label
Sports_Keys_Team = Sports_Keys_For_Team
# ---
cccccups = {
    "FIS Alpine Ski World Cup": "كأس العالم للتزلج على المنحدرات الثلجية",
    "alpine skiing world cup": "كأس العالم للتزلج على المنحدرات الثلجية",
}
# ---
Mako_keys_4 = {
    "ice dance": "الرقص على الجليد",
    "freestyle pursuit": "مطاردة حرة",
    "female": "إناث",
    "male": "ذكور",
    "team": "فريق",
    "pairs": "مزدوج",
    "normal hill individual": "تل عادي فردي",
    "Two-man": "رجلين",
    "Two-woman": "سيدتين",
    "four-man": "4 رجال",
    "four-woman": "4 سيدات",
    "Cross-country skiing": "التزلج الريفي",
    "Cross country": "التزلج الريفي",
    "team race": "سباق الفريق",
}
# ---
Mako_keys2 = {
    "free skating": "تزلج حر",
    # "pair skating" : "التزلج الفني على الجليد" ,
    "pair skating": "تزلج مزدوج",
    "bantamweight": "وزن بانتام",
    "featherweight": "وزن الريشة",
    "lightweight": "وزن خفيف",
    "light heavyweight": "وزن ثقيل خفيف",
    "light-heavyweight": "وزن ثقيل خفيف",
    "light middleweight": "وزن خفيف متوسط",
    "middleweight": "وزن متوسط",
    "super heavyweight": "وزن ثقيل سوبر",
    " slalom ": "متعرج",
    "heavyweight": "وزن ثقيل",
    "welterweight": "وزن الويلتر",
    "classical": "كلاسيكي",
    "butterfly": "فراشة",
    "flyweight": "وزن الذبابة",
    "super middleweight": "وزن متوسط سوبر",
    "Pinweight": "وزن الذرة",
    "super flyweight": "وزن الذبابة سوبر",
    "super featherweight": "وزن الريشة سوبر",
    "super bantamweight": "وزن البانتام سوبر",
    "light flyweight": "وزن ذبابة خفيف",
    "light welterweight": "وزن والتر خفيف",
    "cruiserweight": "وزن الطراد",
    "Atomweight": "وزن الذرة",
    "super cruiserweight": "وزن الطراد سوبر",
    # ---
}
# ---
Mako_keys = {
    "tennis at the summer olympics": "كرة المضرب في الألعاب الأولمبية الصيفية",
    "tennis at the winter olympics": "كرة المضرب في الألعاب الأولمبية الشتوية",
    "team jumping": "القفز للفرق",
    "team eventing": "أحداث الفرق",
    "ice dancing": "الرقص على الجليد",
    "– qualification": "– تصفيات",
    "ice dancing": "الرقص على الجليد",
    "World Figure Skating Championships - ice dancing": "بطولة العالم للتزلج الفني - الرقص على الجليد",
    "World Figure Skating Championships": "بطولة العالم للتزلج الفني",
    "ladies' singles free skating": "تزلج حر فردي للسيدات",
    "men's singles free skating": "تزلج حر فردي للرجال",
}
# ---
International_Federation = {
    "FIL World Luge Championships": "كأس العالم للزحف الثلجي",
    "FIL under 23 World Luge Championships": "كأس العالم للزحف الثلجي تحت 23 سنة",
    "NCAA": "الرابطة الوطنية لرياضة الجامعات",
    "NCAA Men's Water Polo Championships": "بطولة كرة الماء للرجال للجامعات",
    "NCAA women's Water Polo Championships": "بطولة كرة الماء للسيدات للجامعات",
    "National Collegiate Athletic Association": "الرابطة الوطنية لرياضة الجامعات",
    "BWF World Championships": "بطولة العالم لكرة الريشة",
    "BWF World Junior Championships": "بطولة العالم لكرة الريشة للناشئين",
    "ConIFA World Football Cup": "كأس العالم لاتحاد الجمعيات المستقلة لكرة القدم",
    "ATP Tour": "رابطة محترفي التنس",
    "ATP Tour tournaments": "بطولات رابطة محترفي التنس",
    "ATP Tour tournaments": "بطولات رابطة محترفي التنس",
    "ATP World Tour": "بطولات العالم لرابطة محترفات التنس",
    "ATP Challenger Tour": "بطولات تشالنجر لرابطة محترفات التنس",
    "WTA Auckland Open": "أوكلاند المفتوحة للسيدات",
    "WTA Madrid Open (tennis)": "مدريد المفتوحة للسيدات (تنس)",
    "WTA Tour tournaments": "بطولات رابطة محترفات التنس",
    "WTA Tour tournaments": "بطولات رابطة محترفات التنس",
    "WTA Tour": "رابطة محترفات التنس",
    "UCI Continental Teams": "الفرق القارية للاتحاد الدولي للدراجات",
    "UCI Continental Teams (Asia)": "الفرق القارية للاتحاد الدولي للدراجات (آسيا)",
    "UCI Continental Teams (Africa)": "الفرق القارية للاتحاد الدولي للدراجات (أفريقيا)",
    "UCI Continental Teams (America)": "الفرق القارية للاتحاد الدولي للدراجات (أمريكا)",
    "UCI Continental Teams (Europe)": "الفرق القارية للاتحاد الدولي للدراجات (أوروبا)",
    "UCI Continental Teams (Oceania)": "الفرق القارية للاتحاد الدولي للدراجات (أوقيانوسيا)",
    "UCI Under 23 Nations' Cup": "كؤوس وطنية لسباقات الدراجات",
    "UCI World Championships": "بطولات العالم للدراجات",
    "UCI World Tour": "طواف العالم للدراجات",
    "UCI America Tour": "طواف أمريكا للدراجات",
    "UCI Asia Tour": "طواف آسيا للدراجات",
    "UCI Europe Tour": "طواف أوروبا للدراجات",
    "UCI Africa Tour": "طواف أفريقيا للدراجات",
    "UCI Oceania Tour": "طواف أوقيانوسيا للدراجات",
    "UCI Women's World Tour": "طواف العالم للدراجات للسيدات",
    "UCI America Tour": "طواف أمريكا للدراجات",
    "UCI Asia Tour": "طواف آسيا للدراجات",
    "UCI Europe Tour": "طواف أوروبا للدراجات",
    "UCI Africa Tour": "طواف أفريقيا للدراجات",
    "UCI Oceania Tour": "طواف أوقيانوسيا للدراجات",
    "Former UCI WorldTeams": "فرق دراجات هوائية عالمية سابقة",
    "UCI WorldTeam riders": "دراجو فرق دراجات هوائية عالمية",
    "UCI WorldTeams": "فرق دراجات هوائية عالمية",
    "UCI Track Cycling World Championships": "بطولة العالم للدراجات على المضمار",
    "UCI Mountain Bike World Cup": "كأس العالم للدراجات الجبلية",
    "UCI Road World Championships": "بطولة العالم لسباق الدراجات على الطريق",
    "UCI Road World Cup": "كأس العالم لسباق الدراجات على الطريق",
    "UCI Women's Road World Cup": "كأس العالم لسباق الدراجات على الطريق للسيدات",
    "UCI Track Cycling World Cup": "كأس العالم لسباق الدراجات على المضمار",
    "UCI Track Cycling World Cup Classics": "كأس العالم لسباق الدراجات على المضمار",
    "UCI Road World Championships – Men's road race": "سباق الطريق في بطولة العالم لسباق الدراجات على الطريق",
    "UCI Road World Championships – Men's team time trial": "سباق الطريق ضد الساعة للفرق في بطولة العالم لسباق الدراجات على الطريق",
    "UCI Track Cycling World Championships – Men's 1 km time trial": "سباق الكيلو متر ضد الساعة في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's individual pursuit": "سباق المطاردة الفردية في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's keirin": "سباق الكيرين في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's madison": "سباق ماديسون في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's omnium": "سباق الأومنيوم في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's points race": "سباق النقاط في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's scratch": "سباق الخدش - السكراتش في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's sprint": "سباق السرعة الفردية في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's team pursuit": "سباق المطاردة الفرقية في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Men's team sprint": "سباق السرعة الفردية للفرق في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's 500 m time trial": "سباق 500 متر ضد الساعة للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's individual pursuit": "سباق المطاردة الفردية للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's keirin": "سباق الكيرين للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's madison": "سباق ماديسون للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's omnium": "سباق الأومنيوم للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's points race": "سباق النقاط للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's scratch": "سباق الخدش للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's sprint": "سباق السرعة الفردية للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's team pursuit": "سباق المطاردة الفرقية للنساء في بطولة الدراجات على المضمار",
    "UCI Track Cycling World Championships – Women's team sprint": "سباق السرعة الفردية لفرق النساء في بطولة الدراجات على المضمار",
    "OFC U-17 Championships": "كأس أوقيانوسيا للأمم تحت 17 سنة",
    "OFC Nations Cup": "كأس أوقيانوسيا للأمم",
    "OFC U-20 Championships": "كأس أوقيانوسيا للأمم تحت 20 سنة",
    "OFC Nations Cup": "كأس أوقيانوسيا للأمم",
    "OFC U-17 Championships": "كأس أوقيانوسيا للأمم تحت 17 سنة",
    "OFC U-20 Championships": "كأس أوقيانوسيا للأمم تحت 20 سنة",
    "OFC Champions League": "دوري أبطال أوقيانوسيا",
    "AFC Asian Cup Finals": "نهائيات كأس آسيا",
    "AFC Futsal Championships": "بطولة آسيا لكرة القدم الخماسية",
    "AFC U-16 Women's Championships": "بطولة آسيا تحت 16 سنة لكرة القدم للسيدات",
    "AFC Futsal Championships": "بطولة آسيا لكرة القدم الخماسية",
    "AFC President's Cup": "كأس رئيس الاتحاد الآسيوي",
    "AFC Solidarity Cup": "كأس التضامن الآسيوي",
    "AFC Women's Asian Cup": "كأس الأمم الآسيوية لكرة القدم للسيدات",
    "AFC U-16 Championships": "بطولة آسيا للناشئين تحت 16 سنة",
    "AFC Asian Cup": "كأس آسيا",
    "AFC Futsal Club Championships": "بطولة آسيا لكرة القدم الخماسية للأندية",
    "CONCACAF Championships": "بطولة أمريكا الشمالية",
    "CONCACAF Gold Cup": "كأس الكونكاكاف الذهبية",
    "CONCACAF U17 Championships": "الكأس الذهبية تحت 17 سنة لكرة القدم",
    "CONCACAF Under-20 Championships": "الكأس الذهبية تحت 20 سنة لكرة القدم",
    "CONCACAF Women's Championships": "بطولة أمريكا الشمالية للسيدات",
    "CONCACAF Women's U-10 Championships": "بطولة أمريكا الشمالية للسيدات تحت 10 سنة",
    "CONCACAF Women's U-17 Championships": "بطولة أمريكا الشمالية للسيدات تحت 17 سنة",
    "CONCACAF U17 Championships": "الكأس الذهبية تحت 17 سنة لكرة القدم",
    "CONCACAF Champions League": "دوري أبطال الكونكاكاف",
    "CONCACAF Under-20 Championships": "الكأس الذهبية تحت 20 سنة لكرة القدم",
    "AFF U-23 Championships": "بطولة اتحاد آسيان تحت 23 سنة",
    "AFF U-23 Youth Championships": "بطولة اتحاد آسيان تحت 23 سنة للشباب",
    "AFF Championships": "بطولة اتحاد آسيان لكرة القدم",
    "EHF Champions League": "دوري أبطال أوروبا لكرة اليد",
    "Women's EHF Champions League": "دوري أبطال أوروبا لكرة اليد للسيدات",
    "EHF Cup": "كأس أوروبا لكرة اليد",
    "Women's EHF Cup": "كأس أوروبا لكرة اليد للسيدات",
    "Women's EHF Challenge Cup": "كأس التحدي الأوروبية لكرة اليد للسيدات",
    "EHF Champions League": "دوري أبطال أوروبا لكرة اليد",
    "EHF Cup": "كأس أوروبا لكرة اليد",
    "Women's EHF Cup Winners' Cup": "كأس أبطال الكؤوس الأوروبية لكرة اليد للسيدات",
    "EHF Women's Cup Winners' Cup": "كأس أبطال الكؤوس الأوروبية لكرة اليد للسيدات",
    "EHF Women's Champions League": "دوري أبطال أوروبا لكرة اليد للسيدات",
    "AFC Champions League": "دوري أبطال آسيا",
    "ASEAN Football Championships": "بطولة اتحاد آسيان لكرة القدم",
    "FIBA EuroBasket": "بطولة أمم أوروبا لكرة السلة",
    "FIBA Women's Basketball World Cup": "كأس العالم لكرة السلة للسيدات",
    "FIBA European Champions Cup": "كأس أبطال أوروبا لكرة السلة",
    "FIBA Women's European Champions Cup": "كأس أبطال أوروبا لكرة السلة للسيدات",
    "FIBA Women's World Cup": "كأس العالم لكرة السلة للسيدات",
    "FIBA World Cup": "كأس العالم لكرة السلة",
    "FIBA Asia Under-18 Championships": "بطولة فيبا آسيا تحت 18 سنة لكرة السلة",
    "FIBA Under-20 World Championships": "بطولة العالم تحت 20 سنة لكرة السلة",
    "FIBA Under-19 World Championships": "بطولة العالم تحت 19 سنة لكرة السلة",
    "FIBA Under-18 World Championships": "بطولة العالم تحت 18 سنة لكرة السلة",
    "FIBA Under-17 World Championships": "بطولة العالم تحت 17 سنة لكرة السلة",
    "FIBA Under-16 World Championships": "بطولة العالم تحت 16 سنة لكرة السلة",
    "FIBA competitions": "منافسات الاتحاد الدولي لكرة السلة",
    "FIBA Korać Cup": "كأس كوراتش لكرة السلة",
    "FIBA Saporta Cup": "كأس سابورتا",
    "FIBA Asia Cup": "كأس أمم آسيا لكرة السلة",
    "FIBA Americas League": "دوري الأمريكتين لكرة السلة",
    "FIBA Americas Championships": "بطولة أمم الأمريكتين لكرة السلة",
    "FIBA": "الاتحاد الدولي لكرة السلة",
    "FIBA AmeriCup": "بطولة أمم الأمريكتين لكرة السلة",
    "FIBA Africa Championships": "بطولة أمم أفريقيا لكرة السلة",
    "FIBA EuroBasket": "بطولة أمم أوروبا لكرة السلة",
    "FIBA Asia Championships": "بطولة أمم آسيا لكرة السلة",
    "FIBA Basketball World Cup": "بطولة كأس العالم لكرة السلة",
    "FIBA World Championships": "بطولة كأس العالم لكرة السلة",
    "FIBA World Championship for Women": "بطولة كأس العالم لكرة السلة للسيدات",
    "FIBA Korać Cup": "كأس كوراتش لكرة السلة",
    "FIFA World Cup": "كأس العالم لكرة القدم",
    # "FIFA World Cup":"كأس العالم",
    # "FIFA Women's World Cup":"كأس العالم للسيدات",
    "FIFA Women's World Cup": "كأس العالم لكرة القدم للسيدات",
    "FIFA U-17 World Cup": "كأس العالم تحت 17 سنة لكرة القدم",
    "FIFA U-17 Women's World Cup": "كأس العالم تحت 17 سنة لكرة القدم للسيدات",
    "FIFA U-20 World Cup": "كأس العالم تحت 20 سنة لكرة القدم",
    "FIFA U-20 Women's World Cup": "كأس العالم تحت 20 سنة لكرة القدم للسيدات",
    "the FIFA World Cup": "كأس العالم لكرة القدم",
    "FIFA Club World Cup": "كأس العالم للأندية",
    "FIFA Beach Soccer World Cup": "كأس العالم الشاطئية",
    "FIFA World Cup qualification (CAF)": "تصفيات كأس العالم لكرة القدم (أفريقيا)",
    "FIFA World Cup qualification (AFC)": "تصفيات كأس العالم لكرة القدم (آسيا)",
    "FIFA Women's World Cup qualification": "تصفيات كأس العالم لكرة القدم للسيدات",
    "FIFA Futsal World Cup Ney": "بطولة كأس العالم داخل الصالات",
    "FIFA World Cup players": "لاعبو كأس العالم لكرة القدم",
    "The Best FIFA Football Awards": "جوائز الفيفا للأفضل كرويا",
    "IAAF Continental Cup": "كأس العالم لألعاب القوى",
    "IAAF World U20 Championships": "بطولة العالم للناشئين لألعاب القوى",
    "IAAF Diamond League": "دوري ماسي",
    "IAAF World Indoor Championships in Athletics": "بطولة العالم لألعاب القوى داخل الصالات",
    "IAAF World Cross Country Championships": "بطولة العالم للعدو الريفي",
    "IAAF World Indoor Championships in Athletics": "بطولة العالم لألعاب القوى داخل الصالات",
    "IAAF World Indoor Championships": "بطولة العالم لألعاب القوى داخل الصالات",
    "IAAF World Indoor Games": "بطولة العالم لألعاب القوى داخل الصالات",
    "IAAF World Junior Championships in Athletics": "بطولة العالم للناشئين لألعاب القوى",
    "IAAF World Cross Country Championships": "بطولة العالم للعدو الريفي",
    "IAAF World Indoor Championships": "بطولة العالم لألعاب القوى داخل الصالات",
    "IAAF World Indoor Games": "بطولة العالم لألعاب القوى داخل الصالات",
    "SAFF Championships": "بطولة اتحاد جنوب آسيا لكرة القدم",
    "SAFF Championships": "بطولة اتحاد جنوب آسيا لكرة القدم",
    "FIS Nordic World Ski Championships": "بطولة العالم للتزلج النوردي على الثلج",
    "FIS Nordic World Ski Championships": "بطولة العالم للتزلج النوردي على الثلج",
    "FIVB Women's Volleyball World Championships": "بطولة العالم لكرة الطائرة للسيدات",
    "FIVB Volleyball World Cup": "كأس العالم لكرة الطائرة",
    "FIVB Volleyball Women's World Cup": "كأس العالم لكرة الطائرة للسيدات",
    "FIVB Volleyball Men's World Championships": "بطولة العالم للكرة الطائرة",
    "FIVB Volleyball World Championships": "بطولة العالم لكرة الطائرة",
    "FIVB Volleyball World League": "الدوري العالمي للكرة الطائرة",
    "IIHF World Championships": "بطولة العالم لهوكي الجليد",
    "IIHF Challenge Cup of Asia": "كأس التحدي الآسيوي لهوكي الجليد",
    # "UEFA Euro":"بطولة أمم أوروبا لكرة القدم",
    "UEFA Women's Euro": "بطولة أمم أوروبا لكرة القدم للسيدات",
    "UEFA Champions League": "دوري أبطال أوروبا",
    "UEFA Euro 2004 qualifying": "تصفيات بطولة أمم أوروبا لكرة القدم 2004",
    "UEFA European Championship video games": "ألعاب فيديو بطولة أمم أوروبا لكرة القدم",
    "UEFA Futsal Euro 2012": "بطولة أوروبا لكرة الصالات 2012",
    "UEFA Women's Euro 1993": "بطولة أمم أوروبا لكرة القدم للسيدات 1993",
    "UEFA Women's Euro 1995": "بطولة أمم أوروبا لكرة القدم للسيدات 1995",
    "UEFA Women's Euro 1997": "بطولة أمم أوروبا لكرة القدم للسيدات 1997",
    "UEFA Women's Euro 2009": "بطولة أمم أوروبا لكرة القدم للسيدات 2009",
    "UEFA Women's Euro 2013": "بطولة أمم أوروبا لكرة القدم للسيدات 2013",
    "UEFA Women's Euro 2013 qualifying": "تصفيات بطولة أمم أوروبا لكرة القدم للسيدات 2013",
    "UEFA Women's Euro 2017": "بطولة أمم أوروبا لكرة القدم للسيدات 2017",
    "UEFA Women's Under-17 Championships": "بطولة أوروبا تحت 17 سنة لكرة القدم للسيدات",
    "UEFA Europa League": "الدوري الأوروبي",
    "UEFA Women's Championships": "بطولة أمم أوروبا للسيدات",
    "UEFA Futsal Euro": "بطولة أوروبا لكرة الصالات",
    "UEFA Euro": "بطولة أمم أوروبا",
    "UEFA Champions League": "دوري أبطال أوروبا",
    "2017–18 UEFA Champions League": "دوري أبطال أوروبا 2017–18",
    # "UEFA European Championships":"بطولة أمم أوروبا لكرة القدم",
    "UEFA Nations League": "دوري الأمم الأوروبية",
    "UEFA European Championship qualifying": "تصفيات بطولة أمم أوروبا",
    "UEFA Super Cup": "كأس السوبر الأوروبي",
    "UEFA Cup": "كأس الاتحاد الأوروبي",
    "UEFA Intertonto": "كأس إنترتوتو",
    "UEFA Cup Winners' Cup": "كأس الكؤوس الأوروبية",
    "UEFA Regions' Cup": "كأس المقاطعات الأوروبية",
    "UEFA European Championships": "بطولة أمم أوروبا",
    "UEFA European Football Championships": "بطولة أمم أوروبا",
    "UEFA European Under-10 Championships": "بطولة أمم أوروبا تحت 10 سنة",
    "UEFA Europa League": "الدوري الأوروبي",
    "UEFA Youth League": "الدوري الأوروبي للشباب",
    "UEFA Futsal Championships": "بطولة أمم أوروبا داخل الصالات",
    "UEFA European Under-16 Football Championships": "بطولة أوروبا تحت 16 سنة لكرة القدم",
    "UEFA European Under-17 Football Championships": "بطولة أوروبا تحت 17 سنة لكرة القدم",
    "UEFA Women's Under-17 Championships": "بطولة أوروبا تحت 17 سنة لكرة القدم للسيدات",
    "UEFA European Under-19 Football Championships": "بطولة أوروبا تحت 19 سنة لكرة القدم",
    "UEFA Women's Under-19 Championships": "بطولة أوروبا تحت 19 سنة لكرة القدم للسيدات",
    "UEFA European Under-21 Championships": "بطولة أوروبا تحت 21 سنة لكرة القدم",
    "UEFA European Under-21 Football Championships": "بطولة أوروبا تحت 21 سنة لكرة القدم",
    "CAF Confederation Cup": "كأس الكونفيدرالية الأفريقية",
    "CAF Champions League": "دوري أبطال أفريقيا",
    "UNAF U-17 Tournament": "بطولة أمم شمال أفريقيا تحت 17 سنة",
    "UNAF U-20 Tournament": "بطولة أمم شمال أفريقيا تحت 20 سنة",
    "UNAF Club Cup": "كأس اتحاد شمال أفريقيا",
    "UNAF U-17 Tournament": "بطولة أمم شمال أفريقيا تحت 17 سنة",
    "UNAF Club Cup": "كأس اتحاد شمال أفريقيا",
    "UNAF U-20 Tournament": "بطولة أمم شمال أفريقيا تحت 20 سنة",
    "UNAF U-23 Tournament": "بطولة أمم شمال أفريقيا تحت 23 سنة",
    "FINA World Aquatics Championships": "بطولة العالم للألعاب المائية",
    "FINA Water Polo World League": "الدوري العالمي لكرة الماء",
    "FINA": "الاتحاد الدولي للسباحة",
    "FINA World Swimming Championships (25 m)": "بطولة العالم للسباحة (25 متر)",
    "FINA World Swimming Championships": "بطولة العالم للسباحة",
    "FINA World Aquatics Championships": "بطولة العالم للألعاب المائية",
}
# ---
olympics = {
    "Women's 500 m time trial": "سباق 500 متر ضد الساعة للسيدات",
    "Women's individual pursuit": "سباق المطاردة الفردية للسيدات",
    "Women's keirin": "سباق الكيرين للسيدات",
    "Women's madison": "سباق ماديسون للسيدات",
    "Women's omnium": "سباق الأومنيوم للسيدات",
    "Women's points race": "سباق النقاط للسيدات",
    "Women's scratch": "سباق الخدش للسيدات",
    "Women's sprint": "سباق السرعة الفردية للسيدات",
    "Women's team pursuit": "سباق المطاردة الفرقية للسيدات",
    "Women's team sprint": "سباق السرعة الفردية لفرق السيدات",
    # ---
    "Women's road race": "سباق الطريق للسيدات",
    "Women's time trial": "سباق الطريق ضد الساعة للسيدات",
    "Women's road race": "سباق الطريق للسيدات",
    "Women's time trial": "سباق الطريق ضد الساعة للسيدات",
    # ---
    "Men's road race": "سباق الطريق",
    "Men's team time trial": "سباق الطريق ضد الساعة للفرق",
    "Men's 1 km time trial": "سباق الكيلو متر ضد الساعة",
    "Men's individual pursuit": "سباق المطاردة الفردية",
    "Men's keirin": "سباق الكيرين",
    "Men's madison": "سباق ماديسون",
    "Men's omnium": "سباق الأومنيوم",
    "Men's points race": "سباق النقاط",
    "Men's scratch": "سباق الخدش - السكراتش",
    "Men's sprint": "سباق السرعة الفردية",
    "Men's team pursuit": "سباق المطاردة الفرقية",
    "Men's team sprint": "سباق السرعة الفردية للفرق",
}
# ---
for fff, ffflab in Sports_Keys_Team.items():  # – winter youth olympics
    # cccccups["%s world Championships" %  fff.lower() ] = "بطولة العالم %s"  % ffflab
    cccccups[f"{fff.lower()} world championships"] = f"بطولة العالم {ffflab}"
    cccccups[f"world team {fff.lower()} championships"] = f"بطولة العالم {ffflab} للفرق"
    cccccups[f"{fff.lower()} world team championships"] = f"بطولة العالم {ffflab} للفرق"
    cccccups[f"world men's {fff.lower()} championships"] = f"بطولة العالم {ffflab} للرجال"
    cccccups[f"{fff.lower()} world men's championships"] = f"بطولة العالم {ffflab} للرجال"
    cccccups[f"world women's {fff.lower()} championships"] = f"بطولة العالم {ffflab} للسيدات"
    cccccups[f"{fff.lower()} world women's championships"] = f"بطولة العالم {ffflab} للسيدات"
# ---
for fff, ffflab in Sports_Keys_Lab.items():  # – winter youth olympics
    olympics[f"{fff.lower()} at the summer olympics"] = f"{ffflab} في الألعاب الأولمبية الصيفية"
    olympics[f"{fff.lower()} at the winter youth olympics"] = f"{ffflab} في الألعاب الأولمبية الشبابية الشتوية"
    olympics[f"{fff.lower()} at the winter olympics"] = f"{ffflab} في الألعاب الأولمبية الشتوية"
    Mako_keys_4[f" mens's {fff.lower()}"] = f"{ffflab} للرجال"
    Mako_keys_4[f" womens's {fff.lower()}"] = f"{ffflab} للسيدات"
    # Mako_keys_4[ fff.lower() ] = ffflab
# ---
# individual
# jumping
keys_1 = {
    "individual": "فردي",
    "girls": "فتيات",
    "mixed": "مختلط",
    "boys": "فتيان",
    "singles": "فردي",
    "women's": "سيدات",
    "womens": "سيدات",
    "ladies": "سيدات",
    "ladies": "سيدات",
    "mens": "رجال",
    "men's": "رجال",
    # ---
}  # men's individual road race
# ---
keys_2 = {
    "tournament": "مسابقة",
    # "single" : "فردي",
    "individual": "فردي",
    "singles": "فردي",
    "qualification": "تصفيات",
    "team pursuit": "مطاردة الفرق",
    "large hill": "تل كبير",
    "normal hill": "تل عادي",
    "team": "فريق",
    "decathlon": "ديكاتلون",
    # "double" : "زوجي",
    "doubles": "زوجي",
    # "single sculls" : "تجديف فردي",
    # "double sculls" : "تجديف زوجي",
    # "quadruple sculls" : "تجديف رباعي",
    # "coxless pair" : "رباعي مزدوج",
    "quadruple": "رباعي",
    "coxless": "رباعي",
    "jumping": "قفز",
}
# ---
keys_3 = {
    "road race": "سباق الطريق",
    "pursuit": "مطاردة",
    "team": "فريق",
    "decathlon": "ديكاتلون",
    "individual": "فردي",
    "sculls": "تجديف",
    "pair": "مزدوج",
}
# ---
for start in keys_1:  # –
    for suff in keys_2:  # –
        lab_ke = f"{keys_2[suff]} {keys_1[start]}"
        # ---
        ke = f"{start} {suff}"
        Mako_keys2[ke.lower()] = lab_ke
        # ---
        ke44 = f"{suff} {start}"
        Mako_keys2[ke44.lower()] = lab_ke
        for su3 in keys_3:
            lab_ke3 = f"{keys_2[suff]} {keys_1[start]} {keys_3[su3]}"
            # ---
            ke3 = f"{start} {suff} {su3}"
            Mako_keys2[ke3.lower()] = lab_ke3
            # ---
            lab_ke2 = f"{keys_2[suff]} {keys_3[su3]}"
            # ---
            ke2 = f"{suff} {su3}"
            Mako_keys2[ke2.lower()] = lab_ke2
# ---
